import type { ExpeditionPageData } from "@/components/ExpeditionDetail"

/**
 * Contenido (es) de las páginas de detalle de expedición, siguiendo la
 * plantilla del diseño aprobado (ballen-1). Safari La Ventana y Tiburón
 * Ballena vienen textuales de la referencia; el resto adapta el contenido
 * real existente a la misma estructura.
 */
export const expeditionPages: Record<string, ExpeditionPageData> = {
	"safari-la-ventana": {
		breadcrumb: "Safari La Ventana",
		hero: {
			image: "/images/orca-safari.jpg",
			alt: "Seafari en La Ventana, Baja California Sur",
			kicker: "La Ventana · Isla Cerralvo",
			title: "Encuentra lo extraordinario",
			text: "Explora uno de los escenarios marinos más sorprendentes del Golfo de California. Cada salida es distinta. Cada encuentro es real.",
		},
		quickFacts: [
			{ value: "6 horas", label: "8:00 AM salida" },
			{ value: "2-8 personas", label: "Compartido o privado" },
			{ value: "Abr - Jun", label: "Temporada de móbulas" },
			{ value: "40 min", label: "Desde La Paz" },
		],
		story: {
			kicker: "Qué es el Seafari",
			title: "No hay guion. No hay show.",
			paragraphs: [
				"El Seafari inicia en La Ventana, a 40 minutos de La Paz, donde nos dirigimos rumbo al azul profundo. A bordo de la lancha, guiados por biólogos marinos y capitanes locales, navegamos en busca de lo inesperado: móbulas que vuelan, delfines que nos escoltan, ballenas que emergen como leyendas vivas.",
				"A diferencia de un tour convencional donde todo está previamente establecido, el Seafari está diseñado para vivir una experiencia dinámica y auténtica, enfocada en maximizar los encuentros con vida silvestre. Cada salida es única — y por eso trabajamos con vida salvaje en libertad: no garantizamos avistamientos específicos, pero sí garantizamos compromiso, experiencia y un enfoque respetuoso.",
			],
			commitTitle: "Nuestro compromiso",
			commitText: "Respetamos profundamente la vida marina. Nuestros safaris están diseñados para observar sin perturbar, aprender sin interferir, y maravillarse sin dañar el ecosistema que nos acoge.",
		},
		split: {
			image: "/images/safari/nuestrocompromiso2.jpeg",
			alt: "Guía con equipo de snorkel en Seafari La Ventana",
			kicker: "Cómo es la experiencia",
			title: "Un día completo diseñado para el encuentro",
			text: "Navegación en busca de vida marina, snorkel cuando las condiciones lo permiten y exploración en Isla Cerralvo — todo guiado por biólogos marinos que leen el comportamiento animal y las señales del mar en tiempo real. Cerramos el día con ceviche fresco y fruta de temporada frente al mar.",
		},
		timeline: {
			kicker: "Itinerario detallado",
			title: "Hora por hora",
			items: [
				{ time: "8:00 AM", title: "Bienvenida y briefing", text: "Conoce a tu guía biólogo marino y recibe una introducción sobre la vida marina que podrías encontrar." },
				{ time: "8:30 - 11:30 AM", title: "Navegación y búsqueda", text: "Navegamos en busca de vida marina, siguiendo patrones de comportamiento y señales naturales." },
				{ time: "11:30 AM - 1:00 PM", title: "Exploración en Isla Cerralvo", text: "Dependiendo de las condiciones, snorkel o exploración de las aguas cristalinas alrededor de la isla." },
				{ time: "1:00 - 1:30 PM", title: "Refrigerio y descanso", text: "Ceviche fresco y frutas de temporada mientras descansamos." },
				{ time: "1:30 - 2:00 PM", title: "Regreso escénico", text: "Navegamos de regreso a La Ventana, con posibilidad de más avistamientos en el camino." },
			],
		},
		fauna: {
			kicker: "Fauna por temporada",
			title: "El Golfo de California es uno de los mares más biodiversos del planeta",
			items: [
				{ image: "/images/especies/mobulaschafa.jpeg", alt: "Móbulas", label: "Móbulas · Abr-Jun" },
				{ image: "/images/especies/delfinsaltando.jpeg", alt: "Delfín saltando", label: "Delfines · Todo el año" },
				{ image: "/images/especies/ballenasaltando2.jpeg", alt: "Ballena jorobada", label: "Ballena Jorobada · Dic-Abr" },
				{ image: "/images/especies/lobomarinonadando.jpeg", alt: "Lobo marino", label: "Lobos Marinos · Todo el año" },
				{ image: "/images/especies/cachalote2.jpeg", alt: "Cachalote", label: "Cachalotes · Jun-Nov" },
				{ image: "/images/especies/orcalaventana.jpeg", alt: "Orca", label: "Orcas · Impredecible" },
			],
		},
		includes: {
			kicker: "Tu experiencia incluye",
			title: "Todo lo que necesitas para disfrutar el Seafari",
			items: [
				{ title: "Safari marino de 6 hrs", text: "Navegación en busca de vida marina con biólogos marinos y capitanes locales expertos en la zona." },
				{ title: "Equipo completo", text: "Neopreno, snorkel y equipo de playa incluidos para toda la salida." },
				{ title: "Picnic en Isla Cerralvo", text: "Ceviche fresco, fruta de temporada, snacks y bebidas frente al mar." },
				{ title: "Foto y video incluidos", text: "Capturas profesionales de tu experiencia, listas para revivir el momento." },
			],
		},
		pricing: {
			kicker: "Precio",
			title: "Reserva tu Seafari en La Ventana",
			cards: [
				{
					name: "Compartido",
					amount: "$3,000",
					amountNote: "MXN / persona",
					items: [
						"Mínimo 4 personas",
						"Lancha compartida, hasta 8-10 pax",
						"Neopreno, snorkel y equipo de playa",
						"Picnic en Isla Cerralvo",
						"Guía biólogo marino y foto/video incluidos",
					],
					waText: "Quiero reservar el Safari La Ventana compartido",
				},
				{
					name: "Lancha privada",
					amount: "$16,000",
					amountNote: "MXN / hasta 8 pax",
					items: [
						"Lancha exclusiva para tu grupo",
						"Horario flexible dentro del día",
						"Mismo itinerario y equipo incluido",
						"Guía biólogo marino y foto/video incluidos",
					],
					waText: "Quiero reservar el Safari La Ventana privado",
					featured: true,
					featuredTag: "Privado",
				},
			],
			note: "Recomendado para quienes sepan nadar; niños viajan bajo supervisión de un adulto. Cupo limitado por temporada de móbulas (abril-junio).",
		},
		finalCta: {
			image: "/images/orca-safari.jpg",
			alt: "Móbulas saltando en La Ventana",
			title: "Móbulas que vuelan, ballenas que emergen",
			text: "Vive un safari sin guion a 40 minutos de La Paz. Cupos limitados por salida.",
			waText: "Quiero reservar el Safari La Ventana",
		},
	},

	"tiburon-ballena": {
		breadcrumb: "Tiburón Ballena",
		hero: {
			image: "/snorkeling-coral-reef.jpg",
			alt: "Nado con tiburón ballena en La Paz",
			kicker: "La Paz · Oct - Abr",
			title: "Nada con el pez más grande del mundo",
			text: "El nado con tiburón ballena es una de las experiencias marinas más emblemáticas de La Paz, Baja California Sur. Aguas tranquilas, encuentros responsables y regulados.",
		},
		quickFacts: [
			{ value: "2 horas", label: "Muelle fiscal La Paz" },
			{ value: "Oct - Abr", label: "Temporada oficial" },
			{ value: "Regulado", label: "Zona y permisos oficiales" },
			{ value: "Todas las edades", label: "Actividad accesible" },
		],
		story: {
			kicker: "Nada con el pez más grande del mundo",
			title: "Un gigante gentil, en su temporada",
			paragraphs: [
				"Cada temporada, estos gigantes del mar llegan a las aguas tranquilas de la bahía, creando una oportunidad única para observarlos y nadar junto a ellos de manera responsable, siempre bajo lineamientos oficiales y con operadores autorizados.",
				"Nuestros guías especializados te acompañarán durante toda la experiencia, compartiendo información sobre la especie, su importancia ecológica y las buenas prácticas para disfrutar este encuentro con respeto y conciencia.",
			],
			commitTitle: "Actividad regulada",
			commitText: "En La Paz, el acceso a la zona de nado y observación está regulado. Solo pueden ingresar embarcaciones con permiso vigente, respetando turnos y tiempos autorizados por las autoridades para proteger a la especie.",
		},
		split: {
			image: "/manta-ray-swimming.png",
			alt: "Vida marina en el Golfo de California",
			kicker: "Qué más puedes ver",
			title: "El Golfo de California no descansa",
			text: "En el trayecto hacia la zona de observación es común cruzarte con lobos marinos curiosos y delfines que se acercan a la lancha — el Mar de Cortés, \"el acuario del mundo\" según Jacques Cousteau, siempre tiene algo que mostrar.",
		},
		timeline: {
			kicker: "Itinerario del día",
			title: "Paso a paso",
			items: [
				{ time: "Muelle fiscal", title: "Bienvenida y briefing", text: "Nos encontramos en el Muelle fiscal de La Paz. Introducción sobre la experiencia, uso del equipo y reglas para una actividad responsable." },
				{ time: "Navegación", title: "Búsqueda y localización", text: "Navegamos dentro del área permitida siguiendo los protocolos establecidos por las autoridades, respetando turnos y tiempos autorizados." },
				{ time: "En el agua", title: "Nado con tiburón ballena", text: "Encuentro guiado y responsable con el pez más grande del mundo, siempre acompañado de tu guía certificado." },
				{ time: "Regreso", title: "Vuelta a La Paz", text: "Regresamos al muelle con las fotos y videos de tu encuentro." },
			],
		},
		includes: {
			kicker: "Tu experiencia incluye",
			title: "Todo lo necesario para un encuentro seguro y responsable",
			items: [
				{ title: "Transporte en lancha", text: "Salida y regreso desde el Muelle fiscal de La Paz." },
				{ title: "Guía certificado", text: "Equipo especializado bilingüe que comparte el conocimiento de la especie." },
				{ title: "Equipo de snorkel", text: "Visor, aletas y chaleco salvavidas para explorar con tranquilidad." },
				{ title: "Fotos y videos", text: "Recuerdos auténticos de tu aventura, capturados en el momento." },
				{ title: "Permiso regulado", text: "Acceso autorizado a la zona oficial de observación." },
			],
		},
		pricing: {
			kicker: "Opciones de tour",
			title: "Elige la experiencia que mejor se adapte a tu estilo de viaje",
			cards: [
				{
					name: "Tour Estándar",
					amount: "$1,800",
					amountNote: "MXN / persona",
					items: [
						"Transporte en panga compartida",
						"Acompañamiento de guía certificado",
						"Equipo de snorkel incluido",
						"Fotos y video de tu aventura",
					],
					waText: "Quiero reservar Tiburón Ballena estándar",
				},
				{
					name: "Velero privado",
					amount: "Desde $16,000",
					amountNote: "MXN / hasta 6",
					items: [
						"Velero privado de 40 pies",
						"Capitán y marinero",
						"Costo extra por adulto o menor",
						"Itinerario personalizable",
					],
					waText: "Quiero reservar Tiburón Ballena privado",
					featured: true,
					featuredTag: "Privado",
				},
			],
			note: "¿Buscas algo más exclusivo? También tenemos flota de yates de lujo (40-70 pies) desde $30,000 MXN, con catering y tripulación — consulta con un asesor.",
		},
		finalCta: {
			image: "/manta-ray-swimming.png",
			alt: "Vida marina en La Paz, Baja California Sur",
			title: "¿Listo para nadar con el pez más grande del mundo?",
			text: "El tiburón ballena te espera en las aguas de La Paz. Una experiencia única, responsable e inolvidable.",
			waText: "Quiero reservar Tiburón Ballena",
		},
	},

	"safari-bahia-magdalena": {
		breadcrumb: "Safari Bahía Magdalena",
		hero: {
			image: "/images/marlin-bahia-magdalena-hero.jpeg",
			alt: "Marlin cazando sardinas en Bahía Magdalena",
			kicker: "Bahía Magdalena · Nov-Dic",
			title: "El safari más salvaje del Pacífico",
			text: "Miles de sardinas, marlines cazando a máxima velocidad, ballenas alimentándose. Un fenómeno de solo dos meses al año — y tú puedes presenciarlo desde adentro.",
		},
		quickFacts: [
			{ value: "Día completo", label: "5:00 AM salida" },
			{ value: "2-6 personas", label: "Grupos reducidos" },
			{ value: "Nov - Dic", label: "Corrida de sardinas" },
			{ value: "Mar abierto", label: "Pacífico mexicano" },
		],
		story: {
			kicker: "Qué es la corrida de sardinas",
			title: "Un evento tan breve como poderoso",
			paragraphs: [
				"Cada año, durante noviembre y diciembre, sucede uno de los fenómenos más salvajes de la naturaleza: las aguas de Bahía Magdalena se convierten en el epicentro de la vida marina. Miles de sardinas migran en enormes bancos, atrayendo a depredadores tope como marlines, peces dorados, lobos marinos e incluso ballenas.",
				"No es un tour. Es un must para los amantes del océano. Zarparás hacia el gran azul desde uno de los puntos más vírgenes de la península, en un safari guiado por biólogos marinos, y serás parte de uno de los espectáculos más intensos del Pacífico mexicano. Si las condiciones lo permiten, te sumergirás en el corazón de la acción, flotando sobre un ecosistema en movimiento.",
			],
			commitTitle: "Vida salvaje en libertad",
			commitText: "Trabajamos con fauna en libertad: no garantizamos avistamientos específicos, pero sí compromiso, experiencia y un enfoque respetuoso con el ecosistema que nos acoge.",
		},
		split: {
			image: "/images/gallery/marlin-cazando.jpeg",
			alt: "Marlin rayado cazando un cardumen de sardinas",
			kicker: "Cómo es la experiencia",
			title: "Un día completo en mar abierto",
			text: "Salimos de madrugada desde La Paz hacia el Pacífico. Navegamos en busca de los bancos de sardinas y sus depredadores, con la posibilidad de entrar al agua cuando la acción lo permite. Un día largo, intenso y absolutamente inolvidable.",
		},
		timeline: {
			kicker: "Itinerario del safari",
			title: "Paso a paso",
			items: [
				{ time: "5:00 AM", title: "Salida desde La Paz", text: "Partimos rumbo a la costa del Pacífico, el punto de acceso a Bahía Magdalena." },
				{ time: "7:30 AM", title: "Zarpamos al gran azul", text: "Briefing con tu guía biólogo marino y salida en lancha hacia mar abierto." },
				{ time: "8:00 AM - 2:00 PM", title: "Safari en mar abierto", text: "Navegación en busca de los bancos de sardinas y sus depredadores: marlines, dorados, lobos marinos y ballenas. Snorkel si las condiciones lo permiten." },
				{ time: "2:30 PM", title: "Comida frente al mar", text: "Lunch incluido para recuperar energía después de la acción." },
				{ time: "Tarde", title: "Regreso a La Paz", text: "Volvemos por el desierto de la Baja con la memoria llena y las fotos de tu aventura." },
			],
		},
		fauna: {
			kicker: "Fauna de temporada",
			title: "Los protagonistas del sardine run",
			items: [
				{ image: "/images/especies/sardinas-banco.jpeg", alt: "Banco de sardinas", label: "Sardinas · Nov-Dic" },
				{ image: "/striped-marlin-underwater.jpg", alt: "Marlín rayado", label: "Marlín Rayado · Nov-Dic" },
				{ image: "/images/especies/dorado.jpeg", alt: "Pez dorado", label: "Dorado · Nov-Dic" },
				{ image: "/images/especies/lobomarinonadando.jpeg", alt: "Lobo marino", label: "Lobos Marinos · Todo el año" },
				{ image: "/images/especies/ballenasaltando2.jpeg", alt: "Ballena", label: "Ballenas · Nov-Dic" },
				{ image: "/images/especies/delfinsaltando.jpeg", alt: "Delfín", label: "Delfines · Todo el año" },
			],
		},
		includes: {
			kicker: "Tu experiencia incluye",
			title: "Todo lo que necesitas para el safari más salvaje",
			items: [
				{ title: "Safari de día completo", text: "Navegación en mar abierto guiada por biólogos marinos y capitanes locales." },
				{ title: "Equipo de snorkel", text: "Visor, aletas y neopreno para entrar al agua cuando la acción lo permite." },
				{ title: "Lunch y bebidas", text: "Comida y bebidas incluidas para un día completo de expedición." },
				{ title: "Foto y video incluidos", text: "Capturas profesionales de tu experiencia, listas para revivir el momento." },
			],
		},
		pricing: {
			kicker: "Precio",
			title: "Reserva tu lugar en el sardine run",
			cards: [
				{
					name: "Compartido",
					amount: "$3,500",
					amountNote: "MXN / persona",
					items: [
						"Lancha compartida, 2-6 personas",
						"Transporte desde La Paz",
						"Equipo de snorkel incluido",
						"Lunch y bebidas",
						"Guía biólogo marino y foto/video incluidos",
					],
					waText: "Quiero reservar el Safari Bahía Magdalena",
				},
				{
					name: "Lancha privada",
					amount: "A cotizar",
					amountNote: "para tu grupo",
					items: [
						"Lancha exclusiva para tu grupo",
						"Horario flexible dentro del día",
						"Mismo itinerario y equipo incluido",
						"Guía biólogo marino y foto/video incluidos",
					],
					waText: "Quiero cotizar el Safari Bahía Magdalena privado",
					featured: true,
					featuredTag: "Privado",
				},
			],
			note: "Fenómeno de temporada: solo noviembre y diciembre. Cupo muy limitado por salida — reserva con anticipación.",
		},
		finalCta: {
			image: "/images/marlin-bahia-magdalena-hero.jpeg",
			alt: "Marlin cazando en Bahía Magdalena",
			title: "Solo pasa dos meses al año",
			text: "El safari más salvaje del Pacífico te espera en Bahía Magdalena. Cupos limitados por temporada.",
			waText: "Quiero reservar el Safari Bahía Magdalena",
		},
	},

	"tour-ballena-gris": {
		breadcrumb: "Ballena Gris Puerto Chale",
		hero: {
			image: "/images/hero/ballena-gris-hero.jpeg",
			alt: "Ballena gris en Puerto Chale, Bahía Magdalena",
			kicker: "Puerto Chale · Ene - Mar",
			title: "Un encuentro ancestral",
			text: "Cada invierno, miles de ballenas grises viajan desde el Ártico hasta esta laguna tranquila para dar a luz y aparearse. Tú estás a punto de entrar a ese santuario.",
		},
		quickFacts: [
			{ value: "9 horas", label: "5:00 AM pickup en La Paz" },
			{ value: "Hasta 8 personas", label: "Por lancha" },
			{ value: "Ene - Mar", label: "Temporada oficial" },
			{ value: "2-3 horas", label: "En lancha con ballenas" },
		],
		story: {
			kicker: "Esto no es un tour",
			title: "Es un privilegio",
			paragraphs: [
				"Cada invierno, algo sagrado sucede en el Pacífico mexicano. Miles de ballenas grises viajan más de 20,000 km desde el Ártico hasta una laguna tranquila en medio del desierto... para dar a luz, para aparearse, para estar.",
				"Son conocidas por su curiosidad y su acercamiento amigable a las embarcaciones: madres y crías que se aproximan a un remo de distancia. Un regalo de la naturaleza que solo existe unos meses al año — y lo vas a vivir desde el corazón de la Baja.",
			],
			commitTitle: "Observación responsable",
			commitText: "Navegamos con operadores locales autorizados, respetando distancias, tiempos y el comportamiento de los animales. Ellas deciden acercarse — nosotros solo estamos ahí.",
		},
		split: {
			image: "/gray-whale-close-up-magdalena-bay.jpg",
			alt: "Ballena gris de cerca en Bahía Magdalena",
			kicker: "Cómo es la experiencia",
			title: "El camino hacia la magia",
			text: "La aventura comienza temprano: te recogemos en La Paz y cruzamos el desierto de la Baja mientras amanece, entre cardones gigantes. En Puerto Chale tu lancha ya te espera — el aire huele a mar, a manglar y a historia.",
		},
		timeline: {
			kicker: "Itinerario del día",
			title: "Paso a paso",
			items: [
				{ time: "5:00 AM", title: "Salida al amanecer", text: "Te pasamos a ver a tu hotel o Airbnb en La Paz y partimos rumbo al Pacífico." },
				{ time: "2.5 horas", title: "Camino al Pacífico", text: "Travesía por los paisajes del desierto de la Baja hasta Puerto Chale, donde tu lancha ya te espera." },
				{ time: "2-3 horas", title: "Encuentro con las ballenas", text: "Navegamos dentro de la laguna, hogar temporal de estos gigantes. Aquí se aparean, nacen sus crías y descansan tras la migración más larga del reino animal." },
				{ time: "Mediodía", title: "Comida local", text: "Comida en Puerto Chale, preparada por la comunidad local." },
				{ time: "Tarde", title: "Regreso a La Paz", text: "Volvemos por el desierto con el corazón lleno y las fotos de tu encuentro." },
			],
		},
		fauna: {
			kicker: "Fauna del santuario",
			title: "La laguna está viva",
			items: [
				{ image: "/images/especies/ballena-gris-real.jpeg", alt: "Ballena gris", label: "Ballena Gris · Ene-Mar" },
				{ image: "/gray-whale-mother-and-calf-swimming-together-in-ba.jpg", alt: "Madre y cría de ballena gris", label: "Madres y Crías · Ene-Mar" },
				{ image: "/images/especies/delfinsaltando.jpeg", alt: "Delfín", label: "Delfines · Todo el año" },
				{ image: "/images/especies/lobomarinonadando.jpeg", alt: "Lobo marino", label: "Lobos Marinos · Todo el año" },
				{ image: "/brown-pelicans-flying-over-ocean-in-baja-californi.jpg", alt: "Pelícanos", label: "Aves Marinas · Todo el año" },
				{ image: "/magnificent-frigatebird-soaring-over-ocean-in-baja.jpg", alt: "Fragata", label: "Fragatas · Todo el año" },
			],
		},
		includes: {
			kicker: "Tu experiencia incluye",
			title: "Todo lo necesario para un encuentro inolvidable",
			items: [
				{ title: "Transporte redondo", text: "Pickup en tu hotel o Airbnb en La Paz, ida y vuelta a Puerto Chale." },
				{ title: "Lancha con permiso oficial", text: "Navegación dentro de la laguna con operadores locales autorizados." },
				{ title: "Guía biólogo marino", text: "Interpretación del comportamiento animal durante todo el recorrido." },
				{ title: "Comida local", text: "Comida en Puerto Chale preparada por la comunidad." },
				{ title: "Foto y video incluidos", text: "Capturas profesionales de tu encuentro, listas para revivir el momento." },
			],
		},
		pricing: {
			kicker: "Opciones de tour",
			title: "Reserva tu encuentro con la ballena gris",
			cards: [
				{
					name: "Compartido · 2 horas en lancha",
					amount: "$2,800",
					amountNote: "MXN / persona",
					items: [
						"Transporte redondo desde La Paz",
						"2 horas de navegación con ballenas",
						"Guía biólogo marino",
						"Comida local incluida",
						"Foto y video incluidos",
					],
					waText: "Quiero reservar Ballena Gris Puerto Chale compartido",
				},
				{
					name: "Compartido · 3 horas en lancha",
					amount: "$3,000",
					amountNote: "MXN / persona",
					items: [
						"Transporte redondo desde La Paz",
						"3 horas de navegación con ballenas",
						"Guía biólogo marino",
						"Comida local incluida",
						"Foto y video incluidos",
					],
					waText: "Quiero reservar Ballena Gris Puerto Chale de 3 horas",
					featured: true,
					featuredTag: "Más tiempo",
				},
			],
			note: "¿Van en grupo? Lancha privada premium por $14,000 MXN (hasta 6 personas, 3 horas en el agua). Temporada oficial: enero a marzo únicamente.",
		},
		finalCta: {
			image: "/gray-whale-breaching-sunset-sea-of-cortez.jpg",
			alt: "Ballena gris saltando al atardecer",
			title: "Solo existe unos meses al año",
			text: "Madres y crías de ballena gris te esperan en Puerto Chale. Reserva tu lugar en el santuario.",
			waText: "Quiero reservar Ballena Gris Puerto Chale",
		},
	},

	"tour-espiritu-santo": {
		breadcrumb: "Isla Espíritu Santo",
		hero: {
			image: "/espiritu-santo-island-paradise-beach.jpg",
			alt: "Playa paradisíaca en Isla Espíritu Santo",
			kicker: "Isla Espíritu Santo · Patrimonio UNESCO",
			title: "Nada con lobos marinos curiosos",
			text: "Playas vírgenes, aguas cristalinas y una de las colonias de lobos marinos más grandes del Golfo de California. El acuario del mundo, a una lancha de La Paz.",
		},
		quickFacts: [
			{ value: "6 horas", label: "Muelle fiscal La Paz" },
			{ value: "2-10 personas", label: "Grupos reducidos" },
			{ value: "Todo el año", label: "Temporada" },
			{ value: "UNESCO", label: "Reserva de la Biosfera" },
		],
		story: {
			kicker: "Una joya del Golfo de California",
			title: "El acuario del mundo",
			paragraphs: [
				"La Isla Espíritu Santo es hogar de una de las colonias de lobos marinos más grandes del Golfo de California. Aquí vivirás un encuentro responsable y guiado con estos animales en aguas cristalinas, dentro de un entorno natural único.",
				"Nuestros guías especializados te acompañan durante toda la experiencia, compartiendo conocimientos sobre historia natural, conservación marina y buenas prácticas para interactuar con la fauna de forma respetuosa.",
			],
			commitTitle: "Temporada de cría",
			commitText: "Del 1 de junio al 31 de agosto no se permite nadar con los lobos marinos por la temporada de cría; la experiencia se realiza mediante observación desde la embarcación, por la seguridad de los lobeznos.",
		},
		split: {
			image: "/picnic-beach-espiritu-santo.jpg",
			alt: "Picnic en playa de Isla Espíritu Santo",
			kicker: "Cómo es la experiencia",
			title: "Snorkel, playas vírgenes y picnic",
			text: "Después del nado en Los Islotes navegamos a una de las playas del archipiélago: arena clara, agua turquesa y formaciones rocosas impresionantes. Tiempo libre para nadar, caminar o simplemente estar — con picnic incluido frente al mar.",
		},
		timeline: {
			kicker: "Itinerario del día",
			title: "Paso a paso",
			items: [
				{ time: "Mañana", title: "Salida desde La Paz", text: "Nos encontramos en el Muelle fiscal, zarpamos con el sol de la mañana y navegamos hacia el norte por el Golfo de California." },
				{ time: "Los Islotes", title: "Nado con lobos marinos", text: "Encuentro respetuoso y guiado con una de las colonias más grandes del Golfo. Equipo incluido y acompañamiento en el agua en todo momento." },
				{ time: "Mediodía", title: "Playa del archipiélago", text: "Parada en una playa virgen del archipiélago: arena clara, agua turquesa y tiempo libre para explorar." },
				{ time: "Comida", title: "Picnic frente al mar", text: "Picnic incluido en la playa, rodeado del paisaje de la reserva." },
				{ time: "Tarde", title: "Regreso escénico", text: "Navegamos de vuelta a La Paz con posibilidad de avistamientos en el camino." },
			],
		},
		fauna: {
			kicker: "Fauna de la reserva",
			title: "Vida por todos lados",
			items: [
				{ image: "/swimming-with-sea-lions.jpg", alt: "Nado con lobos marinos", label: "Lobos Marinos · Todo el año" },
				{ image: "/sea-lions-resting-on-rocks-in-baja-california-sur.jpg", alt: "Lobos marinos en rocas", label: "Lobera de Los Islotes" },
				{ image: "/pristine-beach-turquoise-water-espiritu-santo-isla.jpg", alt: "Playa virgen", label: "Playas Vírgenes" },
				{ image: "/snorkeling-crystal-clear-water.jpg", alt: "Snorkel", label: "Arrecifes y Peces" },
				{ image: "/brown-pelicans-flying-over-ocean-in-baja-californi.jpg", alt: "Pelícanos", label: "Aves Marinas" },
				{ image: "/images/especies/delfinsaltando.jpeg", alt: "Delfines", label: "Delfines · Todo el año" },
			],
		},
		includes: {
			kicker: "Tu experiencia incluye",
			title: "Todo para un día completo en el paraíso",
			items: [
				{ title: "Navegación por la reserva", text: "Salida y regreso desde el Muelle fiscal de La Paz." },
				{ title: "Nado con lobos marinos", text: "Encuentro guiado en Los Islotes con equipo de snorkel incluido." },
				{ title: "Picnic en la playa", text: "Comida y bebidas frente al mar en una playa del archipiélago." },
				{ title: "Foto y video incluidos", text: "Capturas profesionales de tu experiencia, listas para revivir el momento." },
			],
		},
		pricing: {
			kicker: "Precio",
			title: "Reserva tu día en Isla Espíritu Santo",
			cards: [
				{
					name: "Compartido",
					amount: "$1,800",
					amountNote: "MXN / persona",
					items: [
						"Lancha compartida, 2-10 personas",
						"Nado con lobos marinos en Los Islotes",
						"Equipo de snorkel incluido",
						"Picnic en playa",
						"Guía y foto/video incluidos",
					],
					waText: "Quiero reservar Isla Espíritu Santo",
				},
				{
					name: "Lancha privada",
					amount: "A cotizar",
					amountNote: "para tu grupo",
					items: [
						"Lancha exclusiva para tu grupo",
						"Horario flexible dentro del día",
						"Mismo itinerario y equipo incluido",
						"Guía y foto/video incluidos",
					],
					waText: "Quiero cotizar Isla Espíritu Santo privado",
					featured: true,
					featuredTag: "Privado",
				},
			],
			note: "Del 1 de junio al 31 de agosto el nado con lobos marinos se sustituye por observación desde la embarcación (temporada de cría).",
		},
		finalCta: {
			image: "/espiritu-santo-island-paradise-beach.jpg",
			alt: "Isla Espíritu Santo",
			title: "El paraíso está a una lancha de La Paz",
			text: "Lobos marinos juguetones, playas vírgenes y el azul del acuario del mundo. Reserva tu lugar.",
			waText: "Quiero reservar Isla Espíritu Santo",
		},
	},

	"buceo-cabo-pulmo": {
		breadcrumb: "Scuba Diving Cabo Pulmo",
		hero: {
			image: "/coral-reef-underwater-diving-cabo-pulmo-colorful-f.jpg",
			alt: "Arrecife de coral en Cabo Pulmo",
			kicker: "Cabo Pulmo · Parque Nacional",
			title: "El único arrecife vivo del Golfo",
			text: "25,000 años de coral, tiburones toro, cardúmenes masivos. Bucea en una de las reservas marinas más exitosas del mundo.",
		},
		quickFacts: [
			{ value: "Día completo", label: "Salida desde La Paz" },
			{ value: "2-6 personas", label: "Grupos reducidos" },
			{ value: "Todo el año", label: "Temporada" },
			{ value: "2 inmersiones", label: "Parque Nacional" },
		],
		story: {
			kicker: "Parque Nacional Cabo Pulmo",
			title: "La reserva que volvió a la vida",
			paragraphs: [
				"Cabo Pulmo es el único arrecife de coral vivo del Golfo de California, con más de 25,000 años de antigüedad. Tras décadas de protección comunitaria, su biomasa se recuperó como en ningún otro lugar del planeta: hoy es una de las historias de conservación más exitosas del mundo.",
				"Bucear aquí es entrar a una nube de peces: cardúmenes masivos de jureles, tiburones toro, meros gigantes, tortugas y — con suerte — el famoso tornado de jacks. Cada inmersión está guiada por instructores certificados que conocen el parque de memoria.",
			],
			commitTitle: "Parque Nacional protegido",
			commitText: "Cabo Pulmo es un área natural protegida: grupos reducidos, prácticas de bajo impacto y respeto absoluto por el arrecife en cada inmersión.",
		},
		split: {
			image: "/buceo-cabo-pulmo-cardumen.jpg",
			alt: "Cardumen masivo en Cabo Pulmo",
			kicker: "Cómo es la experiencia",
			title: "Dos inmersiones en el arrecife",
			text: "Salimos temprano de La Paz hacia el Parque Nacional. Realizamos dos inmersiones guiadas en los mejores sitios del arrecife según las condiciones del día, con intervalo en superficie, snacks y toda la logística resuelta.",
		},
		timeline: {
			kicker: "Itinerario del día",
			title: "Paso a paso",
			items: [
				{ time: "Temprano", title: "Salida desde La Paz", text: "Traslado por carretera hacia Cabo Pulmo, en la costa este del Golfo." },
				{ time: "Llegada", title: "Briefing y equipo", text: "Preparación del equipo, briefing de los sitios y reglas del Parque Nacional." },
				{ time: "Inmersión 1", title: "Primer buceo en el arrecife", text: "Inmersión guiada en uno de los sitios icónicos del parque." },
				{ time: "Superficie", title: "Intervalo y snacks", text: "Descanso en superficie con agua, fruta y galletas a bordo." },
				{ time: "Inmersión 2", title: "Segundo buceo", text: "Segunda inmersión en otro punto del arrecife según las condiciones." },
				{ time: "Tarde", title: "Regreso a La Paz", text: "Volvemos con las fotos y videos de tu día en el parque." },
			],
		},
		fauna: {
			kicker: "Vida del arrecife",
			title: "Lo que puedes encontrar en el parque",
			items: [
				{ image: "/coral-reef-underwater-cabo-pulmo-colorful-tropical.jpg", alt: "Arrecife de coral", label: "Coral · 25,000 años" },
				{ image: "/buceo-cabo-pulmo-cardumen.jpg", alt: "Cardumen", label: "Cardúmenes Masivos" },
				{ image: "/buceo-cabo-pulmo-buzo.jpg", alt: "Buzo en Cabo Pulmo", label: "Tiburones Toro y Meros" },
			],
		},
		includes: {
			kicker: "Tu experiencia incluye",
			title: "Todo lo necesario para bucear el parque",
			items: [
				{ title: "2 inmersiones guiadas", text: "En los mejores sitios del arrecife según las condiciones del día." },
				{ title: "Guía certificado", text: "Instructores con experiencia en el Parque Nacional." },
				{ title: "Agua y snacks", text: "Hidratación, fruta y galletas a bordo durante la salida." },
				{ title: "Foto y video incluidos", text: "Capturas profesionales de tu experiencia bajo el agua." },
			],
		},
		pricing: {
			kicker: "Opciones de buceo",
			title: "Elige tu experiencia en Cabo Pulmo",
			cards: [
				{
					name: "Buzos certificados",
					amount: "$3,200",
					amountNote: "MXN / persona con tu equipo",
					items: [
						"2 inmersiones compartidas",
						"$3,400 MXN con equipo completo incluido",
						"Grupos de hasta 6 personas",
						"Agua y galletas a bordo",
						"Guía certificado y foto/video",
					],
					waText: "Quiero reservar Buceo en Cabo Pulmo certificado",
				},
				{
					name: "Discovery Scuba Diver",
					amount: "$3,800",
					amountNote: "MXN / persona",
					items: [
						"Para principiantes sin experiencia",
						"Instrucción teórica completa",
						"Práctica en aguas poco profundas",
						"2 inmersiones supervisadas por instructor",
					],
					waText: "Quiero reservar Discovery en Cabo Pulmo",
					featured: true,
					featuredTag: "Sin certificación",
				},
			],
			note: "¿Grupo privado? Buceo privado desde $12,000 MXN (1-3 buzos, precio fijo) + costo por buzo adicional. Escríbenos para armar tu salida.",
		},
		finalCta: {
			image: "/coral-reef-underwater-diving-cabo-pulmo-colorful-f.jpg",
			alt: "Arrecife de Cabo Pulmo",
			title: "Bucea el arrecife que volvió a la vida",
			text: "25,000 años de coral te esperan en el Parque Nacional Cabo Pulmo. Cupo limitado por salida.",
			waText: "Quiero reservar Buceo en Cabo Pulmo",
		},
	},

	"buceo-la-paz": {
		breadcrumb: "Scuba Diving Isla Espíritu Santo",
		hero: {
			image: "/scuba-diving-underwater-sea-lions-swimming-playful.jpg",
			alt: "Buceo con lobos marinos en Los Islotes",
			kicker: "Archipiélago Espíritu Santo · Patrimonio UNESCO",
			title: "Bucea con lobos marinos curiosos",
			text: "Los Islotes es hogar de más de 400 lobos marinos que juegan, giran y te rodean bajo el agua. La combinación de buceo y fauna más juguetona de La Paz.",
		},
		quickFacts: [
			{ value: "7-8 horas", label: "Muelle fiscal La Paz" },
			{ value: "2-6 personas", label: "Grupos reducidos" },
			{ value: "Todo el año", label: "Temporada" },
			{ value: "2-3 inmersiones", label: "Los Islotes y más" },
		],
		story: {
			kicker: "Los perritos del mar",
			title: "Ellos también quieren jugar",
			paragraphs: [
				"Los Islotes, en el extremo norte del archipiélago Espíritu Santo, alberga una colonia de más de 400 lobos marinos extremadamente curiosos y juguetones con los buceadores. Te rodean, hacen piruetas y crean recuerdos que no se olvidan.",
				"Además de la lobera, visitamos otros sitios del archipiélago con formaciones rocosas impresionantes, cuevas submarinas y una diversidad de vida marina que le valió el título del acuario del mundo.",
			],
			commitTitle: "Encuentro responsable",
			commitText: "Buceamos con prácticas de bajo impacto y respeto por la colonia: ellos deciden acercarse — y casi siempre lo hacen.",
		},
		split: {
			image: "/scuba-diving-underwater-la-paz-sea-lions-swimming.jpg",
			alt: "Lobos marinos nadando con buzos",
			kicker: "Cómo es la experiencia",
			title: "Un día completo de buceo en la reserva",
			text: "Zarpamos del Muelle fiscal de La Paz hacia el archipiélago. Dos a tres inmersiones guiadas según las condiciones, con lunch y bebidas incluidas — y lobos marinos de compañía.",
		},
		timeline: {
			kicker: "Itinerario del día",
			title: "Paso a paso",
			items: [
				{ time: "Mañana", title: "Salida desde La Paz", text: "Nos encontramos en el Muelle fiscal y navegamos hacia el archipiélago Espíritu Santo." },
				{ time: "Los Islotes", title: "Inmersión con lobos marinos", text: "Buceo guiado en la lobera más famosa del Golfo de California." },
				{ time: "Superficie", title: "Intervalo y lunch", text: "Descanso, lunch y bebidas a bordo frente a los paisajes de la reserva." },
				{ time: "Inmersión 2", title: "Cuevas y formaciones", text: "Segunda inmersión en sitios con formaciones rocosas y vida marina diversa." },
				{ time: "Tarde", title: "Regreso a La Paz", text: "Volvemos al muelle con las fotos y videos de tu día." },
			],
		},
		fauna: {
			kicker: "Vida del archipiélago",
			title: "Lo que te espera bajo el agua",
			items: [
				{ image: "/sea-lions-swimming-underwater.jpg", alt: "Lobos marinos bajo el agua", label: "Lobos Marinos · Todo el año" },
				{ image: "/scuba-diving-underwater-la-paz-sea-lions-swimming.jpg", alt: "Buceo con lobos marinos", label: "Los Islotes" },
				{ image: "/buceo-la-paz-buzo.jpg", alt: "Buzo en La Paz", label: "Cuevas y Formaciones" },
			],
		},
		includes: {
			kicker: "Tu experiencia incluye",
			title: "Todo para bucear el acuario del mundo",
			items: [
				{ title: "Transporte en panga", text: "Salida y regreso desde el Muelle fiscal de La Paz." },
				{ title: "2-3 inmersiones", text: "Guiadas por dive master certificado en los mejores sitios del archipiélago." },
				{ title: "Equipo completo", text: "Equipo de buceo completo incluido en la opción con equipo." },
				{ title: "Lunch y bebidas", text: "Comida y bebidas a bordo durante la salida." },
				{ title: "Foto y video incluidos", text: "Capturas submarinas de tu experiencia." },
			],
		},
		pricing: {
			kicker: "Opciones de buceo",
			title: "Elige tu experiencia en Espíritu Santo",
			cards: [
				{
					name: "Buzos certificados",
					amount: "$3,700",
					amountNote: "MXN / persona",
					items: [
						"2-3 inmersiones en el archipiélago",
						"Dive master certificado",
						"Lunch y bebidas incluidas",
						"Foto y video incluidos",
					],
					waText: "Quiero reservar Buceo en Isla Espíritu Santo certificado",
				},
				{
					name: "Discovery Scuba Diver",
					amount: "$4,200",
					amountNote: "MXN / persona",
					items: [
						"Para principiantes sin experiencia",
						"Instrucción teórica completa",
						"Práctica en aguas poco profundas",
						"Inmersiones supervisadas por instructor",
					],
					waText: "Quiero reservar Discovery en Isla Espíritu Santo",
					featured: true,
					featuredTag: "Sin certificación",
				},
			],
			note: "También disponible para snorkelers: no se requiere certificación para el snorkel con lobos marinos.",
		},
		finalCta: {
			image: "/scuba-diving-underwater-sea-lions-swimming-playful.jpg",
			alt: "Lobos marinos juguetones",
			title: "Nada con los perritos del mar",
			text: "Una experiencia que nunca olvidarás, en un Patrimonio UNESCO. Reserva hoy tu inmersión.",
			waText: "Quiero reservar Buceo en Isla Espíritu Santo",
		},
	},

	"scuba-discovery": {
		breadcrumb: "Scuba Discovery desde Playa",
		hero: {
			image: "/snorkeling-coral-reef.jpg",
			alt: "Scuba Discovery desde playa en La Paz",
			kicker: "La Paz · Desde playa",
			title: "Tu primera respiración bajo el agua",
			text: "Sin certificación, sin experiencia previa, sin lancha: entras caminando desde la playa con un instructor a tu lado en todo momento. Máximo 6 metros de profundidad.",
		},
		quickFacts: [
			{ value: "Medio día", label: "Playa en La Paz" },
			{ value: "1-6 personas", label: "Por instructor" },
			{ value: "Todo el año", label: "Temporada" },
			{ value: "Máx. 6 m", label: "Profundidad" },
		],
		story: {
			kicker: "Para principiantes",
			title: "El buceo, sin barreras",
			paragraphs: [
				"El Scuba Discovery es la forma más accesible de probar el buceo: entras al agua caminando desde la playa, practicas los ejercicios básicos en aguas poco profundas y exploras el fondo marino a un máximo de 6 metros de profundidad.",
				"No necesitas certificación ni experiencia previa — solo ganas de descubrir el Mar de Cortés desde abajo. Un instructor certificado te acompaña en todo momento, desde la teoría hasta la última burbuja.",
			],
			commitTitle: "Tu primer paso",
			commitText: "Si te enamoras del buceo, esta experiencia es el primer paso hacia tu certificación Open Water. Apto para principiantes desde los 10 años.",
		},
		split: {
			image: "/snorkeling-crystal-clear-water.jpg",
			alt: "Aguas cristalinas en La Paz",
			kicker: "Cómo es la experiencia",
			title: "Del briefing a las burbujas",
			text: "Empezamos en la playa con una introducción teórica sencilla, practicamos las habilidades básicas donde tocas el fondo, y cuando estás listo exploramos el arrecife costero acompañados en todo momento. Fotos incluidas.",
		},
		timeline: {
			kicker: "Itinerario",
			title: "Paso a paso",
			items: [
				{ time: "Bienvenida", title: "Briefing en la playa", text: "Introducción teórica sencilla: el equipo, la respiración y las señales básicas." },
				{ time: "Aguas someras", title: "Práctica de habilidades", text: "Ejercicios básicos en agua donde tocas el fondo, a tu ritmo y sin presión." },
				{ time: "Inmersión", title: "Exploración guiada", text: "Buceo guiado a máximo 6 metros de profundidad por el arrecife costero." },
				{ time: "Cierre", title: "Fotos y siguiente paso", text: "Recibes las fotos de tu experiencia y, si quieres más, te contamos cómo certificarte." },
			],
		},
		includes: {
			kicker: "Tu experiencia incluye",
			title: "Todo para tu primera vez bajo el agua",
			items: [
				{ title: "Instructor certificado", text: "Acompañamiento uno a uno durante toda la experiencia." },
				{ title: "Equipo completo", text: "Todo el equipo de buceo incluido, ajustado a tu medida." },
				{ title: "Práctica en aguas someras", text: "Briefing y ejercicios donde tocas el fondo, sin prisa." },
				{ title: "Fotos incluidas", text: "Capturas de tu primera respiración bajo el agua." },
			],
		},
		pricing: {
			kicker: "Precio",
			title: "Reserva tu Scuba Discovery",
			cards: [
				{
					name: "Por persona",
					amount: "$1,500",
					amountNote: "MXN / persona",
					items: [
						"Sin experiencia previa necesaria",
						"Instructor certificado todo el tiempo",
						"Equipo completo incluido",
						"Máximo 6 metros de profundidad",
						"Fotos incluidas",
					],
					waText: "Quiero reservar Scuba Discovery desde Playa",
				},
				{
					name: "Grupo privado",
					amount: "A cotizar",
					amountNote: "hasta 6 personas",
					items: [
						"Instructor exclusivo para tu grupo",
						"Horario flexible",
						"Mismo equipo e itinerario",
						"Ideal para familias y amigos",
					],
					waText: "Quiero cotizar Scuba Discovery privado",
					featured: true,
					featuredTag: "Nuevo",
				},
			],
			note: "Apto para principiantes desde los 10 años. Si continúas hacia tu certificación, esta experiencia cuenta como tu primer contacto con el buceo.",
		},
		finalCta: {
			image: "/snorkeling-crystal-clear-water.jpg",
			alt: "Aguas cristalinas del Mar de Cortés",
			title: "Respira bajo el agua por primera vez",
			text: "Sin certificación, sin experiencia, sin pretextos. El Mar de Cortés te espera a 6 metros.",
			waText: "Quiero reservar Scuba Discovery desde Playa",
		},
	},
}
