import type { ExpeditionPageData } from "@/components/ExpeditionDetail"

/** English content for the expedition detail pages. */
export const expeditionPagesEn: Record<string, ExpeditionPageData> = {
	"safari-la-ventana": {
		breadcrumb: "La Ventana Safari",
		hero: {
			image: "/images/orca-safari.jpg",
			alt: "Seafari in La Ventana, Baja California Sur",
			kicker: "La Ventana · Cerralvo Island",
			title: "Find the extraordinary",
			text: "Explore one of the most surprising marine settings in the Gulf of California. Every trip is different. Every encounter is real.",
		},
		quickFacts: [
			{ value: "6 hours", label: "8:00 AM departure" },
			{ value: "2-8 people", label: "Shared or private" },
			{ value: "Apr - Jun", label: "Mobula season" },
			{ value: "40 min", label: "From La Paz" },
		],
		story: {
			kicker: "What the Seafari is",
			title: "No script. No show.",
			paragraphs: [
				"The Seafari starts in La Ventana, 40 minutes from La Paz, where we head out into the deep blue. Aboard the boat, guided by marine biologists and local captains, we sail in search of the unexpected: mobulas that fly, dolphins that escort us, whales that surface like living legends.",
				"Unlike a conventional tour where everything is set in advance, the Seafari is designed as a dynamic, authentic experience focused on maximizing wildlife encounters. Every trip is unique — because we work with wildlife in freedom: we don't guarantee specific sightings, but we do guarantee commitment, experience and a respectful approach.",
			],
			commitTitle: "Our commitment",
			commitText: "We deeply respect marine life. Our safaris are designed to observe without disturbing, learn without interfering, and marvel without harming the ecosystem that hosts us.",
		},
		split: {
			image: "/images/safari/nuestrocompromiso2.jpeg",
			alt: "Guide with snorkeling gear on the La Ventana Seafari",
			kicker: "How the experience works",
			title: "A full day designed for the encounter",
			text: "Sailing in search of marine life, snorkeling when conditions allow and exploring Cerralvo Island — all guided by marine biologists who read animal behavior and the sea's signals in real time. We close the day with fresh ceviche and seasonal fruit by the water.",
		},
		timeline: {
			kicker: "Detailed itinerary",
			title: "Hour by hour",
			items: [
				{ time: "8:00 AM", title: "Welcome and briefing", text: "Meet your marine biologist guide and get an introduction to the marine life you might encounter." },
				{ time: "8:30 - 11:30 AM", title: "Sailing and searching", text: "We sail in search of marine life, following behavior patterns and natural signals." },
				{ time: "11:30 AM - 1:00 PM", title: "Exploring Cerralvo Island", text: "Depending on conditions, snorkeling or exploring the crystal-clear waters around the island." },
				{ time: "1:00 - 1:30 PM", title: "Snack and rest", text: "Fresh ceviche and seasonal fruit while we rest." },
				{ time: "1:30 - 2:00 PM", title: "Scenic return", text: "We sail back to La Ventana, with the chance of more sightings along the way." },
			],
		},
		fauna: {
			kicker: "Wildlife by season",
			title: "The Gulf of California is one of the most biodiverse seas on the planet",
			items: [
				{ image: "/images/especies/mobulaschafa.jpeg", alt: "Mobulas", label: "Mobulas · Apr-Jun" },
				{ image: "/images/especies/delfinsaltando.jpeg", alt: "Jumping dolphin", label: "Dolphins · Year-round" },
				{ image: "/images/especies/ballenasaltando2.jpeg", alt: "Humpback whale", label: "Humpback Whale · Dec-Apr" },
				{ image: "/images/especies/lobomarinonadando.jpeg", alt: "Sea lion", label: "Sea Lions · Year-round" },
				{ image: "/images/especies/cachalote2.jpeg", alt: "Sperm whale", label: "Sperm Whales · Jun-Nov" },
				{ image: "/images/especies/orcalaventana.jpeg", alt: "Orca", label: "Orcas · Unpredictable" },
			],
		},
		includes: {
			kicker: "Your experience includes",
			title: "Everything you need to enjoy the Seafari",
			items: [
				{ title: "6-hour marine safari", text: "Sailing in search of marine life with marine biologists and local captains who know the area." },
				{ title: "Full equipment", text: "Wetsuit, snorkel and beach gear included for the whole trip." },
				{ title: "Picnic on Cerralvo Island", text: "Fresh ceviche, seasonal fruit, snacks and drinks by the sea." },
				{ title: "Photo and video included", text: "Professional captures of your experience, ready to relive the moment." },
			],
		},
		pricing: {
			kicker: "Price",
			title: "Book your Seafari in La Ventana",
			cards: [
				{
					name: "Shared",
					amountMxn: 3000,
					amountNote: "/ person",
					items: [
						"Minimum 4 people",
						"Shared boat, up to 8-10 pax",
						"Wetsuit, snorkel and beach gear",
						"Picnic on Cerralvo Island",
						"Marine biologist guide, photo/video included",
					],
					waText: "I want to book the shared La Ventana Safari",
				},
				{
					name: "Private boat",
					amountMxn: 16000,
					amountNote: "/ up to 8 pax",
					items: [
						"Boat exclusively for your group",
						"Flexible schedule within the day",
						"Same itinerary and gear included",
						"Marine biologist guide, photo/video included",
					],
					waText: "I want to book the private La Ventana Safari",
					featured: true,
					featuredTag: "Private",
				},
			],
			note: "Recommended for confident swimmers; children travel under adult supervision. Limited spots during mobula season (April-June).",
		},
		finalCta: {
			image: "/images/orca-safari.jpg",
			alt: "Mobulas jumping in La Ventana",
			title: "Mobulas that fly, whales that surface",
			text: "Live a safari with no script, 40 minutes from La Paz. Limited spots per departure.",
			waText: "I want to book the La Ventana Safari",
		},
	},

	"tiburon-ballena": {
		breadcrumb: "Whale Shark",
		hero: {
			image: "/snorkeling-coral-reef.jpg",
			alt: "Swimming with whale sharks in La Paz",
			kicker: "La Paz · Nov - Mar",
			title: "Swim with the biggest fish in the world",
			text: "Swimming with whale sharks is one of the most iconic marine experiences in La Paz, Baja California Sur. Calm waters, responsible and regulated encounters.",
		},
		quickFacts: [
			{ value: "2 hours", label: "La Paz main pier" },
			{ value: "Nov - Mar", label: "Official season" },
			{ value: "Regulated", label: "Official zone and permits" },
			{ value: "All ages", label: "Accessible activity" },
		],
		story: {
			kicker: "Swim with the biggest fish in the world",
			title: "A gentle giant, in its season",
			paragraphs: [
				"Every season, these giants of the sea arrive in the calm waters of the bay, creating a unique opportunity to observe them and swim alongside them responsibly, always under official guidelines and with authorized operators.",
				"Our specialized guides accompany you throughout the experience, sharing knowledge about the species, its ecological importance and best practices to enjoy this encounter with respect and awareness.",
			],
			commitTitle: "A regulated activity",
			commitText: "In La Paz, access to the swimming and observation zone is regulated. Only boats with a current permit may enter, respecting the turns and times authorized to protect the species.",
		},
		split: {
			image: "/manta-ray-swimming.png",
			alt: "Marine life in the Gulf of California",
			kicker: "What else you can see",
			title: "The Gulf of California never rests",
			text: "On the way to the observation zone it's common to come across curious sea lions and dolphins approaching the boat — the Sea of Cortez, \"the aquarium of the world\" according to Jacques Cousteau, always has something to show.",
		},
		timeline: {
			kicker: "Day itinerary",
			title: "Step by step",
			items: [
				{ time: "Main pier", title: "Welcome and briefing", text: "We meet at La Paz's main pier. Introduction to the experience, gear use and the rules for a responsible activity." },
				{ time: "Sailing", title: "Search and locate", text: "We sail within the permitted area following the protocols set by the authorities, respecting authorized turns and times." },
				{ time: "In the water", title: "Swim with the whale shark", text: "A guided, responsible encounter with the biggest fish in the world, always accompanied by your certified guide." },
				{ time: "Return", title: "Back to La Paz", text: "We return to the pier with the photos and videos of your encounter." },
			],
		},
		includes: {
			kicker: "Your experience includes",
			title: "Everything for a safe and responsible encounter",
			items: [
				{ title: "Boat transport", text: "Departure and return from La Paz's main pier." },
				{ title: "Certified guide", text: "A specialized bilingual team that shares knowledge about the species." },
				{ title: "Snorkeling gear", text: "Mask, fins and life vest to explore with peace of mind." },
				{ title: "Photos and videos", text: "Authentic memories of your adventure, captured in the moment." },
				{ title: "Regulated permit", text: "Authorized access to the official observation zone." },
			],
		},
		pricing: {
			kicker: "Price",
			title: "Book your whale shark swim",
			cards: [
				{
					name: "Shared tour",
					amountMxn: 1800,
					amountNote: "/ person",
					items: [
						"Shared panga transport",
						"Certified guide by your side",
						"Snorkeling gear included",
						"Photos and video of your adventure",
						"Permit for the regulated zone",
					],
					waText: "I want to book the Whale Shark tour",
				},
			],
			note: "Official season: November to March, with peak season from December to February. Accessible for all ages — minors participate under adult supervision.",
		},
		finalCta: {
			image: "/manta-ray-swimming.png",
			alt: "Marine life in La Paz, Baja California Sur",
			title: "Ready to swim with the biggest fish in the world?",
			text: "The whale shark awaits in the waters of La Paz. A unique, responsible and unforgettable experience.",
			waText: "I want to book the Whale Shark tour",
		},
	},

	"safari-bahia-magdalena": {
		breadcrumb: "Magdalena Bay Safari",
		hero: {
			image: "/images/marlin-bahia-magdalena-hero.jpeg",
			alt: "Marlin hunting sardines in Magdalena Bay",
			kicker: "Magdalena Bay · Nov-Dec",
			title: "The wildest safari in the Pacific",
			text: "Thousands of sardines, marlin hunting at full speed, whales feeding. A phenomenon that lasts only two months a year — and you can witness it from the inside.",
		},
		quickFacts: [
			{ value: "Full day", label: "5:00 AM departure" },
			{ value: "2-6 people", label: "Small groups" },
			{ value: "Nov - Dec", label: "Sardine run" },
			{ value: "Open water", label: "Mexican Pacific" },
		],
		story: {
			kicker: "What the sardine run is",
			title: "An event as brief as it is powerful",
			paragraphs: [
				"Every year, during November and December, one of nature's wildest phenomena takes place: the waters of Magdalena Bay become the epicenter of marine life. Thousands of sardines migrate in enormous bait balls, attracting top predators like marlin, mahi-mahi, sea lions and even whales.",
				"This is not a tour. It's a must for ocean lovers. You'll set sail into the big blue from one of the most pristine spots on the peninsula, on a safari guided by marine biologists, and become part of one of the most intense spectacles of the Mexican Pacific. If conditions allow, you'll slip into the heart of the action, floating above an ecosystem in motion.",
			],
			commitTitle: "Wildlife in freedom",
			commitText: "We work with animals in the wild: we don't guarantee specific sightings, but we do guarantee commitment, experience and a respectful approach to the ecosystem that hosts us.",
		},
		split: {
			image: "/images/gallery/marlin-cazando.jpeg",
			alt: "Striped marlin hunting a bait ball of sardines",
			kicker: "How the experience works",
			title: "A full day in open water",
			text: "We leave La Paz at dawn heading for the Pacific. We sail in search of the sardine bait balls and their predators, with the chance to get in the water when the action allows. A long, intense, absolutely unforgettable day.",
		},
		timeline: {
			kicker: "Safari itinerary",
			title: "Step by step",
			items: [
				{ time: "5:00 AM", title: "Departure from La Paz", text: "We head for the Pacific coast, the gateway to Magdalena Bay." },
				{ time: "7:30 AM", title: "Into the big blue", text: "Briefing with your marine biologist guide and departure by boat into open water." },
				{ time: "8:00 AM - 2:00 PM", title: "Open-water safari", text: "Sailing in search of the sardine bait balls and their predators: marlin, mahi-mahi, sea lions and whales. Snorkeling if conditions allow." },
				{ time: "2:30 PM", title: "Lunch by the sea", text: "Lunch included to recharge after the action." },
				{ time: "Afternoon", title: "Return to La Paz", text: "We drive back through the Baja desert with a full memory card and the photos of your adventure." },
			],
		},
		fauna: {
			kicker: "Seasonal wildlife",
			title: "The stars of the sardine run",
			items: [
				{ image: "/images/especies/sardinas-banco.jpeg", alt: "Sardine bait ball", label: "Sardines · Nov-Dec" },
				{ image: "/striped-marlin-underwater.jpg", alt: "Striped marlin", label: "Striped Marlin · Nov-Dec" },
				{ image: "/images/especies/dorado.jpeg", alt: "Mahi-mahi", label: "Mahi-mahi · Nov-Dec" },
				{ image: "/images/especies/lobomarinonadando.jpeg", alt: "Sea lion", label: "Sea Lions · Year-round" },
				{ image: "/images/especies/ballenasaltando2.jpeg", alt: "Whale", label: "Whales · Nov-Dec" },
				{ image: "/images/especies/delfinsaltando.jpeg", alt: "Dolphin", label: "Dolphins · Year-round" },
			],
		},
		includes: {
			kicker: "Your experience includes",
			title: "Everything you need for the wildest safari",
			items: [
				{ title: "Full-day safari", text: "Open-water sailing guided by marine biologists and local captains." },
				{ title: "Snorkeling gear", text: "Mask, fins and wetsuit to get in the water when the action allows." },
				{ title: "Lunch and drinks", text: "Food and drinks included for a full day of expedition." },
				{ title: "Photo and video included", text: "Professional captures of your experience, ready to relive the moment." },
			],
		},
		pricing: {
			kicker: "Price",
			title: "Book your spot at the sardine run",
			cards: [
				{
					name: "Shared",
					amountMxn: 3500,
					amountNote: "/ person",
					items: [
						"Shared boat, 2-6 people",
						"Transport from La Paz",
						"Snorkeling gear included",
						"Lunch and drinks",
						"Marine biologist guide, photo/video included",
					],
					waText: "I want to book the Magdalena Bay Safari",
				},
				{
					name: "Private boat",
					amountText: "Quote",
					amountNote: "for your group",
					items: [
						"Boat exclusively for your group",
						"Flexible schedule within the day",
						"Same itinerary and gear included",
						"Marine biologist guide, photo/video included",
					],
					waText: "I want a quote for the private Magdalena Bay Safari",
					featured: true,
					featuredTag: "Private",
				},
			],
			note: "A seasonal phenomenon: November and December only. Very limited spots per departure — book early.",
		},
		finalCta: {
			image: "/images/marlin-bahia-magdalena-hero.jpeg",
			alt: "Marlin hunting in Magdalena Bay",
			title: "It only happens two months a year",
			text: "The wildest safari in the Pacific awaits in Magdalena Bay. Limited spots per season.",
			waText: "I want to book the Magdalena Bay Safari",
		},
	},

	"tour-ballena-gris": {
		breadcrumb: "Gray Whale Puerto Chale",
		hero: {
			image: "/images/hero/ballena-gris-hero.jpeg",
			alt: "Gray whale in Puerto Chale, Magdalena Bay",
			kicker: "Puerto Chale · Jan - Mar",
			title: "An ancestral encounter",
			text: "Every winter, thousands of gray whales travel from the Arctic to this quiet lagoon to give birth and mate. You are about to enter that sanctuary.",
		},
		quickFacts: [
			{ value: "9 hours", label: "5:00 AM pickup in La Paz" },
			{ value: "Up to 8 people", label: "Per boat" },
			{ value: "Jan - Mar", label: "Official season" },
			{ value: "2-3 hours", label: "On the water with whales" },
		],
		story: {
			kicker: "This is not a tour",
			title: "It's a privilege",
			paragraphs: [
				"Every winter, something sacred happens in the Mexican Pacific. Thousands of gray whales travel more than 20,000 km from the Arctic to a quiet lagoon in the middle of the desert... to give birth, to mate, to simply be.",
				"They are known for their curiosity and friendly approach to boats: mothers and calves that come within an oar's reach. A gift of nature that exists only a few months a year — and you'll live it from the heart of Baja.",
			],
			commitTitle: "Responsible watching",
			commitText: "We sail with authorized local operators, respecting distances, times and the animals' behavior. They decide to come close — we are simply there.",
		},
		split: {
			image: "/gray-whale-close-up-magdalena-bay.jpg",
			alt: "Gray whale up close in Magdalena Bay",
			kicker: "How the experience works",
			title: "The road to the magic",
			text: "The adventure starts early: we pick you up in La Paz and cross the Baja desert as the sun rises among giant cardón cacti. In Puerto Chale your boat is already waiting — the air smells of sea, mangrove and history.",
		},
		timeline: {
			kicker: "Day itinerary",
			title: "Step by step",
			items: [
				{ time: "5:00 AM", title: "Dawn departure", text: "We pick you up at your hotel or Airbnb in La Paz and head for the Pacific." },
				{ time: "2.5 hours", title: "The road to the Pacific", text: "A crossing through the Baja desert landscapes to Puerto Chale, where your boat is already waiting." },
				{ time: "2-3 hours", title: "Meeting the whales", text: "We sail inside the lagoon, the temporary home of these giants. This is where they mate, where their calves are born, where they rest after the longest migration in the animal kingdom." },
				{ time: "Midday", title: "Local lunch", text: "Lunch in Puerto Chale, prepared by the local community." },
				{ time: "Afternoon", title: "Return to La Paz", text: "We drive back through the desert with a full heart and the photos of your encounter." },
			],
		},
		fauna: {
			kicker: "Sanctuary wildlife",
			title: "The lagoon is alive",
			items: [
				{ image: "/images/especies/ballena-gris-real.jpeg", alt: "Gray whale", label: "Gray Whale · Jan-Mar" },
				{ image: "/gray-whale-mother-and-calf-swimming-together-in-ba.jpg", alt: "Gray whale mother and calf", label: "Mothers and Calves · Jan-Mar" },
				{ image: "/images/especies/delfinsaltando.jpeg", alt: "Dolphin", label: "Dolphins · Year-round" },
				{ image: "/images/especies/lobomarinonadando.jpeg", alt: "Sea lion", label: "Sea Lions · Year-round" },
				{ image: "/brown-pelicans-flying-over-ocean-in-baja-californi.jpg", alt: "Pelicans", label: "Seabirds · Year-round" },
				{ image: "/magnificent-frigatebird-soaring-over-ocean-in-baja.jpg", alt: "Frigatebird", label: "Frigatebirds · Year-round" },
			],
		},
		includes: {
			kicker: "Your experience includes",
			title: "Everything for an unforgettable encounter",
			items: [
				{ title: "Round-trip transport", text: "Pickup at your hotel or Airbnb in La Paz, there and back to Puerto Chale." },
				{ title: "Officially permitted boat", text: "Sailing inside the lagoon with authorized local operators." },
				{ title: "Marine biologist guide", text: "Animal behavior interpretation throughout the trip." },
				{ title: "Local lunch", text: "Lunch in Puerto Chale prepared by the community." },
				{ title: "Photo and video included", text: "Professional captures of your encounter, ready to relive the moment." },
			],
		},
		pricing: {
			kicker: "Tour options",
			title: "Book your gray whale encounter",
			cards: [
				{
					name: "Shared · 2 hours on the water",
					amountMxn: 2800,
					amountNote: "/ person",
					items: [
						"Round-trip transport from La Paz",
						"2 hours sailing with whales",
						"Marine biologist guide",
						"Local lunch included",
						"Photo and video included",
					],
					waText: "I want to book the shared Gray Whale Puerto Chale tour",
				},
				{
					name: "Shared · 3 hours on the water",
					amountMxn: 3000,
					amountNote: "/ person",
					items: [
						"Round-trip transport from La Paz",
						"3 hours sailing with whales",
						"Marine biologist guide",
						"Local lunch included",
						"Photo and video included",
					],
					waText: "I want to book the 3-hour Gray Whale Puerto Chale tour",
					featured: true,
					featuredTag: "More time",
				},
			],
			note: "Traveling as a group? Premium private boat for $14,000 MXN (up to 6 people, 3 hours on the water). Official season: January to March only.",
		},
		finalCta: {
			image: "/gray-whale-breaching-sunset-sea-of-cortez.jpg",
			alt: "Gray whale breaching at sunset",
			title: "It only exists a few months a year",
			text: "Gray whale mothers and calves await in Puerto Chale. Book your place in the sanctuary.",
			waText: "I want to book Gray Whale Puerto Chale",
		},
	},

	"tour-espiritu-santo": {
		breadcrumb: "Espiritu Santo Island",
		hero: {
			image: "/espiritu-santo-island-paradise-beach.jpg",
			alt: "Paradise beach on Espiritu Santo Island",
			kicker: "Espiritu Santo Island · UNESCO World Heritage",
			title: "Swim with curious sea lions",
			text: "Pristine beaches, crystal-clear waters and one of the largest sea lion colonies in the Gulf of California. The aquarium of the world, one boat ride from La Paz.",
		},
		quickFacts: [
			{ value: "6 hours", label: "La Paz main pier" },
			{ value: "2-10 people", label: "Small groups" },
			{ value: "Year-round", label: "Season" },
			{ value: "UNESCO", label: "Biosphere Reserve" },
		],
		story: {
			kicker: "A jewel of the Gulf of California",
			title: "The aquarium of the world",
			paragraphs: [
				"Espiritu Santo Island is home to one of the largest sea lion colonies in the Gulf of California. Here you'll live a responsible, guided encounter with these animals in crystal-clear waters, within a unique natural environment.",
				"Our specialized guides accompany you throughout the experience, sharing knowledge about natural history, marine conservation and best practices for interacting with wildlife respectfully.",
			],
			commitTitle: "Pupping season",
			commitText: "From June 1 to August 31 swimming with the sea lions is not allowed due to pupping season; the experience is done by observation from the boat, for the safety of the pups.",
		},
		split: {
			image: "/picnic-beach-espiritu-santo.jpg",
			alt: "Picnic on a beach of Espiritu Santo Island",
			kicker: "How the experience works",
			title: "Snorkeling, pristine beaches and a picnic",
			text: "After the swim at Los Islotes we sail to one of the archipelago's beaches: light sand, turquoise water and striking rock formations. Free time to swim, walk or simply be — with a picnic included by the sea.",
		},
		timeline: {
			kicker: "Day itinerary",
			title: "Step by step",
			items: [
				{ time: "Morning", title: "Departure from La Paz", text: "We meet at the main pier, set sail with the morning sun and head north through the Gulf of California." },
				{ time: "Los Islotes", title: "Swim with sea lions", text: "A respectful, guided encounter with one of the largest colonies in the Gulf. Gear included and in-water accompaniment at all times." },
				{ time: "Midday", title: "Archipelago beach", text: "A stop at a pristine beach of the archipelago: light sand, turquoise water and free time to explore." },
				{ time: "Lunch", title: "Picnic by the sea", text: "Picnic included on the beach, surrounded by the reserve's landscape." },
				{ time: "Afternoon", title: "Scenic return", text: "We sail back to La Paz with the chance of sightings along the way." },
			],
		},
		fauna: {
			kicker: "Reserve wildlife",
			title: "Life everywhere you look",
			items: [
				{ image: "/swimming-with-sea-lions.jpg", alt: "Swimming with sea lions", label: "Sea Lions · Year-round" },
				{ image: "/sea-lions-resting-on-rocks-in-baja-california-sur.jpg", alt: "Sea lions on the rocks", label: "Los Islotes Rookery" },
				{ image: "/pristine-beach-turquoise-water-espiritu-santo-isla.jpg", alt: "Pristine beach", label: "Pristine Beaches" },
				{ image: "/snorkeling-crystal-clear-water.jpg", alt: "Snorkeling", label: "Reefs and Fish" },
				{ image: "/brown-pelicans-flying-over-ocean-in-baja-californi.jpg", alt: "Pelicans", label: "Seabirds" },
				{ image: "/images/especies/delfinsaltando.jpeg", alt: "Dolphins", label: "Dolphins · Year-round" },
			],
		},
		includes: {
			kicker: "Your experience includes",
			title: "Everything for a full day in paradise",
			items: [
				{ title: "Sailing through the reserve", text: "Departure and return from La Paz's main pier." },
				{ title: "Swim with sea lions", text: "Guided encounter at Los Islotes with snorkeling gear included." },
				{ title: "Beach picnic", text: "Food and drinks by the sea on an archipelago beach." },
				{ title: "Photo and video included", text: "Professional captures of your experience, ready to relive the moment." },
			],
		},
		pricing: {
			kicker: "Price",
			title: "Book your day at Espiritu Santo Island",
			cards: [
				{
					name: "Shared",
					amountMxn: 1800,
					amountNote: "/ person",
					items: [
						"Shared boat, 2-10 people",
						"Swim with sea lions at Los Islotes",
						"Snorkeling gear included",
						"Beach picnic",
						"Guide, photo/video included",
					],
					waText: "I want to book Espiritu Santo Island",
				},
				{
					name: "Private boat",
					amountText: "Quote",
					amountNote: "for your group",
					items: [
						"Boat exclusively for your group",
						"Flexible schedule within the day",
						"Same itinerary and gear included",
						"Guide, photo/video included",
					],
					waText: "I want a quote for private Espiritu Santo Island",
					featured: true,
					featuredTag: "Private",
				},
			],
			note: "From June 1 to August 31 the sea lion swim is replaced by observation from the boat (pupping season).",
		},
		finalCta: {
			image: "/espiritu-santo-island-paradise-beach.jpg",
			alt: "Espiritu Santo Island",
			title: "Paradise is one boat ride from La Paz",
			text: "Playful sea lions, pristine beaches and the blue of the aquarium of the world. Book your spot.",
			waText: "I want to book Espiritu Santo Island",
		},
	},

	"buceo-cabo-pulmo": {
		breadcrumb: "Scuba Diving Cabo Pulmo",
		hero: {
			image: "/coral-reef-underwater-diving-cabo-pulmo-colorful-f.jpg",
			alt: "Coral reef in Cabo Pulmo",
			kicker: "Cabo Pulmo · National Park",
			title: "The only living reef in the Gulf",
			text: "25,000 years of coral, bull sharks, massive schools of fish. Dive in one of the most successful marine reserves in the world.",
		},
		quickFacts: [
			{ value: "Full day", label: "Departure from La Paz" },
			{ value: "2-6 people", label: "Small groups" },
			{ value: "Year-round", label: "Season" },
			{ value: "2 dives", label: "National Park" },
		],
		story: {
			kicker: "Cabo Pulmo National Park",
			title: "The reserve that came back to life",
			paragraphs: [
				"Cabo Pulmo is the only living coral reef in the Gulf of California, more than 25,000 years old. After decades of community-led protection, its biomass recovered like nowhere else on the planet: today it is one of the world's greatest conservation success stories.",
				"Diving here is entering a cloud of fish: massive schools of jacks, bull sharks, giant groupers, turtles and — with luck — the famous jack tornado. Every dive is led by certified instructors who know the park by heart.",
			],
			commitTitle: "A protected National Park",
			commitText: "Cabo Pulmo is a protected natural area: small groups, low-impact practices and absolute respect for the reef on every dive.",
		},
		split: {
			image: "/buceo-cabo-pulmo-cardumen.jpg",
			alt: "Massive school of fish in Cabo Pulmo",
			kicker: "How the experience works",
			title: "Two dives on the reef",
			text: "We leave La Paz early for the National Park. We do two guided dives at the reef's best sites depending on the day's conditions, with a surface interval, snacks and all the logistics taken care of.",
		},
		timeline: {
			kicker: "Day itinerary",
			title: "Step by step",
			items: [
				{ time: "Early", title: "Departure from La Paz", text: "Road transfer to Cabo Pulmo, on the east coast of the Gulf." },
				{ time: "Arrival", title: "Briefing and gear", text: "Gear setup, site briefing and the National Park's rules." },
				{ time: "Dive 1", title: "First reef dive", text: "A guided dive at one of the park's iconic sites." },
				{ time: "Surface", title: "Interval and snacks", text: "Surface rest with water, fruit and cookies on board." },
				{ time: "Dive 2", title: "Second dive", text: "A second dive at another point of the reef depending on conditions." },
				{ time: "Afternoon", title: "Return to La Paz", text: "We head back with the photos and videos of your day in the park." },
			],
		},
		fauna: {
			kicker: "Reef life",
			title: "What you can find in the park",
			items: [
				{ image: "/coral-reef-underwater-cabo-pulmo-colorful-tropical.jpg", alt: "Coral reef", label: "Coral · 25,000 years" },
				{ image: "/buceo-cabo-pulmo-cardumen.jpg", alt: "School of fish", label: "Massive Schools" },
				{ image: "/buceo-cabo-pulmo-buzo.jpg", alt: "Diver in Cabo Pulmo", label: "Bull Sharks and Groupers" },
			],
		},
		includes: {
			kicker: "Your experience includes",
			title: "Everything you need to dive the park",
			items: [
				{ title: "2 guided dives", text: "At the reef's best sites depending on the day's conditions." },
				{ title: "Certified guide", text: "Instructors with experience in the National Park." },
				{ title: "Water and snacks", text: "Hydration, fruit and cookies on board throughout the trip." },
				{ title: "Photo and video included", text: "Professional underwater captures of your experience." },
			],
		},
		pricing: {
			kicker: "Diving options",
			title: "Choose your Cabo Pulmo experience",
			cards: [
				{
					name: "Certified divers",
					amountMxn: 3200,
					amountNote: "/ person with your own gear",
					items: [
						"2 shared dives",
						"$3,400 MXN with full gear included",
						"Groups of up to 6 people",
						"Water and cookies on board",
						"Certified guide, photo/video",
					],
					waText: "I want to book certified diving in Cabo Pulmo",
				},
				{
					name: "Discovery Scuba Diver",
					amountMxn: 3800,
					amountNote: "/ person",
					items: [
						"For beginners with no experience",
						"Full theory instruction",
						"Shallow-water practice",
						"2 instructor-supervised dives",
					],
					waText: "I want to book Discovery in Cabo Pulmo",
					featured: true,
					featuredTag: "No certification",
				},
			],
			note: "Private group? Private diving from $12,000 MXN (1-3 divers, flat rate) plus a fee per additional diver. Message us to set up your trip.",
		},
		finalCta: {
			image: "/coral-reef-underwater-diving-cabo-pulmo-colorful-f.jpg",
			alt: "Cabo Pulmo reef",
			title: "Dive the reef that came back to life",
			text: "25,000 years of coral await in Cabo Pulmo National Park. Limited spots per departure.",
			waText: "I want to book diving in Cabo Pulmo",
		},
	},

	"buceo-la-paz": {
		breadcrumb: "Scuba Diving Espiritu Santo Island",
		hero: {
			image: "/scuba-diving-underwater-sea-lions-swimming-playful.jpg",
			alt: "Diving with sea lions at Los Islotes",
			kicker: "Espiritu Santo Archipelago · UNESCO World Heritage",
			title: "Dive with curious sea lions",
			text: "Los Islotes is home to more than 400 sea lions that play, spin and circle around you underwater. The most playful combination of diving and wildlife in La Paz.",
		},
		quickFacts: [
			{ value: "7-8 hours", label: "La Paz main pier" },
			{ value: "2-6 people", label: "Small groups" },
			{ value: "Year-round", label: "Season" },
			{ value: "2-3 dives", label: "Los Islotes and more" },
		],
		story: {
			kicker: "The puppies of the sea",
			title: "They want to play too",
			paragraphs: [
				"Los Islotes, at the northern tip of the Espiritu Santo archipelago, hosts a colony of more than 400 sea lions that are extremely curious and playful with divers. They circle you, do pirouettes and create memories that stay with you.",
				"Beyond the rookery, we visit other sites of the archipelago with striking rock formations, underwater caves, shipwrecks full of life and a marine diversity that earned it the title of the aquarium of the world.",
			],
			commitTitle: "A responsible encounter",
			commitText: "We dive with low-impact practices and respect for the colony: they decide to come close — and they almost always do.",
		},
		split: {
			image: "/scuba-diving-underwater-la-paz-sea-lions-swimming.jpg",
			alt: "Sea lions swimming with divers",
			kicker: "How the experience works",
			title: "A full day of diving in the reserve",
			text: "We set sail from La Paz's main pier toward the archipelago. Two to three guided dives depending on conditions, with lunch and drinks included — and sea lions for company.",
		},
		timeline: {
			kicker: "Day itinerary",
			title: "Step by step",
			items: [
				{ time: "Morning", title: "Departure from La Paz", text: "We meet at the main pier and sail toward the Espiritu Santo archipelago." },
				{ time: "Los Islotes", title: "Dive with sea lions", text: "A guided dive at the most famous rookery in the Gulf of California." },
				{ time: "Surface", title: "Interval and lunch", text: "Rest, lunch and drinks on board facing the reserve's landscapes." },
				{ time: "Dive 2", title: "Shipwrecks and caves", text: "A second dive at sites with shipwrecks, rock formations and diverse marine life." },
				{ time: "Afternoon", title: "Return to La Paz", text: "Back to the pier with the photos and videos of your day." },
			],
		},
		fauna: {
			kicker: "Archipelago life",
			title: "What awaits you underwater",
			items: [
				{ image: "/sea-lions-swimming-underwater.jpg", alt: "Sea lions underwater", label: "Sea Lions · Year-round" },
				{ image: "/scuba-diving-underwater-la-paz-sea-lions-swimming.jpg", alt: "Diving with sea lions", label: "Los Islotes" },
				{ image: "/buceo-la-paz-buzo.jpg", alt: "Diver in La Paz", label: "Shipwrecks and Caves" },
			],
		},
		includes: {
			kicker: "Your experience includes",
			title: "Everything to dive the aquarium of the world",
			items: [
				{ title: "Panga transport", text: "Departure and return from La Paz's main pier." },
				{ title: "2-3 dives", text: "Guided by a certified dive master at the archipelago's best sites." },
				{ title: "Full gear", text: "Complete diving equipment included in the full-gear option." },
				{ title: "Lunch and drinks", text: "Food and drinks on board throughout the trip." },
				{ title: "Photo and video included", text: "Underwater captures of your experience." },
			],
		},
		pricing: {
			kicker: "Diving options",
			title: "Choose your Espiritu Santo experience",
			cards: [
				{
					name: "Certified divers",
					amountMxn: 3700,
					amountNote: "/ person",
					items: [
						"2-3 dives in the archipelago",
						"Certified dive master",
						"Lunch and drinks included",
						"Photo and video included",
					],
					waText: "I want to book certified diving at Espiritu Santo Island",
				},
				{
					name: "Discovery Scuba Diver",
					amountMxn: 4200,
					amountNote: "/ person",
					items: [
						"For beginners with no experience",
						"Full theory instruction",
						"Shallow-water practice",
						"Instructor-supervised dives",
					],
					waText: "I want to book Discovery at Espiritu Santo Island",
					featured: true,
					featuredTag: "No certification",
				},
			],
			note: "Also available for snorkelers: no certification is required for the sea lion snorkel.",
		},
		finalCta: {
			image: "/scuba-diving-underwater-sea-lions-swimming-playful.jpg",
			alt: "Playful sea lions",
			title: "Swim with the puppies of the sea",
			text: "An experience you'll never forget, in a UNESCO World Heritage site. Book your dive today.",
			waText: "I want to book diving at Espiritu Santo Island",
		},
	},

	"scuba-discovery": {
		breadcrumb: "Scuba Discovery from the Beach",
		hero: {
			image: "/snorkeling-coral-reef.jpg",
			alt: "Scuba Discovery from the beach in La Paz",
			kicker: "La Paz · From the beach",
			title: "Your first breath underwater",
			text: "No certification, no prior experience, no boat: you walk in from the beach with an instructor by your side at all times. Maximum depth 6 meters.",
		},
		quickFacts: [
			{ value: "Half day", label: "Beach in La Paz" },
			{ value: "1-6 people", label: "Per instructor" },
			{ value: "Year-round", label: "Season" },
			{ value: "Max 6 m", label: "Depth" },
		],
		story: {
			kicker: "For beginners",
			title: "Diving, without barriers",
			paragraphs: [
				"Scuba Discovery is the most accessible way to try diving: you walk into the water from the beach, practice the basic skills in shallow water and explore the seabed at a maximum depth of 6 meters.",
				"No certification or prior experience needed — just the desire to discover the Sea of Cortez from below. A certified instructor accompanies you at all times, from the theory to the last bubble.",
			],
			commitTitle: "Your first step",
			commitText: "If you fall in love with diving, this experience is the first step toward your Open Water certification. Suitable for beginners from age 10.",
		},
		split: {
			image: "/snorkeling-crystal-clear-water.jpg",
			alt: "Crystal-clear waters in La Paz",
			kicker: "How the experience works",
			title: "From the briefing to the bubbles",
			text: "We start on the beach with a simple theory introduction, practice the basic skills where you can touch the bottom, and when you're ready we explore the coastal reef accompanied at all times. Photos included.",
		},
		timeline: {
			kicker: "Itinerary",
			title: "Step by step",
			items: [
				{ time: "Welcome", title: "Beach briefing", text: "A simple theory introduction: the gear, breathing and the basic signals." },
				{ time: "Shallow water", title: "Skills practice", text: "Basic exercises in water where you can touch the bottom, at your own pace and without pressure." },
				{ time: "The dive", title: "Guided exploration", text: "A guided dive at a maximum depth of 6 meters along the coastal reef." },
				{ time: "Wrap-up", title: "Photos and next step", text: "You get the photos of your experience and, if you want more, we'll tell you how to get certified." },
			],
		},
		includes: {
			kicker: "Your experience includes",
			title: "Everything for your first time underwater",
			items: [
				{ title: "Certified instructor", text: "One-on-one accompaniment throughout the experience." },
				{ title: "Full gear", text: "All diving equipment included, fitted to you." },
				{ title: "Shallow-water practice", text: "Briefing and exercises where you can touch the bottom, no rush." },
				{ title: "Photos included", text: "Captures of your first breath underwater." },
			],
		},
		pricing: {
			kicker: "Price",
			title: "Book your Scuba Discovery",
			cards: [
				{
					name: "Per person",
					amountMxn: 1500,
					amountNote: "/ person",
					items: [
						"No prior experience needed",
						"Certified instructor at all times",
						"Full gear included",
						"Maximum depth of 6 meters",
						"Photos included",
					],
					waText: "I want to book Scuba Discovery from the Beach",
				},
				{
					name: "Private group",
					amountText: "Quote",
					amountNote: "up to 6 people",
					items: [
						"An instructor exclusively for your group",
						"Flexible schedule",
						"Same gear and itinerary",
						"Great for families and friends",
					],
					waText: "I want a quote for private Scuba Discovery",
					featured: true,
					featuredTag: "New",
				},
			],
			note: "Suitable for beginners from age 10. If you continue toward certification, this experience counts as your first contact with diving.",
		},
		finalCta: {
			image: "/snorkeling-crystal-clear-water.jpg",
			alt: "Crystal-clear waters of the Sea of Cortez",
			title: "Breathe underwater for the first time",
			text: "No certification, no experience, no excuses. The Sea of Cortez awaits, 6 meters down.",
			waText: "I want to book Scuba Discovery from the Beach",
		},
	},
}
