import type { ExpeditionPageData } from "@/components/ExpeditionDetail"

/** Contenu français des pages de détail des expéditions. */
export const expeditionPagesFr: Record<string, ExpeditionPageData> = {
	"safari-la-ventana": {
		breadcrumb: "Ocean Safari La Ventana",
		hero: {
			image: "/images/orca-safari.jpg",
			alt: "Seafari à La Ventana, Basse-Californie du Sud",
			kicker: "La Ventana · Île Cerralvo",
			title: "Trouvez l'extraordinaire",
			text: "Explorez l'un des décors marins les plus surprenants du golfe de Californie. Chaque sortie est différente. Chaque rencontre est réelle.",
		},
		quickFacts: [
			{ value: "6 heures", label: "Départ à 8h00" },
			{ value: "2-8 personnes", label: "Partagé ou privé" },
			{ value: "Avr - Juin", label: "Saison des mobules" },
			{ value: "40 min", label: "Depuis La Paz" },
		],
		story: {
			kicker: "Qu'est-ce que le Seafari",
			title: "Pas de scénario. Pas de spectacle.",
			paragraphs: [
				"Le Seafari commence à La Ventana, à 40 minutes de La Paz, d'où nous mettons le cap vers le grand bleu. À bord du bateau, guidés par des biologistes marins et des capitaines locaux, nous naviguons à la recherche de l'inattendu : des mobules qui volent, des dauphins qui nous escortent, des baleines qui émergent comme des légendes vivantes.",
				"Contrairement à un tour classique où tout est établi à l'avance, le Seafari est conçu comme une expérience dynamique et authentique, axée sur la maximisation des rencontres avec la faune. Chaque sortie est unique — car nous travaillons avec une faune en liberté : nous ne garantissons pas d'observations précises, mais nous garantissons l'engagement, l'expérience et une approche respectueuse.",
			],
			commitTitle: "Notre engagement",
			commitText: "Nous respectons profondément la vie marine. Nos safaris sont conçus pour observer sans déranger, apprendre sans interférer et s'émerveiller sans nuire à l'écosystème qui nous accueille.",
		},
		split: {
			image: "/images/safari/nuestrocompromiso2.jpeg",
			alt: "Guide avec équipement de snorkeling au Seafari de La Ventana",
			kicker: "Comment se déroule l'expérience",
			title: "Une journée complète conçue pour la rencontre",
			text: "Navigation à la recherche de la vie marine, snorkeling quand les conditions le permettent et exploration de l'île Cerralvo — le tout guidé par des biologistes marins qui lisent le comportement animal et les signes de la mer en temps réel. Nous terminons la journée avec un ceviche frais et des fruits de saison face à la mer.",
		},
		timeline: {
			kicker: "Itinéraire détaillé",
			title: "Heure par heure",
			items: [
				{ time: "8h00", title: "Accueil et briefing", text: "Rencontrez votre guide biologiste marin et recevez une introduction sur la vie marine que vous pourriez rencontrer." },
				{ time: "8h30 - 11h30", title: "Navigation et recherche", text: "Nous naviguons à la recherche de la vie marine, en suivant les schémas de comportement et les signes naturels." },
				{ time: "11h30 - 13h00", title: "Exploration de l'île Cerralvo", text: "Selon les conditions, snorkeling ou exploration des eaux cristallines autour de l'île." },
				{ time: "13h00 - 13h30", title: "Collation et repos", text: "Ceviche frais et fruits de saison pendant que nous nous reposons." },
				{ time: "13h30 - 14h00", title: "Retour panoramique", text: "Nous naviguons vers La Ventana, avec la possibilité de nouvelles observations en chemin." },
			],
		},
		fauna: {
			kicker: "Faune par saison",
			title: "Le golfe de Californie est l'une des mers les plus riches en biodiversité de la planète",
			items: [
				{ image: "/images/especies/mobulaschafa.jpeg", alt: "Mobules", label: "Mobules · Avr-Juin" },
				{ image: "/images/especies/delfinsaltando.jpeg", alt: "Dauphin qui saute", label: "Dauphins · Toute l'année" },
				{ image: "/images/especies/ballenasaltando2.jpeg", alt: "Baleine à bosse", label: "Baleine à bosse · Déc-Avr" },
				{ image: "/images/especies/lobomarinonadando.jpeg", alt: "Otarie", label: "Otaries · Toute l'année" },
				{ image: "/images/especies/cachalote2.jpeg", alt: "Cachalot", label: "Cachalots · Juin-Nov" },
				{ image: "/images/especies/orcalaventana.jpeg", alt: "Orque", label: "Orques · Imprévisible" },
			],
		},
		includes: {
			kicker: "Votre expérience comprend",
			title: "Tout ce qu'il vous faut pour profiter du Seafari",
			items: [
				{ title: "Safari marin de 6 h", text: "Navigation à la recherche de la vie marine avec des biologistes marins et des capitaines locaux experts de la zone." },
				{ title: "Équipement complet", text: "Combinaison, tuba et matériel de plage inclus pour toute la sortie." },
				{ title: "Pique-nique sur l'île Cerralvo", text: "Ceviche frais, fruits de saison, snacks et boissons face à la mer." },
				{ title: "Photo et vidéo inclus", text: "Des clichés professionnels de votre expérience, prêts à revivre le moment." },
			],
		},
		pricing: {
			kicker: "Prix",
			title: "Réservez votre Seafari à La Ventana",
			cards: [
				{
					name: "Partagé",
					amountMxn: 3000,
					amountNote: "/ personne",
					items: [
						"Minimum 4 personnes",
						"Bateau partagé, jusqu'à 8-10 pers.",
						"Combinaison, tuba et matériel de plage",
						"Pique-nique sur l'île Cerralvo",
						"Guide biologiste marin, photo/vidéo inclus",
					],
					waText: "Je veux réserver l'Ocean Safari La Ventana partagé",
				},
				{
					name: "Bateau privé",
					amountMxn: 16000,
					amountNote: "/ jusqu'à 8 pers.",
					items: [
						"Bateau exclusivement pour votre groupe",
						"Horaire flexible dans la journée",
						"Même itinéraire et équipement inclus",
						"Guide biologiste marin, photo/vidéo inclus",
					],
					waText: "Je veux réserver l'Ocean Safari La Ventana privé",
					featured: true,
					featuredTag: "Privé",
				},
			],
			note: "Recommandé aux personnes sachant nager ; les enfants voyagent sous la surveillance d'un adulte. Places limitées pendant la saison des mobules (avril-juin).",
		},
		finalCta: {
			image: "/images/orca-safari.jpg",
			alt: "Mobules qui sautent à La Ventana",
			title: "Des mobules qui volent, des baleines qui émergent",
			text: "Vivez un safari sans scénario, à 40 minutes de La Paz. Places limitées par départ.",
			waText: "Je veux réserver l'Ocean Safari La Ventana",
		},
	},

	"tiburon-ballena": {
		breadcrumb: "Requin-Baleine",
		hero: {
			image: "/tiburon-ballena-drone.jpg",
			alt: "Nager avec des requins-baleines à La Paz",
			kicker: "La Paz · Nov - Mar",
			title: "Nagez avec le plus grand poisson du monde",
			text: "Nager avec les requins-baleines est l'une des expériences marines les plus emblématiques de La Paz, Basse-Californie du Sud. Des eaux calmes, des rencontres responsables et réglementées.",
		},
		quickFacts: [
			{ value: "2 heures", label: "Quai principal de La Paz" },
			{ value: "Nov - Mar", label: "Saison officielle" },
			{ value: "Réglementé", label: "Zone et permis officiels" },
			{ value: "Tous âges", label: "Activité accessible" },
		],
		story: {
			kicker: "Nagez avec le plus grand poisson du monde",
			title: "Un géant paisible, en sa saison",
			paragraphs: [
				"Chaque saison, ces géants des mers arrivent dans les eaux calmes de la baie, créant une occasion unique de les observer et de nager à leurs côtés de manière responsable, toujours selon les directives officielles et avec des opérateurs autorisés.",
				"Nos guides spécialisés vous accompagnent tout au long de l'expérience, partageant leurs connaissances sur l'espèce, son importance écologique et les bonnes pratiques pour profiter de cette rencontre avec respect et conscience.",
			],
			commitTitle: "Une activité réglementée",
			commitText: "À La Paz, l'accès à la zone de baignade et d'observation est réglementé. Seuls les bateaux disposant d'un permis en cours de validité peuvent y entrer, en respectant les tours et les horaires autorisés pour protéger l'espèce.",
		},
		split: {
			image: "/manta-ray-swimming.png",
			alt: "Vie marine dans le golfe de Californie",
			kicker: "Que voir d'autre",
			title: "Le golfe de Californie ne se repose jamais",
			text: "Sur le chemin vers la zone d'observation, il est fréquent de croiser des otaries curieuses et des dauphins qui s'approchent du bateau — la mer de Cortez, « l'aquarium du monde » selon Jacques Cousteau, a toujours quelque chose à montrer.",
		},
		timeline: {
			kicker: "Itinéraire de la journée",
			title: "Étape par étape",
			items: [
				{ time: "Quai principal", title: "Accueil et briefing", text: "Rendez-vous au quai principal de La Paz. Introduction à l'expérience, à l'utilisation du matériel et aux règles d'une activité responsable." },
				{ time: "Navigation", title: "Recherche et localisation", text: "Nous naviguons dans la zone autorisée en suivant les protocoles définis par les autorités, en respectant les tours et horaires autorisés." },
				{ time: "Dans l'eau", title: "Nager avec le requin-baleine", text: "Une rencontre guidée et responsable avec le plus grand poisson du monde, toujours accompagné de votre guide certifié." },
				{ time: "Retour", title: "Retour à La Paz", text: "Nous rentrons au quai avec les photos et vidéos de votre rencontre." },
			],
		},
		includes: {
			kicker: "Votre expérience comprend",
			title: "Tout pour une rencontre sûre et responsable",
			items: [
				{ title: "Transport en bateau", text: "Départ et retour depuis le quai principal de La Paz." },
				{ title: "Guide certifié", text: "Une équipe spécialisée bilingue qui partage ses connaissances sur l'espèce." },
				{ title: "Équipement de snorkeling", text: "Masque, palmes et gilet de sauvetage pour explorer en toute tranquillité." },
				{ title: "Photos et vidéos", text: "De véritables souvenirs de votre aventure, capturés sur l'instant." },
				{ title: "Permis réglementé", text: "Accès autorisé à la zone d'observation officielle." },
			],
		},
		pricing: {
			kicker: "Prix",
			title: "Réservez votre nage avec le requin-baleine",
			cards: [
				{
					name: "Tour partagé",
					amountMxn: 1800,
					amountNote: "/ personne",
					items: [
						"Transport en panga partagée",
						"Guide certifié à vos côtés",
						"Équipement de snorkeling inclus",
						"Photos et vidéo de votre aventure",
						"Permis pour la zone réglementée",
					],
					waText: "Je veux réserver le tour Requin-Baleine",
				},
			],
			note: "Saison officielle : de novembre à mars, avec une haute saison de décembre à février. Accessible à tous les âges — les mineurs participent sous la surveillance d'un adulte.",
		},
		finalCta: {
			image: "/manta-ray-swimming.png",
			alt: "Vie marine à La Paz, Basse-Californie du Sud",
			title: "Prêt à nager avec le plus grand poisson du monde ?",
			text: "Le requin-baleine vous attend dans les eaux de La Paz. Une expérience unique, responsable et inoubliable.",
			waText: "Je veux réserver le tour Requin-Baleine",
		},
	},

	"safari-bahia-magdalena": {
		breadcrumb: "Safari Bahía Magdalena",
		hero: {
			image: "/images/marlin-bahia-magdalena-hero.jpeg",
			alt: "Marlin chassant des sardines à Bahía Magdalena",
			kicker: "Bahía Magdalena · Nov-Déc",
			title: "Le safari le plus sauvage du Pacifique",
			text: "Des milliers de sardines, des marlins qui chassent à pleine vitesse, des baleines qui se nourrissent. Un phénomène qui ne dure que deux mois par an — et vous pouvez le vivre de l'intérieur.",
		},
		quickFacts: [
			{ value: "Journée complète", label: "Départ à 5h00" },
			{ value: "2-6 personnes", label: "Petits groupes" },
			{ value: "Nov - Déc", label: "Sardine run" },
			{ value: "Mer ouverte", label: "Pacifique mexicain" },
		],
		story: {
			kicker: "Qu'est-ce que le sardine run",
			title: "Un événement aussi bref que puissant",
			paragraphs: [
				"Chaque année, en novembre et décembre, l'un des phénomènes les plus sauvages de la nature se produit : les eaux de Bahía Magdalena deviennent l'épicentre de la vie marine. Des milliers de sardines migrent en d'énormes bancs, attirant des prédateurs de premier ordre comme les marlins, les dorades, les otaries et même les baleines.",
				"Ce n'est pas un tour. C'est un incontournable pour les amoureux de l'océan. Vous mettrez le cap vers le grand bleu depuis l'un des endroits les plus préservés de la péninsule, lors d'un safari guidé par des biologistes marins, et deviendrez acteur de l'un des spectacles les plus intenses du Pacifique mexicain. Si les conditions le permettent, vous vous glisserez au cœur de l'action, flottant au-dessus d'un écosystème en mouvement.",
			],
			commitTitle: "Une faune en liberté",
			commitText: "Nous travaillons avec des animaux à l'état sauvage : nous ne garantissons pas d'observations précises, mais nous garantissons l'engagement, l'expérience et une approche respectueuse de l'écosystème qui nous accueille.",
		},
		split: {
			image: "/images/gallery/marlin-cazando.jpeg",
			alt: "Marlin rayé chassant un banc de sardines",
			kicker: "Comment se déroule l'expérience",
			title: "Une journée complète en mer ouverte",
			text: "Nous quittons La Paz à l'aube en direction du Pacifique. Nous naviguons à la recherche des bancs de sardines et de leurs prédateurs, avec la possibilité de se mettre à l'eau quand l'action le permet. Une journée longue, intense, absolument inoubliable.",
		},
		timeline: {
			kicker: "Itinéraire du safari",
			title: "Étape par étape",
			items: [
				{ time: "5h00", title: "Départ de La Paz", text: "Nous prenons la direction de la côte Pacifique, la porte d'entrée de Bahía Magdalena." },
				{ time: "7h30", title: "Vers le grand bleu", text: "Briefing avec votre guide biologiste marin et départ en bateau vers la mer ouverte." },
				{ time: "8h00 - 14h00", title: "Safari en mer ouverte", text: "Navigation à la recherche des bancs de sardines et de leurs prédateurs : marlins, dorades, otaries et baleines. Snorkeling si les conditions le permettent." },
				{ time: "14h30", title: "Déjeuner face à la mer", text: "Déjeuner inclus pour recharger les batteries après l'action." },
				{ time: "Après-midi", title: "Retour à La Paz", text: "Nous rentrons à travers le désert de la Baja, la carte mémoire pleine et les photos de votre aventure." },
			],
		},
		fauna: {
			kicker: "Faune de saison",
			title: "Les vedettes du sardine run",
			items: [
				{ image: "/images/especies/sardinas-banco.jpeg", alt: "Banc de sardines", label: "Sardines · Nov-Déc" },
				{ image: "/striped-marlin-underwater.jpg", alt: "Marlin rayé", label: "Marlin rayé · Nov-Déc" },
				{ image: "/images/especies/dorado.jpeg", alt: "Dorade", label: "Dorade · Nov-Déc" },
				{ image: "/images/especies/lobomarinonadando.jpeg", alt: "Otarie", label: "Otaries · Toute l'année" },
				{ image: "/images/especies/ballenasaltando2.jpeg", alt: "Baleine", label: "Baleines · Nov-Déc" },
				{ image: "/images/especies/delfinsaltando.jpeg", alt: "Dauphin", label: "Dauphins · Toute l'année" },
			],
		},
		includes: {
			kicker: "Votre expérience comprend",
			title: "Tout ce qu'il vous faut pour le safari le plus sauvage",
			items: [
				{ title: "Safari d'une journée", text: "Navigation en mer ouverte guidée par des biologistes marins et des capitaines locaux." },
				{ title: "Équipement de snorkeling", text: "Masque, palmes et combinaison pour se mettre à l'eau quand l'action le permet." },
				{ title: "Déjeuner et boissons", text: "Repas et boissons inclus pour une journée complète d'expédition." },
				{ title: "Photo et vidéo inclus", text: "Des clichés professionnels de votre expérience, prêts à revivre le moment." },
			],
		},
		pricing: {
			kicker: "Prix",
			title: "Réservez votre place au sardine run",
			cards: [
				{
					name: "Partagé",
					amountMxn: 3500,
					amountNote: "/ personne",
					items: [
						"Bateau partagé, 2-6 personnes",
						"Transport depuis La Paz",
						"Équipement de snorkeling inclus",
						"Déjeuner et boissons",
						"Guide biologiste marin, photo/vidéo inclus",
					],
					waText: "Je veux réserver le Safari Bahía Magdalena",
				},
				{
					name: "Bateau privé",
					amountText: "Sur devis",
					amountNote: "pour votre groupe",
					items: [
						"Bateau exclusivement pour votre groupe",
						"Horaire flexible dans la journée",
						"Même itinéraire et équipement inclus",
						"Guide biologiste marin, photo/vidéo inclus",
					],
					waText: "Je veux un devis pour le Safari Bahía Magdalena privé",
					featured: true,
					featuredTag: "Privé",
				},
			],
			note: "Un phénomène saisonnier : novembre et décembre seulement. Places très limitées par départ — réservez tôt.",
		},
		finalCta: {
			image: "/images/marlin-bahia-magdalena-hero.jpeg",
			alt: "Marlin chassant à Bahía Magdalena",
			title: "Cela n'arrive que deux mois par an",
			text: "Le safari le plus sauvage du Pacifique vous attend à Bahía Magdalena. Places limitées par saison.",
			waText: "Je veux réserver le Safari Bahía Magdalena",
		},
	},

	"tour-ballena-gris": {
		breadcrumb: "Baleine Grise Puerto Chale",
		hero: {
			image: "/ballena-gris-spyhop-drone.jpg",
			alt: "Baleine grise à Puerto Chale, Bahía Magdalena",
			kicker: "Puerto Chale · Jan - Mar",
			title: "Une rencontre ancestrale",
			text: "Chaque hiver, des milliers de baleines grises voyagent depuis l'Arctique jusqu'à ce lagon paisible pour mettre bas et se reproduire. Vous êtes sur le point d'entrer dans ce sanctuaire.",
		},
		quickFacts: [
			{ value: "9 heures", label: "Prise en charge à 5h00 à La Paz" },
			{ value: "Jusqu'à 8 personnes", label: "Par bateau" },
			{ value: "Jan - Mar", label: "Saison officielle" },
			{ value: "2-3 heures", label: "Sur l'eau avec les baleines" },
		],
		story: {
			kicker: "Ce n'est pas un tour",
			title: "C'est un privilège",
			paragraphs: [
				"Chaque hiver, quelque chose de sacré se produit dans le Pacifique mexicain. Des milliers de baleines grises parcourent plus de 20 000 km depuis l'Arctique jusqu'à un lagon paisible au milieu du désert... pour mettre bas, pour se reproduire, pour simplement être.",
				"Elles sont connues pour leur curiosité et leur approche amicale des bateaux : des mères et des baleineaux qui s'approchent à un coup de rame. Un cadeau de la nature qui n'existe que quelques mois par an — et vous le vivrez depuis le cœur de la Baja.",
			],
			commitTitle: "Observation responsable",
			commitText: "Nous naviguons avec des opérateurs locaux autorisés, en respectant les distances, les horaires et le comportement des animaux. Ce sont elles qui décident de s'approcher — nous sommes simplement là.",
		},
		split: {
			image: "/gray-whale-close-up-magdalena-bay.jpg",
			alt: "Baleine grise de près à Bahía Magdalena",
			kicker: "Comment se déroule l'expérience",
			title: "La route vers la magie",
			text: "L'aventure commence tôt : nous venons vous chercher à La Paz et traversons le désert de la Baja au lever du soleil, parmi les cardons géants. À Puerto Chale, votre bateau vous attend déjà — l'air sent la mer, la mangrove et l'histoire.",
		},
		timeline: {
			kicker: "Itinéraire de la journée",
			title: "Étape par étape",
			items: [
				{ time: "5h00", title: "Départ à l'aube", text: "Nous venons vous chercher à votre hôtel ou Airbnb à La Paz et prenons la direction du Pacifique." },
				{ time: "2 h 30", title: "La route vers le Pacifique", text: "Une traversée à travers les paysages désertiques de la Baja jusqu'à Puerto Chale, où votre bateau vous attend déjà." },
				{ time: "2-3 heures", title: "La rencontre avec les baleines", text: "Nous naviguons à l'intérieur du lagon, la demeure temporaire de ces géants. C'est ici qu'elles se reproduisent, que naissent leurs baleineaux, qu'elles se reposent après la plus longue migration du règne animal." },
				{ time: "Midi", title: "Déjeuner local", text: "Déjeuner à Puerto Chale, préparé par la communauté locale." },
				{ time: "Après-midi", title: "Retour à La Paz", text: "Nous rentrons à travers le désert le cœur plein et avec les photos de votre rencontre." },
			],
		},
		fauna: {
			kicker: "Faune du sanctuaire",
			title: "Le lagon est vivant",
			items: [
				{ image: "/images/especies/ballena-gris-real.jpeg", alt: "Baleine grise", label: "Baleine grise · Jan-Mar" },
				{ image: "/gray-whale-mother-and-calf-swimming-together-in-ba.jpg", alt: "Mère et baleineau gris", label: "Mères et baleineaux · Jan-Mar" },
				{ image: "/images/especies/delfinsaltando.jpeg", alt: "Dauphin", label: "Dauphins · Toute l'année" },
				{ image: "/images/especies/lobomarinonadando.jpeg", alt: "Otarie", label: "Otaries · Toute l'année" },
				{ image: "/brown-pelicans-flying-over-ocean-in-baja-californi.jpg", alt: "Pélicans", label: "Oiseaux marins · Toute l'année" },
				{ image: "/magnificent-frigatebird-soaring-over-ocean-in-baja.jpg", alt: "Frégate", label: "Frégates · Toute l'année" },
			],
		},
		includes: {
			kicker: "Votre expérience comprend",
			title: "Tout pour une rencontre inoubliable",
			items: [
				{ title: "Transport aller-retour", text: "Prise en charge à votre hôtel ou Airbnb à La Paz, aller et retour jusqu'à Puerto Chale." },
				{ title: "Bateau officiellement autorisé", text: "Navigation à l'intérieur du lagon avec des opérateurs locaux autorisés." },
				{ title: "Guide biologiste marin", text: "Interprétation du comportement animal tout au long du trajet." },
				{ title: "Déjeuner local", text: "Déjeuner à Puerto Chale préparé par la communauté." },
				{ title: "Photo et vidéo inclus", text: "Des clichés professionnels de votre rencontre, prêts à revivre le moment." },
			],
		},
		pricing: {
			kicker: "Options de tour",
			title: "Réservez votre rencontre avec la baleine grise",
			cards: [
				{
					name: "Partagé · 2 heures sur l'eau",
					amountMxn: 2800,
					amountNote: "/ personne",
					items: [
						"Transport aller-retour depuis La Paz",
						"2 heures de navigation avec les baleines",
						"Guide biologiste marin",
						"Déjeuner local inclus",
						"Photo et vidéo inclus",
					],
					waText: "Je veux réserver le tour partagé Baleine Grise Puerto Chale",
				},
				{
					name: "Partagé · 3 heures sur l'eau",
					amountMxn: 3000,
					amountNote: "/ personne",
					items: [
						"Transport aller-retour depuis La Paz",
						"3 heures de navigation avec les baleines",
						"Guide biologiste marin",
						"Déjeuner local inclus",
						"Photo et vidéo inclus",
					],
					waText: "Je veux réserver le tour de 3 heures Baleine Grise Puerto Chale",
					featured: true,
					featuredTag: "Plus de temps",
				},
			],
			note: "Vous voyagez en groupe ? Bateau privé premium à 14 000 MXN (jusqu'à 6 personnes, 3 heures sur l'eau). Saison officielle : de janvier à mars uniquement.",
		},
		finalCta: {
			image: "/gray-whale-breaching-sunset-sea-of-cortez.jpg",
			alt: "Baleine grise sortant de l'eau au coucher du soleil",
			title: "Cela n'existe que quelques mois par an",
			text: "Les mères et les baleineaux gris vous attendent à Puerto Chale. Réservez votre place dans le sanctuaire.",
			waText: "Je veux réserver Baleine Grise Puerto Chale",
		},
	},

	"tour-espiritu-santo": {
		breadcrumb: "Tour Snorkel Île Espíritu Santo",
		hero: {
			image: "/espiritu-santo-island-paradise-beach.jpg",
			alt: "Plage paradisiaque de l'île Espíritu Santo",
			kicker: "Île Espíritu Santo · Patrimoine mondial UNESCO",
			title: "Nagez avec des otaries curieuses",
			text: "Des plages vierges, des eaux cristallines et l'une des plus grandes colonies d'otaries du golfe de Californie. L'aquarium du monde, à une sortie en bateau de La Paz.",
		},
		quickFacts: [
			{ value: "6 heures", label: "Quai principal de La Paz" },
			{ value: "2-10 personnes", label: "Petits groupes" },
			{ value: "Toute l'année", label: "Saison" },
			{ value: "UNESCO", label: "Réserve de biosphère" },
		],
		story: {
			kicker: "Un joyau du golfe de Californie",
			title: "L'aquarium du monde",
			paragraphs: [
				"L'île Espíritu Santo abrite l'une des plus grandes colonies d'otaries du golfe de Californie. Vous y vivrez une rencontre responsable et guidée avec ces animaux dans des eaux cristallines, au sein d'un environnement naturel unique.",
				"Nos guides spécialisés vous accompagnent tout au long de l'expérience, partageant leurs connaissances sur l'histoire naturelle, la conservation marine et les bonnes pratiques pour interagir avec la faune de manière respectueuse.",
			],
			commitTitle: "Saison de reproduction",
			commitText: "Du 1er juin au 31 août, il n'est pas permis de nager avec les otaries en raison de la saison de reproduction ; l'expérience se fait par observation depuis le bateau, pour la sécurité des petits.",
		},
		split: {
			image: "/picnic-beach-espiritu-santo.jpg",
			alt: "Pique-nique sur une plage de l'île Espíritu Santo",
			kicker: "Comment se déroule l'expérience",
			title: "Snorkeling, plages vierges et pique-nique",
			text: "Après la baignade à Los Islotes, nous naviguons vers l'une des plages de l'archipel : sable clair, eau turquoise et formations rocheuses saisissantes. Temps libre pour nager, marcher ou simplement être — avec un pique-nique inclus face à la mer.",
		},
		timeline: {
			kicker: "Itinéraire de la journée",
			title: "Étape par étape",
			items: [
				{ time: "Matin", title: "Départ de La Paz", text: "Rendez-vous au quai principal, nous mettons les voiles avec le soleil du matin et prenons la direction du nord à travers le golfe de Californie." },
				{ time: "Los Islotes", title: "Nager avec les otaries", text: "Une rencontre respectueuse et guidée avec l'une des plus grandes colonies du Golfe. Équipement inclus et accompagnement dans l'eau à tout moment." },
				{ time: "Midi", title: "Plage de l'archipel", text: "Un arrêt sur une plage vierge de l'archipel : sable clair, eau turquoise et temps libre pour explorer." },
				{ time: "Déjeuner", title: "Pique-nique face à la mer", text: "Pique-nique inclus sur la plage, entouré du paysage de la réserve." },
				{ time: "Après-midi", title: "Retour panoramique", text: "Nous naviguons vers La Paz avec la possibilité d'observations en chemin." },
			],
		},
		fauna: {
			kicker: "Faune de la réserve",
			title: "La vie partout où le regard se pose",
			items: [
				{ image: "/swimming-with-sea-lions.jpg", alt: "Nager avec les otaries", label: "Otaries · Toute l'année" },
				{ image: "/sea-lions-resting-on-rocks-in-baja-california-sur.jpg", alt: "Otaries sur les rochers", label: "Colonie de Los Islotes" },
				{ image: "/pristine-beach-turquoise-water-espiritu-santo-isla.jpg", alt: "Plage vierge", label: "Plages vierges" },
				{ image: "/snorkeling-crystal-clear-water.jpg", alt: "Snorkeling", label: "Récifs et poissons" },
				{ image: "/brown-pelicans-flying-over-ocean-in-baja-californi.jpg", alt: "Pélicans", label: "Oiseaux marins" },
				{ image: "/images/especies/delfinsaltando.jpeg", alt: "Dauphins", label: "Dauphins · Toute l'année" },
			],
		},
		includes: {
			kicker: "Votre expérience comprend",
			title: "Tout pour une journée complète au paradis",
			items: [
				{ title: "Navigation dans la réserve", text: "Départ et retour depuis le quai principal de La Paz." },
				{ title: "Nager avec les otaries", text: "Rencontre guidée à Los Islotes avec équipement de snorkeling inclus." },
				{ title: "Pique-nique sur la plage", text: "Repas et boissons face à la mer sur une plage de l'archipel." },
				{ title: "Photo et vidéo inclus", text: "Des clichés professionnels de votre expérience, prêts à revivre le moment." },
			],
		},
		pricing: {
			kicker: "Prix",
			title: "Réservez votre journée à l'île Espíritu Santo",
			cards: [
				{
					name: "Partagé",
					amountMxn: 1800,
					amountNote: "/ personne",
					items: [
						"Bateau partagé, 2-10 personnes",
						"Nager avec les otaries à Los Islotes",
						"Équipement de snorkeling inclus",
						"Pique-nique sur la plage",
						"Guide, photo/vidéo inclus",
					],
					waText: "Je veux réserver l'Île Espíritu Santo",
				},
				{
					name: "Bateau privé",
					amountText: "Sur devis",
					amountNote: "pour votre groupe",
					items: [
						"Bateau exclusivement pour votre groupe",
						"Horaire flexible dans la journée",
						"Même itinéraire et équipement inclus",
						"Guide, photo/vidéo inclus",
					],
					waText: "Je veux un devis pour l'Île Espíritu Santo privée",
					featured: true,
					featuredTag: "Privé",
				},
			],
			note: "Du 1er juin au 31 août, la nage avec les otaries est remplacée par l'observation depuis le bateau (saison de reproduction).",
		},
		finalCta: {
			image: "/espiritu-santo-island-paradise-beach.jpg",
			alt: "Île Espíritu Santo",
			title: "Le paradis est à une sortie en bateau de La Paz",
			text: "Des otaries joueuses, des plages vierges et le bleu de l'aquarium du monde. Réservez votre place.",
			waText: "Je veux réserver l'Île Espíritu Santo",
		},
	},

	"buceo-cabo-pulmo": {
		breadcrumb: "Plongée Cabo Pulmo",
		hero: {
			image: "/coral-reef-underwater-diving-cabo-pulmo-colorful-f.jpg",
			alt: "Récif corallien à Cabo Pulmo",
			kicker: "Cabo Pulmo · Parc National",
			title: "Le seul récif vivant du Golfe",
			text: "25 000 ans de corail, des requins bouledogues, d'immenses bancs de poissons. Plongez dans l'une des réserves marines les plus réussies au monde.",
		},
		quickFacts: [
			{ value: "Journée complète", label: "Départ de La Paz" },
			{ value: "2-6 personnes", label: "Petits groupes" },
			{ value: "Toute l'année", label: "Saison" },
			{ value: "2 plongées", label: "Parc National" },
		],
		story: {
			kicker: "Parc National de Cabo Pulmo",
			title: "La réserve qui a repris vie",
			paragraphs: [
				"Cabo Pulmo est le seul récif corallien vivant du golfe de Californie, vieux de plus de 25 000 ans. Après des décennies de protection menée par la communauté, sa biomasse s'est régénérée comme nulle part ailleurs sur la planète : c'est aujourd'hui l'une des plus grandes réussites de conservation au monde.",
				"Plonger ici, c'est entrer dans un nuage de poissons : d'immenses bancs de carangues, des requins bouledogues, des mérous géants, des tortues et — avec un peu de chance — la fameuse tornade de carangues. Chaque plongée est menée par des instructeurs certifiés qui connaissent le parc par cœur.",
			],
			commitTitle: "Un Parc National protégé",
			commitText: "Cabo Pulmo est une aire naturelle protégée : petits groupes, pratiques à faible impact et respect absolu du récif à chaque plongée.",
		},
		split: {
			image: "/buceo-cabo-pulmo-cardumen.jpg",
			alt: "Immense banc de poissons à Cabo Pulmo",
			kicker: "Comment se déroule l'expérience",
			title: "Deux plongées sur le récif",
			text: "Nous quittons La Paz tôt pour le Parc National. Nous effectuons deux plongées guidées sur les meilleurs sites du récif selon les conditions du jour, avec un intervalle en surface, des collations et toute la logistique prise en charge.",
		},
		timeline: {
			kicker: "Itinéraire de la journée",
			title: "Étape par étape",
			items: [
				{ time: "Tôt", title: "Départ de La Paz", text: "Transfert par la route jusqu'à Cabo Pulmo, sur la côte est du Golfe." },
				{ time: "Arrivée", title: "Briefing et équipement", text: "Préparation du matériel, briefing des sites et règles du Parc National." },
				{ time: "Plongée 1", title: "Première plongée sur le récif", text: "Une plongée guidée sur l'un des sites emblématiques du parc." },
				{ time: "Surface", title: "Intervalle et collations", text: "Repos en surface avec eau, fruits et biscuits à bord." },
				{ time: "Plongée 2", title: "Deuxième plongée", text: "Une deuxième plongée sur un autre point du récif selon les conditions." },
				{ time: "Après-midi", title: "Retour à La Paz", text: "Nous rentrons avec les photos et vidéos de votre journée dans le parc." },
			],
		},
		fauna: {
			kicker: "Vie du récif",
			title: "Ce que vous pouvez trouver dans le parc",
			items: [
				{ image: "/coral-reef-underwater-cabo-pulmo-colorful-tropical.jpg", alt: "Récif corallien", label: "Corail · 25 000 ans" },
				{ image: "/buceo-cabo-pulmo-cardumen.jpg", alt: "Banc de poissons", label: "Bancs immenses" },
				{ image: "/buceo-cabo-pulmo-buzo.jpg", alt: "Plongeur à Cabo Pulmo", label: "Requins bouledogues et mérous" },
			],
		},
		includes: {
			kicker: "Votre expérience comprend",
			title: "Tout ce qu'il vous faut pour plonger dans le parc",
			items: [
				{ title: "2 plongées guidées", text: "Sur les meilleurs sites du récif selon les conditions du jour." },
				{ title: "Guide certifié", text: "Des instructeurs expérimentés dans le Parc National." },
				{ title: "Eau et collations", text: "Hydratation, fruits et biscuits à bord tout au long de la sortie." },
				{ title: "Photo et vidéo inclus", text: "Des clichés sous-marins professionnels de votre expérience." },
			],
		},
		pricing: {
			kicker: "Options de plongée",
			title: "Choisissez votre expérience à Cabo Pulmo",
			cards: [
				{
					name: "Plongeurs certifiés",
					amountMxn: 3200,
					amountNote: "/ personne avec votre propre équipement",
					items: [
						"2 plongées partagées",
						"3 400 MXN avec équipement complet inclus",
						"Groupes jusqu'à 6 personnes",
						"Eau et biscuits à bord",
						"Guide certifié, photo/vidéo",
					],
					waText: "Je veux réserver la plongée certifiée à Cabo Pulmo",
				},
				{
					name: "Baptême de plongée",
					amountMxn: 3800,
					amountNote: "/ personne",
					items: [
						"Pour débutants sans expérience",
						"Instruction théorique complète",
						"Pratique en eau peu profonde",
						"2 plongées supervisées par un instructeur",
					],
					waText: "Je veux réserver le Baptême à Cabo Pulmo",
					featured: true,
					featuredTag: "Sans certification",
				},
			],
			note: "Groupe privé ? Plongée privée à partir de 12 000 MXN (1-3 plongeurs, tarif fixe) plus un supplément par plongeur additionnel. Écrivez-nous pour organiser votre sortie.",
		},
		finalCta: {
			image: "/coral-reef-underwater-diving-cabo-pulmo-colorful-f.jpg",
			alt: "Récif de Cabo Pulmo",
			title: "Plongez dans le récif qui a repris vie",
			text: "25 000 ans de corail vous attendent dans le Parc National de Cabo Pulmo. Places limitées par départ.",
			waText: "Je veux réserver la plongée à Cabo Pulmo",
		},
	},

	"buceo-la-paz": {
		breadcrumb: "Plongée Île Espíritu Santo",
		hero: {
			image: "/scuba-diving-underwater-sea-lions-swimming-playful.jpg",
			alt: "Plongée avec les otaries à Los Islotes",
			kicker: "Archipel Espíritu Santo · Patrimoine mondial UNESCO",
			title: "Plongez avec des otaries curieuses",
			text: "Los Islotes abrite plus de 400 otaries qui jouent, tournoient et vous entourent sous l'eau. La combinaison de plongée et de faune la plus ludique de La Paz.",
		},
		quickFacts: [
			{ value: "7-8 heures", label: "Quai principal de La Paz" },
			{ value: "2-6 personnes", label: "Petits groupes" },
			{ value: "Toute l'année", label: "Saison" },
			{ value: "2-3 plongées", label: "Los Islotes et plus" },
		],
		story: {
			kicker: "Les chiots de la mer",
			title: "Elles aussi veulent jouer",
			paragraphs: [
				"Los Islotes, à l'extrémité nord de l'archipel Espíritu Santo, accueille une colonie de plus de 400 otaries extrêmement curieuses et joueuses avec les plongeurs. Elles vous entourent, font des pirouettes et créent des souvenirs qui restent gravés.",
				"Au-delà de la colonie, nous visitons d'autres sites de l'archipel aux formations rocheuses saisissantes, aux grottes sous-marines, aux épaves pleines de vie et à une diversité marine qui lui a valu le titre d'aquarium du monde.",
			],
			commitTitle: "Une rencontre responsable",
			commitText: "Nous plongeons avec des pratiques à faible impact et dans le respect de la colonie : ce sont elles qui décident de s'approcher — et elles le font presque toujours.",
		},
		split: {
			image: "/scuba-diving-underwater-la-paz-sea-lions-swimming.jpg",
			alt: "Otaries nageant avec des plongeurs",
			kicker: "Comment se déroule l'expérience",
			title: "Une journée complète de plongée dans la réserve",
			text: "Nous mettons les voiles depuis le quai principal de La Paz vers l'archipel. Deux à trois plongées guidées selon les conditions, avec déjeuner et boissons inclus — et des otaries pour compagnie.",
		},
		timeline: {
			kicker: "Itinéraire de la journée",
			title: "Étape par étape",
			items: [
				{ time: "Matin", title: "Départ de La Paz", text: "Rendez-vous au quai principal et navigation vers l'archipel Espíritu Santo." },
				{ time: "Los Islotes", title: "Plonger avec les otaries", text: "Une plongée guidée dans la colonie la plus célèbre du golfe de Californie." },
				{ time: "Surface", title: "Intervalle et déjeuner", text: "Repos, déjeuner et boissons à bord face aux paysages de la réserve." },
				{ time: "Plongée 2", title: "Épaves et grottes", text: "Une deuxième plongée sur des sites aux épaves, formations rocheuses et vie marine variée." },
				{ time: "Après-midi", title: "Retour à La Paz", text: "Retour au quai avec les photos et vidéos de votre journée." },
			],
		},
		fauna: {
			kicker: "Vie de l'archipel",
			title: "Ce qui vous attend sous l'eau",
			items: [
				{ image: "/sea-lions-swimming-underwater.jpg", alt: "Otaries sous l'eau", label: "Otaries · Toute l'année" },
				{ image: "/scuba-diving-underwater-la-paz-sea-lions-swimming.jpg", alt: "Plongée avec les otaries", label: "Los Islotes" },
				{ image: "/buceo-la-paz-buzo.jpg", alt: "Plongeur à La Paz", label: "Épaves et grottes" },
			],
		},
		includes: {
			kicker: "Votre expérience comprend",
			title: "Tout pour plonger dans l'aquarium du monde",
			items: [
				{ title: "Transport en panga", text: "Départ et retour depuis le quai principal de La Paz." },
				{ title: "2-3 plongées", text: "Guidées par un dive master certifié sur les meilleurs sites de l'archipel." },
				{ title: "Équipement complet", text: "Équipement de plongée complet inclus dans l'option avec équipement." },
				{ title: "Déjeuner et boissons", text: "Repas et boissons à bord tout au long de la sortie." },
				{ title: "Photo et vidéo inclus", text: "Des clichés sous-marins de votre expérience." },
			],
		},
		pricing: {
			kicker: "Options de plongée",
			title: "Choisissez votre expérience à Espíritu Santo",
			cards: [
				{
					name: "Plongeurs certifiés",
					amountMxn: 3700,
					amountNote: "/ personne",
					items: [
						"2-3 plongées dans l'archipel",
						"Dive master certifié",
						"Déjeuner et boissons inclus",
						"Photo et vidéo inclus",
					],
					waText: "Je veux réserver la plongée certifiée à l'Île Espíritu Santo",
				},
				{
					name: "Baptême de plongée",
					amountMxn: 4200,
					amountNote: "/ personne",
					items: [
						"Pour débutants sans expérience",
						"Instruction théorique complète",
						"Pratique en eau peu profonde",
						"Plongées supervisées par un instructeur",
					],
					waText: "Je veux réserver le Baptême à l'Île Espíritu Santo",
					featured: true,
					featuredTag: "Sans certification",
				},
			],
			note: "Également disponible pour les adeptes du snorkeling : aucune certification n'est requise pour le snorkeling avec les otaries.",
		},
		finalCta: {
			image: "/scuba-diving-underwater-sea-lions-swimming-playful.jpg",
			alt: "Otaries joueuses",
			title: "Nagez avec les chiots de la mer",
			text: "Une expérience que vous n'oublierez jamais, dans un site du patrimoine mondial de l'UNESCO. Réservez votre plongée dès aujourd'hui.",
			waText: "Je veux réserver la plongée à l'Île Espíritu Santo",
		},
	},

	"scuba-discovery": {
		breadcrumb: "Baptême de Plongée depuis la Plage",
		hero: {
			image: "/snorkeling-coral-reef.jpg",
			alt: "Baptême de plongée depuis la plage à La Paz",
			kicker: "La Paz · Depuis la plage",
			title: "Votre première respiration sous l'eau",
			text: "Sans certification, sans expérience préalable, sans bateau : vous entrez à pied depuis la plage avec un instructeur à vos côtés en permanence. Profondeur maximale 6 mètres.",
		},
		quickFacts: [
			{ value: "Demi-journée", label: "Plage à La Paz" },
			{ value: "1-6 personnes", label: "Par instructeur" },
			{ value: "Toute l'année", label: "Saison" },
			{ value: "Max 6 m", label: "Profondeur" },
		],
		story: {
			kicker: "Pour débutants",
			title: "La plongée, sans barrières",
			paragraphs: [
				"Le Baptême de plongée est la façon la plus accessible d'essayer la plongée : vous entrez dans l'eau à pied depuis la plage, pratiquez les compétences de base en eau peu profonde et explorez les fonds marins à une profondeur maximale de 6 mètres.",
				"Aucune certification ni expérience préalable requise — juste l'envie de découvrir la mer de Cortez d'en bas. Un instructeur certifié vous accompagne en permanence, de la théorie à la dernière bulle.",
			],
			commitTitle: "Votre premier pas",
			commitText: "Si vous tombez amoureux de la plongée, cette expérience est le premier pas vers votre certification Open Water. Convient aux débutants dès l'âge de 10 ans.",
		},
		split: {
			image: "/snorkeling-crystal-clear-water.jpg",
			alt: "Eaux cristallines à La Paz",
			kicker: "Comment se déroule l'expérience",
			title: "Du briefing aux bulles",
			text: "Nous commençons sur la plage par une simple introduction théorique, pratiquons les compétences de base là où vous avez pied, et lorsque vous êtes prêt, nous explorons le récif côtier, accompagnés en permanence. Photos incluses.",
		},
		timeline: {
			kicker: "Itinéraire",
			title: "Étape par étape",
			items: [
				{ time: "Accueil", title: "Briefing sur la plage", text: "Une simple introduction théorique : le matériel, la respiration et les signaux de base." },
				{ time: "Eau peu profonde", title: "Pratique des compétences", text: "Exercices de base dans l'eau là où vous avez pied, à votre rythme et sans pression." },
				{ time: "La plongée", title: "Exploration guidée", text: "Une plongée guidée à une profondeur maximale de 6 mètres le long du récif côtier." },
				{ time: "Conclusion", title: "Photos et prochaine étape", text: "Vous recevez les photos de votre expérience et, si vous en voulez plus, nous vous expliquons comment vous certifier." },
			],
		},
		includes: {
			kicker: "Votre expérience comprend",
			title: "Tout pour votre première fois sous l'eau",
			items: [
				{ title: "Instructeur certifié", text: "Accompagnement individuel tout au long de l'expérience." },
				{ title: "Équipement complet", text: "Tout l'équipement de plongée inclus, ajusté à votre taille." },
				{ title: "Pratique en eau peu profonde", text: "Briefing et exercices là où vous avez pied, sans précipitation." },
				{ title: "Photos incluses", text: "Des clichés de votre première respiration sous l'eau." },
			],
		},
		pricing: {
			kicker: "Prix",
			title: "Réservez votre Baptême de plongée",
			cards: [
				{
					name: "Par personne",
					amountMxn: 1500,
					amountNote: "/ personne",
					items: [
						"Aucune expérience préalable requise",
						"Instructeur certifié en permanence",
						"Équipement complet inclus",
						"Profondeur maximale de 6 mètres",
						"Photos incluses",
					],
					waText: "Je veux réserver le Baptême de Plongée depuis la Plage",
				},
				{
					name: "Groupe privé",
					amountText: "Sur devis",
					amountNote: "jusqu'à 6 personnes",
					items: [
						"Un instructeur exclusivement pour votre groupe",
						"Horaire flexible",
						"Même équipement et itinéraire",
						"Idéal pour les familles et les amis",
					],
					waText: "Je veux un devis pour un Baptême de plongée privé",
					featured: true,
					featuredTag: "Nouveau",
				},
			],
			note: "Convient aux débutants dès l'âge de 10 ans. Si vous poursuivez vers la certification, cette expérience compte comme votre premier contact avec la plongée.",
		},
		finalCta: {
			image: "/snorkeling-crystal-clear-water.jpg",
			alt: "Eaux cristallines de la mer de Cortez",
			title: "Respirez sous l'eau pour la première fois",
			text: "Sans certification, sans expérience, sans excuses. La mer de Cortez vous attend, à 6 mètres de profondeur.",
			waText: "Je veux réserver le Baptême de Plongée depuis la Plage",
		},
	},
}
