import type { ExpeditionPageData } from "@/components/ExpeditionDetail"

/** 探险详情页面的中文内容。 */
export const expeditionPagesZh: Record<string, ExpeditionPageData> = {
	"safari-la-ventana": {
		breadcrumb: "拉文塔纳海洋探险",
		hero: {
			image: "/images/orca-safari.jpg",
			alt: "下加利福尼亚州拉文塔纳的海上探险",
			kicker: "拉文塔纳 · 塞拉尔沃岛",
			title: "邂逅非凡",
			text: "探索加利福尼亚湾最令人惊叹的海洋场景之一。每次出海都不同，每次相遇都真实。",
		},
		quickFacts: [
			{ value: "6小时", label: "上午8:00出发" },
			{ value: "2-8人", label: "拼团或包船" },
			{ value: "4-6月", label: "蝠鲼季" },
			{ value: "40分钟", label: "距拉巴斯" },
		],
		story: {
			kicker: "什么是海上探险",
			title: "没有剧本，没有表演。",
			paragraphs: [
				"探险从距拉巴斯40分钟的拉文塔纳开始，我们驶向深蓝。在海洋生物学家和当地船长的带领下，我们航行去寻找意料之外的相遇：飞翔的蝠鲼、护送我们的海豚、如活的传奇般跃出水面的鲸鱼。",
				"与一切都预先安排好的传统旅行不同，这次探险被设计成一场动态而真实的体验，专注于最大限度地与野生动物相遇。每次出海都独一无二——因为我们面对的是自由的野生动物：我们不保证特定的目击，但我们保证投入、经验和尊重自然的态度。",
			],
			commitTitle: "我们的承诺",
			commitText: "我们深深尊重海洋生命。我们的探险旨在观察而不打扰、学习而不干预、赞叹而不损害接纳我们的生态系统。",
		},
		split: {
			image: "/images/safari/nuestrocompromiso2.jpeg",
			alt: "拉文塔纳海上探险中携带浮潜装备的向导",
			kicker: "体验如何进行",
			title: "为相遇而设计的一整天",
			text: "航行寻找海洋生物，条件允许时浮潜，并探索塞拉尔沃岛——全程由海洋生物学家带领，他们实时解读动物行为和大海的信号。我们以新鲜的酸橘汁腌鱼和时令水果面朝大海结束这一天。",
		},
		timeline: {
			kicker: "详细行程",
			title: "逐时安排",
			items: [
				{ time: "上午8:00", title: "欢迎与讲解", text: "认识你的海洋生物学家向导，了解你可能遇到的海洋生物。" },
				{ time: "上午8:30 - 11:30", title: "航行与寻找", text: "我们循着动物的行为规律和自然信号，航行寻找海洋生物。" },
				{ time: "上午11:30 - 下午1:00", title: "探索塞拉尔沃岛", text: "视条件而定，在岛屿周围清澈的海水中浮潜或探索。" },
				{ time: "下午1:00 - 1:30", title: "点心与休息", text: "在休息时享用新鲜的酸橘汁腌鱼和时令水果。" },
				{ time: "下午1:30 - 2:00", title: "风景返程", text: "我们驶回拉文塔纳，途中可能有更多目击。" },
			],
		},
		fauna: {
			kicker: "各季节的野生动物",
			title: "加利福尼亚湾是地球上生物多样性最丰富的海域之一",
			items: [
				{ image: "/images/especies/mobulaschafa.jpeg", alt: "蝠鲼", label: "蝠鲼 · 4-6月" },
				{ image: "/images/especies/delfinsaltando.jpeg", alt: "跃起的海豚", label: "海豚 · 全年" },
				{ image: "/images/especies/ballenasaltando2.jpeg", alt: "座头鲸", label: "座头鲸 · 12-4月" },
				{ image: "/images/especies/lobomarinonadando.jpeg", alt: "海狮", label: "海狮 · 全年" },
				{ image: "/images/especies/cachalote2.jpeg", alt: "抹香鲸", label: "抹香鲸 · 6-11月" },
				{ image: "/images/especies/orcalaventana.jpeg", alt: "虎鲸", label: "虎鲸 · 不定期" },
			],
		},
		includes: {
			kicker: "你的体验包含",
			title: "尽情享受海上探险所需的一切",
			items: [
				{ title: "6小时海洋探险", text: "在熟悉这片海域的海洋生物学家和当地船长带领下航行寻找海洋生物。" },
				{ title: "全套装备", text: "全程含潜水衣、浮潜装备和沙滩用具。" },
				{ title: "塞拉尔沃岛野餐", text: "面朝大海享用新鲜酸橘汁腌鱼、时令水果、小吃和饮品。" },
				{ title: "含照片和视频", text: "专业记录你的体验，随时重温这一刻。" },
			],
		},
		pricing: {
			kicker: "价格",
			title: "预订你的拉文塔纳海上探险",
			cards: [
				{
					name: "拼团",
					amountMxn: 3000,
					amountNote: "/ 每人",
					items: [
						"最少4人成行",
						"拼船，最多8-10人",
						"潜水衣、浮潜装备和沙滩用具",
						"塞拉尔沃岛野餐",
						"海洋生物学家向导，含照片/视频",
					],
					waText: "我想预订拼团拉文塔纳海洋探险",
				},
				{
					name: "包船",
					amountMxn: 16000,
					amountNote: "/ 最多8人",
					items: [
						"专属于你团体的船只",
						"当天时间灵活",
						"相同行程与含装备",
						"海洋生物学家向导，含照片/视频",
					],
					waText: "我想预订包船拉文塔纳海洋探险",
					featured: true,
					featuredTag: "包船",
				},
			],
			note: "建议会游泳者参加；儿童须在成人监护下同行。蝠鲼季（4-6月）名额有限。",
		},
		finalCta: {
			image: "/images/orca-safari.jpg",
			alt: "在拉文塔纳跃起的蝠鲼",
			title: "飞翔的蝠鲼，跃出的鲸鱼",
			text: "在距拉巴斯40分钟的地方，体验一场没有剧本的探险。每次出海名额有限。",
			waText: "我想预订拉文塔纳海洋探险",
		},
	},

	"tiburon-ballena": {
		breadcrumb: "鲸鲨",
		hero: {
			image: "/snorkeling-coral-reef.jpg",
			alt: "在拉巴斯与鲸鲨同游",
			kicker: "拉巴斯 · 11-3月",
			title: "与世界上最大的鱼同游",
			text: "与鲸鲨同游是下加利福尼亚州拉巴斯最具标志性的海洋体验之一。平静的海水，负责任且受规范管理的相遇。",
		},
		quickFacts: [
			{ value: "2小时", label: "拉巴斯主码头" },
			{ value: "11-3月", label: "官方季节" },
			{ value: "受规范管理", label: "官方区域与许可" },
			{ value: "各年龄", label: "适合所有人" },
		],
		story: {
			kicker: "与世界上最大的鱼同游",
			title: "温和的巨兽，在它的季节",
			paragraphs: [
				"每个季节，这些海中巨兽都会来到海湾平静的水域，创造了以负责任的方式观察它们并与它们同游的独特机会——始终遵循官方规定，并由获授权的运营方带领。",
				"我们的专业向导会全程陪伴你，分享关于这一物种、其生态重要性以及如何以尊重和意识去享受这次相遇的知识。",
			],
			commitTitle: "受规范管理的活动",
			commitText: "在拉巴斯，进入同游与观赏区域受到规范管理。只有持有效许可的船只才能进入，并须遵守当局为保护该物种而授权的轮次和时间。",
		},
		split: {
			image: "/manta-ray-swimming.png",
			alt: "加利福尼亚湾的海洋生物",
			kicker: "你还能看到什么",
			title: "加利福尼亚湾从不休息",
			text: "在前往观赏区的途中，常会遇到好奇的海狮和靠近船只的海豚——被雅克·库斯托称为「世界的水族馆」的科尔特斯海，总有值得一看的景象。",
		},
		timeline: {
			kicker: "当天行程",
			title: "逐步安排",
			items: [
				{ time: "主码头", title: "欢迎与讲解", text: "在拉巴斯主码头集合。介绍体验、装备使用以及负责任活动的规则。" },
				{ time: "航行", title: "搜寻与定位", text: "我们在许可区域内航行，遵循当局制定的规程，尊重授权的轮次和时间。" },
				{ time: "下水", title: "与鲸鲨同游", text: "在持证向导的全程陪伴下，与世界上最大的鱼进行一次有向导、负责任的相遇。" },
				{ time: "返程", title: "回到拉巴斯", text: "我们带着你相遇的照片和视频返回码头。" },
			],
		},
		includes: {
			kicker: "你的体验包含",
			title: "安全而负责任相遇所需的一切",
			items: [
				{ title: "乘船交通", text: "从拉巴斯主码头往返。" },
				{ title: "持证向导", text: "分享该物种知识的专业双语团队。" },
				{ title: "浮潜装备", text: "面镜、脚蹼和救生衣，让你安心探索。" },
				{ title: "照片和视频", text: "捕捉当下瞬间，留下你冒险的真实回忆。" },
				{ title: "规范许可", text: "获授权进入官方观赏区。" },
			],
		},
		pricing: {
			kicker: "价格",
			title: "预订你的鲸鲨同游",
			cards: [
				{
					name: "拼团行程",
					amountMxn: 1800,
					amountNote: "/ 每人",
					items: [
						"拼乘小艇交通",
						"持证向导陪伴",
						"含浮潜装备",
						"你冒险的照片和视频",
						"规范区域许可",
					],
					waText: "我想预订鲸鲨行程",
				},
			],
			note: "官方季节：11月至3月，其中12月至2月为旺季。适合所有年龄——未成年人须在成人监护下参加。",
		},
		finalCta: {
			image: "/manta-ray-swimming.png",
			alt: "下加利福尼亚州拉巴斯的海洋生物",
			title: "准备好与世界上最大的鱼同游了吗？",
			text: "鲸鲨在拉巴斯的海域等你。一次独特、负责任且难忘的体验。",
			waText: "我想预订鲸鲨行程",
		},
	},

	"safari-bahia-magdalena": {
		breadcrumb: "马格达莱纳湾探险",
		hero: {
			image: "/images/marlin-bahia-magdalena-hero.jpeg",
			alt: "在马格达莱纳湾捕猎沙丁鱼的马林鱼",
			kicker: "马格达莱纳湾 · 11-12月",
			title: "太平洋最狂野的探险",
			text: "成千上万的沙丁鱼、全速捕猎的马林鱼、觅食的鲸鱼。一年仅两个月的自然奇观——而你可以身临其境。",
		},
		quickFacts: [
			{ value: "全天", label: "上午5:00出发" },
			{ value: "2-6人", label: "小团体" },
			{ value: "11-12月", label: "沙丁鱼洄游" },
			{ value: "开阔海域", label: "墨西哥太平洋" },
		],
		story: {
			kicker: "什么是沙丁鱼洄游",
			title: "短暂却震撼的盛事",
			paragraphs: [
				"每年11月和12月，大自然最狂野的现象之一在此上演：马格达莱纳湾的水域成为海洋生命的中心。成千上万的沙丁鱼聚成巨大的鱼球洄游，吸引马林鱼、鲯鳅、海狮甚至鲸鱼等顶级掠食者。",
				"这不是一次普通旅行，而是每位海洋爱好者的必体验。你将从半岛最原始的地点之一驶向大海，在海洋生物学家的带领下，成为墨西哥太平洋最激烈景象之一的一部分。条件允许时，你会潜入行动的核心，漂浮在一个流动的生态系统之上。",
			],
			commitTitle: "自由的野生动物",
			commitText: "我们面对的是自然中自由的动物：我们不保证特定的目击，但我们保证投入、经验以及对接纳我们的生态系统的尊重。",
		},
		split: {
			image: "/images/gallery/marlin-cazando.jpeg",
			alt: "捕猎沙丁鱼球的条纹马林鱼",
			kicker: "体验如何进行",
			title: "在开阔海域度过一整天",
			text: "我们在黎明离开拉巴斯，驶向太平洋。航行寻找沙丁鱼球及其掠食者，行动允许时可下水。漫长、激烈、绝对难忘的一天。",
		},
		timeline: {
			kicker: "探险行程",
			title: "逐步安排",
			items: [
				{ time: "上午5:00", title: "从拉巴斯出发", text: "我们驶向太平洋海岸，进入马格达莱纳湾的门户。" },
				{ time: "上午7:30", title: "驶向大海", text: "与你的海洋生物学家向导进行讲解，随后乘船驶入开阔海域。" },
				{ time: "上午8:00 - 下午2:00", title: "开阔海域探险", text: "航行寻找沙丁鱼球及其掠食者：马林鱼、鲯鳅、海狮和鲸鱼。条件允许时浮潜。" },
				{ time: "下午2:30", title: "海边午餐", text: "含午餐，在激烈体验后补充能量。" },
				{ time: "下午", title: "返回拉巴斯", text: "我们穿越下加利福尼亚沙漠返回，满载而归，带着你冒险的照片。" },
			],
		},
		fauna: {
			kicker: "季节野生动物",
			title: "沙丁鱼洄游的主角",
			items: [
				{ image: "/images/especies/sardinas-banco.jpeg", alt: "沙丁鱼球", label: "沙丁鱼 · 11-12月" },
				{ image: "/striped-marlin-underwater.jpg", alt: "条纹马林鱼", label: "条纹马林鱼 · 11-12月" },
				{ image: "/images/especies/dorado.jpeg", alt: "鲯鳅", label: "鲯鳅 · 11-12月" },
				{ image: "/images/especies/lobomarinonadando.jpeg", alt: "海狮", label: "海狮 · 全年" },
				{ image: "/images/especies/ballenasaltando2.jpeg", alt: "鲸鱼", label: "鲸鱼 · 11-12月" },
				{ image: "/images/especies/delfinsaltando.jpeg", alt: "海豚", label: "海豚 · 全年" },
			],
		},
		includes: {
			kicker: "你的体验包含",
			title: "最狂野探险所需的一切",
			items: [
				{ title: "全天探险", text: "在海洋生物学家和当地船长带领下于开阔海域航行。" },
				{ title: "浮潜装备", text: "面镜、脚蹼和潜水衣，行动允许时可下水。" },
				{ title: "午餐和饮品", text: "含餐食和饮品，供一整天的探险。" },
				{ title: "含照片和视频", text: "专业记录你的体验，随时重温这一刻。" },
			],
		},
		pricing: {
			kicker: "价格",
			title: "预订你的沙丁鱼洄游名额",
			cards: [
				{
					name: "拼团",
					amountMxn: 3500,
					amountNote: "/ 每人",
					items: [
						"拼船，2-6人",
						"拉巴斯出发交通",
						"含浮潜装备",
						"午餐和饮品",
						"海洋生物学家向导，含照片/视频",
					],
					waText: "我想预订马格达莱纳湾探险",
				},
				{
					name: "包船",
					amountText: "询价",
					amountNote: "为你的团体",
					items: [
						"专属于你团体的船只",
						"当天时间灵活",
						"相同行程与含装备",
						"海洋生物学家向导，含照片/视频",
					],
					waText: "我想咨询包船马格达莱纳湾探险的报价",
					featured: true,
					featuredTag: "包船",
				},
			],
			note: "季节性奇观：仅限11月和12月。每次出海名额非常有限——请尽早预订。",
		},
		finalCta: {
			image: "/images/marlin-bahia-magdalena-hero.jpeg",
			alt: "在马格达莱纳湾捕猎的马林鱼",
			title: "一年仅两个月",
			text: "太平洋最狂野的探险在马格达莱纳湾等你。每季名额有限。",
			waText: "我想预订马格达莱纳湾探险",
		},
	},

	"tour-ballena-gris": {
		breadcrumb: "灰鲸查莱港",
		hero: {
			image: "/images/hero/ballena-gris-hero.jpeg",
			alt: "马格达莱纳湾查莱港的灰鲸",
			kicker: "查莱港 · 1-3月",
			title: "一场远古的相遇",
			text: "每年冬天，成千上万的灰鲸从北极迁徙到这片宁静的潟湖，产崽和繁育。你即将走进这片圣地。",
		},
		quickFacts: [
			{ value: "9小时", label: "上午5:00拉巴斯接送" },
			{ value: "最多8人", label: "每船" },
			{ value: "1-3月", label: "官方季节" },
			{ value: "2-3小时", label: "海上与鲸鱼同行" },
		],
		story: {
			kicker: "这不是一次普通旅行",
			title: "这是一种荣幸",
			paragraphs: [
				"每年冬天，墨西哥太平洋都会发生某种神圣的事。成千上万的灰鲸从北极跋涉超过20,000公里，来到沙漠中央一片宁静的潟湖……产崽、繁育，只为存在于此。",
				"它们以好奇和对船只的友好接近而闻名：母鲸与幼鲸会靠近到一桨之遥。这是一份一年仅存在数月的大自然馈赠——而你将从下加利福尼亚的腹地亲历它。",
			],
			commitTitle: "负责任的观赏",
			commitText: "我们与获授权的当地运营方一同航行，尊重距离、时间和动物的行为。是它们决定靠近——我们只是在那里。",
		},
		split: {
			image: "/gray-whale-close-up-magdalena-bay.jpg",
			alt: "马格达莱纳湾近距离的灰鲸",
			kicker: "体验如何进行",
			title: "通往奇迹之路",
			text: "冒险很早开始：我们在拉巴斯接你，在朝阳中穿越巨大仙人掌林立的下加利福尼亚沙漠。抵达查莱港时，你的船已在等候——空气中弥漫着大海、红树林和历史的气息。",
		},
		timeline: {
			kicker: "当天行程",
			title: "逐步安排",
			items: [
				{ time: "上午5:00", title: "黎明出发", text: "我们在你位于拉巴斯的酒店或民宿接你，驶向太平洋。" },
				{ time: "2.5小时", title: "通往太平洋之路", text: "穿越下加利福尼亚沙漠景观，前往查莱港，你的船已在那里等候。" },
				{ time: "2-3小时", title: "与鲸鱼相遇", text: "我们在潟湖内航行，这里是这些巨兽的临时家园。它们在此繁育、幼崽在此出生、在动物界最长的迁徙之后在此休憩。" },
				{ time: "中午", title: "当地午餐", text: "在查莱港享用由当地社区准备的午餐。" },
				{ time: "下午", title: "返回拉巴斯", text: "我们满心欢喜、带着相遇的照片穿越沙漠返回。" },
			],
		},
		fauna: {
			kicker: "圣地的野生动物",
			title: "生机勃勃的潟湖",
			items: [
				{ image: "/images/especies/ballena-gris-real.jpeg", alt: "灰鲸", label: "灰鲸 · 1-3月" },
				{ image: "/gray-whale-mother-and-calf-swimming-together-in-ba.jpg", alt: "灰鲸母鲸与幼鲸", label: "母鲸与幼鲸 · 1-3月" },
				{ image: "/images/especies/delfinsaltando.jpeg", alt: "海豚", label: "海豚 · 全年" },
				{ image: "/images/especies/lobomarinonadando.jpeg", alt: "海狮", label: "海狮 · 全年" },
				{ image: "/brown-pelicans-flying-over-ocean-in-baja-californi.jpg", alt: "鹈鹕", label: "海鸟 · 全年" },
				{ image: "/magnificent-frigatebird-soaring-over-ocean-in-baja.jpg", alt: "军舰鸟", label: "军舰鸟 · 全年" },
			],
		},
		includes: {
			kicker: "你的体验包含",
			title: "难忘相遇所需的一切",
			items: [
				{ title: "往返交通", text: "在你位于拉巴斯的酒店或民宿接送，往返查莱港。" },
				{ title: "官方许可船只", text: "在获授权的当地运营方带领下于潟湖内航行。" },
				{ title: "海洋生物学家向导", text: "全程讲解动物行为。" },
				{ title: "当地午餐", text: "在查莱港享用由社区准备的午餐。" },
				{ title: "含照片和视频", text: "专业记录你的相遇，随时重温这一刻。" },
			],
		},
		pricing: {
			kicker: "行程选项",
			title: "预订你与灰鲸的相遇",
			cards: [
				{
					name: "拼团 · 海上2小时",
					amountMxn: 2800,
					amountNote: "/ 每人",
					items: [
						"拉巴斯往返交通",
						"2小时与鲸鱼同航",
						"海洋生物学家向导",
						"含当地午餐",
						"含照片和视频",
					],
					waText: "我想预订拼团灰鲸查莱港行程",
				},
				{
					name: "拼团 · 海上3小时",
					amountMxn: 3000,
					amountNote: "/ 每人",
					items: [
						"拉巴斯往返交通",
						"3小时与鲸鱼同航",
						"海洋生物学家向导",
						"含当地午餐",
						"含照片和视频",
					],
					waText: "我想预订3小时灰鲸查莱港行程",
					featured: true,
					featuredTag: "更长时间",
				},
			],
			note: "团体出行？高端包船14,000墨西哥比索（最多6人，海上3小时）。官方季节：仅限1月至3月。",
		},
		finalCta: {
			image: "/gray-whale-breaching-sunset-sea-of-cortez.jpg",
			alt: "夕阳下跃出水面的灰鲸",
			title: "一年仅存在数月",
			text: "灰鲸母鲸与幼鲸在查莱港等你。预订你在这片圣地的名额。",
			waText: "我想预订灰鲸查莱港行程",
		},
	},

	"tour-espiritu-santo": {
		breadcrumb: "圣灵岛浮潜之旅",
		hero: {
			image: "/espiritu-santo-island-paradise-beach.jpg",
			alt: "圣灵岛的天堂海滩",
			kicker: "圣灵岛 · 联合国教科文组织世界遗产",
			title: "与好奇的海狮同游",
			text: "原始的海滩、清澈的海水，以及加利福尼亚湾最大的海狮群之一。世界的水族馆，距拉巴斯一次船程。",
		},
		quickFacts: [
			{ value: "6小时", label: "拉巴斯主码头" },
			{ value: "2-10人", label: "小团体" },
			{ value: "全年", label: "季节" },
			{ value: "UNESCO", label: "生物圈保护区" },
		],
		story: {
			kicker: "加利福尼亚湾的瑰宝",
			title: "世界的水族馆",
			paragraphs: [
				"圣灵岛是加利福尼亚湾最大的海狮群之一的家园。在这里，你将在清澈的海水中、于独特的自然环境里，与这些动物进行一次负责任、有向导的相遇。",
				"我们的专业向导会全程陪伴你，分享关于自然史、海洋保育以及如何尊重地与野生动物互动的知识。",
			],
			commitTitle: "繁育季",
			commitText: "6月1日至8月31日为繁育季，不允许与海狮同游；为了幼崽的安全，体验将改为在船上观赏。",
		},
		split: {
			image: "/picnic-beach-espiritu-santo.jpg",
			alt: "圣灵岛某处海滩上的野餐",
			kicker: "体验如何进行",
			title: "浮潜、原始海滩与野餐",
			text: "在洛斯伊斯洛特斯同游之后，我们驶向群岛的一处海滩：浅色沙滩、碧蓝海水和令人惊叹的岩石地貌。自由时间可游泳、散步或只是静静待着——面朝大海，含野餐。",
		},
		timeline: {
			kicker: "当天行程",
			title: "逐步安排",
			items: [
				{ time: "上午", title: "从拉巴斯出发", text: "在主码头集合，伴着朝阳启航，向北穿越加利福尼亚湾。" },
				{ time: "洛斯伊斯洛特斯", title: "与海狮同游", text: "与海湾最大的海狮群之一进行一次尊重、有向导的相遇。含装备，全程水中陪伴。" },
				{ time: "中午", title: "群岛海滩", text: "在群岛一处原始海滩停留：浅色沙滩、碧蓝海水和自由探索的时间。" },
				{ time: "午餐", title: "海边野餐", text: "在海滩上享用含野餐，四周环绕着保护区的景色。" },
				{ time: "下午", title: "风景返程", text: "我们驶回拉巴斯，途中可能有目击。" },
			],
		},
		fauna: {
			kicker: "保护区的野生动物",
			title: "目之所及皆是生命",
			items: [
				{ image: "/swimming-with-sea-lions.jpg", alt: "与海狮同游", label: "海狮 · 全年" },
				{ image: "/sea-lions-resting-on-rocks-in-baja-california-sur.jpg", alt: "岩石上的海狮", label: "洛斯伊斯洛特斯栖息地" },
				{ image: "/pristine-beach-turquoise-water-espiritu-santo-isla.jpg", alt: "原始海滩", label: "原始海滩" },
				{ image: "/snorkeling-crystal-clear-water.jpg", alt: "浮潜", label: "珊瑚礁与鱼群" },
				{ image: "/brown-pelicans-flying-over-ocean-in-baja-californi.jpg", alt: "鹈鹕", label: "海鸟" },
				{ image: "/images/especies/delfinsaltando.jpeg", alt: "海豚", label: "海豚 · 全年" },
			],
		},
		includes: {
			kicker: "你的体验包含",
			title: "在天堂度过一整天所需的一切",
			items: [
				{ title: "航行穿越保护区", text: "从拉巴斯主码头往返。" },
				{ title: "与海狮同游", text: "在洛斯伊斯洛特斯的有向导相遇，含浮潜装备。" },
				{ title: "海滩野餐", text: "在群岛海滩面朝大海享用餐食和饮品。" },
				{ title: "含照片和视频", text: "专业记录你的体验，随时重温这一刻。" },
			],
		},
		pricing: {
			kicker: "价格",
			title: "预订你在圣灵岛的一天",
			cards: [
				{
					name: "拼团",
					amountMxn: 1800,
					amountNote: "/ 每人",
					items: [
						"拼船，2-10人",
						"在洛斯伊斯洛特斯与海狮同游",
						"含浮潜装备",
						"海滩野餐",
						"向导，含照片/视频",
					],
					waText: "我想预订圣灵岛",
				},
				{
					name: "包船",
					amountText: "询价",
					amountNote: "为你的团体",
					items: [
						"专属于你团体的船只",
						"当天时间灵活",
						"相同行程与含装备",
						"向导，含照片/视频",
					],
					waText: "我想咨询包船圣灵岛的报价",
					featured: true,
					featuredTag: "包船",
				},
			],
			note: "6月1日至8月31日，与海狮同游改为在船上观赏（繁育季）。",
		},
		finalCta: {
			image: "/espiritu-santo-island-paradise-beach.jpg",
			alt: "圣灵岛",
			title: "天堂距拉巴斯一次船程",
			text: "顽皮的海狮、原始的海滩，以及世界水族馆的湛蓝。预订你的名额。",
			waText: "我想预订圣灵岛",
		},
	},

	"buceo-cabo-pulmo": {
		breadcrumb: "卡波普尔莫潜水",
		hero: {
			image: "/coral-reef-underwater-diving-cabo-pulmo-colorful-f.jpg",
			alt: "卡波普尔莫的珊瑚礁",
			kicker: "卡波普尔莫 · 国家公园",
			title: "海湾唯一的活珊瑚礁",
			text: "25,000年的珊瑚、公牛鲨、庞大的鱼群。在世界上最成功的海洋保护区之一潜水。",
		},
		quickFacts: [
			{ value: "全天", label: "从拉巴斯出发" },
			{ value: "2-6人", label: "小团体" },
			{ value: "全年", label: "季节" },
			{ value: "2次潜水", label: "国家公园" },
		],
		story: {
			kicker: "卡波普尔莫国家公园",
			title: "重获新生的保护区",
			paragraphs: [
				"卡波普尔莫是加利福尼亚湾唯一的活珊瑚礁，已有超过25,000年历史。经过数十年由社区主导的保护，其生物量以地球上绝无仅有的方式恢复：如今它是世界上最伟大的保育成功案例之一。",
				"在这里潜水，就是走进一片鱼云：庞大的鲹鱼群、公牛鲨、巨型石斑鱼、海龟，以及——运气好的话——著名的鲹鱼龙卷风。每次潜水都由对公园了如指掌的持证教练带领。",
			],
			commitTitle: "受保护的国家公园",
			commitText: "卡波普尔莫是受保护的自然区域：小团体、低影响的做法，以及每次潜水对珊瑚礁的绝对尊重。",
		},
		split: {
			image: "/buceo-cabo-pulmo-cardumen.jpg",
			alt: "卡波普尔莫庞大的鱼群",
			kicker: "体验如何进行",
			title: "在珊瑚礁上的两次潜水",
			text: "我们一早离开拉巴斯前往国家公园。视当天条件在珊瑚礁最佳潜点进行两次有向导潜水，含水面间歇、小吃，并安排好全部后勤。",
		},
		timeline: {
			kicker: "当天行程",
			title: "逐步安排",
			items: [
				{ time: "清晨", title: "从拉巴斯出发", text: "驾车前往海湾东岸的卡波普尔莫。" },
				{ time: "抵达", title: "讲解与装备", text: "装备准备、潜点讲解和国家公园规则。" },
				{ time: "第1潜", title: "首次珊瑚礁潜水", text: "在公园标志性潜点之一进行一次有向导潜水。" },
				{ time: "水面", title: "间歇与小吃", text: "在船上休息，享用水、水果和饼干。" },
				{ time: "第2潜", title: "第二次潜水", text: "视条件在珊瑚礁另一处进行第二次潜水。" },
				{ time: "下午", title: "返回拉巴斯", text: "我们带着你在公园这一天的照片和视频返回。" },
			],
		},
		fauna: {
			kicker: "珊瑚礁生命",
			title: "你能在公园里发现什么",
			items: [
				{ image: "/coral-reef-underwater-cabo-pulmo-colorful-tropical.jpg", alt: "珊瑚礁", label: "珊瑚 · 25,000年" },
				{ image: "/buceo-cabo-pulmo-cardumen.jpg", alt: "鱼群", label: "庞大鱼群" },
				{ image: "/buceo-cabo-pulmo-buzo.jpg", alt: "卡波普尔莫的潜水员", label: "公牛鲨与石斑鱼" },
			],
		},
		includes: {
			kicker: "你的体验包含",
			title: "在公园潜水所需的一切",
			items: [
				{ title: "2次有向导潜水", text: "视当天条件在珊瑚礁最佳潜点。" },
				{ title: "持证向导", text: "在国家公园经验丰富的教练。" },
				{ title: "水和小吃", text: "全程船上提供饮水、水果和饼干。" },
				{ title: "含照片和视频", text: "专业水下记录你的体验。" },
			],
		},
		pricing: {
			kicker: "潜水选项",
			title: "选择你的卡波普尔莫体验",
			cards: [
				{
					name: "持证潜水员",
					amountMxn: 3200,
					amountNote: "/ 每人（自带装备）",
					items: [
						"2次拼团潜水",
						"含全套装备3,400墨西哥比索",
						"最多6人成团",
						"船上提供水和饼干",
						"持证向导，含照片/视频",
					],
					waText: "我想预订卡波普尔莫持证潜水",
				},
				{
					name: "体验潜水",
					amountMxn: 3800,
					amountNote: "/ 每人",
					items: [
						"适合无经验的初学者",
						"完整理论讲解",
						"浅水练习",
						"2次教练监督下的潜水",
					],
					waText: "我想预订卡波普尔莫体验潜水",
					featured: true,
					featuredTag: "无需证书",
				},
			],
			note: "私人团体？私人潜水12,000墨西哥比索起（1-3名潜水员，固定价），每增加一名潜水员另加费用。请联系我们安排你的行程。",
		},
		finalCta: {
			image: "/coral-reef-underwater-diving-cabo-pulmo-colorful-f.jpg",
			alt: "卡波普尔莫珊瑚礁",
			title: "潜入重获新生的珊瑚礁",
			text: "25,000年的珊瑚在卡波普尔莫国家公园等你。每次出海名额有限。",
			waText: "我想预订卡波普尔莫潜水",
		},
	},

	"buceo-la-paz": {
		breadcrumb: "圣灵岛潜水",
		hero: {
			image: "/scuba-diving-underwater-sea-lions-swimming-playful.jpg",
			alt: "在洛斯伊斯洛特斯与海狮潜水",
			kicker: "圣灵岛群岛 · 联合国教科文组织世界遗产",
			title: "与好奇的海狮潜水",
			text: "洛斯伊斯洛特斯是400多只海狮的家园，它们在水下嬉戏、翻转、绕着你打转。拉巴斯最有趣的潜水与野生动物组合。",
		},
		quickFacts: [
			{ value: "7-8小时", label: "拉巴斯主码头" },
			{ value: "2-6人", label: "小团体" },
			{ value: "全年", label: "季节" },
			{ value: "2-3次潜水", label: "洛斯伊斯洛特斯及更多" },
		],
		story: {
			kicker: "海中的小狗",
			title: "它们也想玩耍",
			paragraphs: [
				"洛斯伊斯洛特斯位于圣灵岛群岛的最北端，栖息着400多只对潜水员极其好奇和顽皮的海狮。它们绕着你打转、做出各种花样，留下难忘的回忆。",
				"除了这处栖息地，我们还会探访群岛的其他潜点，那里有令人惊叹的岩石地貌、水下洞穴、充满生命的沉船，以及为其赢得「世界水族馆」之名的海洋多样性。",
			],
			commitTitle: "负责任的相遇",
			commitText: "我们以低影响的方式潜水，尊重这个海狮群：是它们决定靠近——而它们几乎总会这样做。",
		},
		split: {
			image: "/scuba-diving-underwater-la-paz-sea-lions-swimming.jpg",
			alt: "与潜水员同游的海狮",
			kicker: "体验如何进行",
			title: "在保护区潜水的一整天",
			text: "我们从拉巴斯主码头启航驶向群岛。视条件进行两到三次有向导潜水，含午餐和饮品——还有海狮作伴。",
		},
		timeline: {
			kicker: "当天行程",
			title: "逐步安排",
			items: [
				{ time: "上午", title: "从拉巴斯出发", text: "在主码头集合，驶向圣灵岛群岛。" },
				{ time: "洛斯伊斯洛特斯", title: "与海狮潜水", text: "在加利福尼亚湾最著名的栖息地进行一次有向导潜水。" },
				{ time: "水面", title: "间歇与午餐", text: "在船上面朝保护区景色休息、享用午餐和饮品。" },
				{ time: "第2潜", title: "沉船与洞穴", text: "在有沉船、岩石地貌和多样海洋生物的潜点进行第二次潜水。" },
				{ time: "下午", title: "返回拉巴斯", text: "带着你这一天的照片和视频回到码头。" },
			],
		},
		fauna: {
			kicker: "群岛生命",
			title: "水下等你的一切",
			items: [
				{ image: "/sea-lions-swimming-underwater.jpg", alt: "水下的海狮", label: "海狮 · 全年" },
				{ image: "/scuba-diving-underwater-la-paz-sea-lions-swimming.jpg", alt: "与海狮潜水", label: "洛斯伊斯洛特斯" },
				{ image: "/buceo-la-paz-buzo.jpg", alt: "拉巴斯的潜水员", label: "沉船与洞穴" },
			],
		},
		includes: {
			kicker: "你的体验包含",
			title: "潜入世界水族馆所需的一切",
			items: [
				{ title: "小艇交通", text: "从拉巴斯主码头往返。" },
				{ title: "2-3次潜水", text: "由持证潜水长在群岛最佳潜点带领。" },
				{ title: "全套装备", text: "含装备选项中包含完整潜水装备。" },
				{ title: "午餐和饮品", text: "全程船上提供餐食和饮品。" },
				{ title: "含照片和视频", text: "水下记录你的体验。" },
			],
		},
		pricing: {
			kicker: "潜水选项",
			title: "选择你的圣灵岛体验",
			cards: [
				{
					name: "持证潜水员",
					amountMxn: 3700,
					amountNote: "/ 每人",
					items: [
						"在群岛进行2-3次潜水",
						"持证潜水长",
						"含午餐和饮品",
						"含照片和视频",
					],
					waText: "我想预订圣灵岛持证潜水",
				},
				{
					name: "体验潜水",
					amountMxn: 4200,
					amountNote: "/ 每人",
					items: [
						"适合无经验的初学者",
						"完整理论讲解",
						"浅水练习",
						"教练监督下的潜水",
					],
					waText: "我想预订圣灵岛体验潜水",
					featured: true,
					featuredTag: "无需证书",
				},
			],
			note: "也适合浮潜者：与海狮浮潜无需潜水证书。",
		},
		finalCta: {
			image: "/scuba-diving-underwater-sea-lions-swimming-playful.jpg",
			alt: "顽皮的海狮",
			title: "与海中的小狗同游",
			text: "在联合国教科文组织世界遗产地的一次永生难忘的体验。今天就预订你的潜水。",
			waText: "我想预订圣灵岛潜水",
		},
	},

	"scuba-discovery": {
		breadcrumb: "海滩体验潜水",
		hero: {
			image: "/snorkeling-coral-reef.jpg",
			alt: "在拉巴斯海滩进行的体验潜水",
			kicker: "拉巴斯 · 从海滩出发",
			title: "你的第一次水下呼吸",
			text: "无需证书、无需经验、无需乘船：你从海滩涉水而入，全程有教练在身旁。最深6米。",
		},
		quickFacts: [
			{ value: "半天", label: "拉巴斯海滩" },
			{ value: "1-6人", label: "每位教练" },
			{ value: "全年", label: "季节" },
			{ value: "最深6米", label: "深度" },
		],
		story: {
			kicker: "适合初学者",
			title: "潜水，没有门槛",
			paragraphs: [
				"体验潜水是尝试潜水最容易的方式：你从海滩涉水入海，在浅水区练习基本技巧，并在最深6米处探索海底。",
				"无需证书或经验——只需想从水下认识科尔特斯海的心。持证教练全程陪伴你，从理论到最后一个气泡。",
			],
			commitTitle: "你的第一步",
			commitText: "如果你爱上潜水，这次体验就是你迈向 Open Water 证书的第一步。适合10岁以上的初学者。",
		},
		split: {
			image: "/snorkeling-crystal-clear-water.jpg",
			alt: "拉巴斯清澈的海水",
			kicker: "体验如何进行",
			title: "从讲解到气泡",
			text: "我们在海滩上从简单的理论介绍开始，在你能踩到底的地方练习基本技巧，当你准备好后，我们在全程陪伴下探索近岸珊瑚礁。含照片。",
		},
		timeline: {
			kicker: "行程",
			title: "逐步安排",
			items: [
				{ time: "欢迎", title: "海滩讲解", text: "简单的理论介绍：装备、呼吸和基本手势。" },
				{ time: "浅水", title: "技巧练习", text: "在你能踩到底的水中进行基本练习，按你的节奏、毫无压力。" },
				{ time: "潜水", title: "有向导探索", text: "沿近岸珊瑚礁进行一次最深6米的有向导潜水。" },
				{ time: "收尾", title: "照片与下一步", text: "你会拿到体验的照片；如果想深入，我们会告诉你如何考取证书。" },
			],
		},
		includes: {
			kicker: "你的体验包含",
			title: "你首次水下之旅所需的一切",
			items: [
				{ title: "持证教练", text: "全程一对一陪伴。" },
				{ title: "全套装备", text: "含全部潜水装备，按你的尺寸调整。" },
				{ title: "浅水练习", text: "在你能踩到底的地方讲解和练习，不慌不忙。" },
				{ title: "含照片", text: "记录你第一次水下呼吸的瞬间。" },
			],
		},
		pricing: {
			kicker: "价格",
			title: "预订你的体验潜水",
			cards: [
				{
					name: "每人",
					amountMxn: 1500,
					amountNote: "/ 每人",
					items: [
						"无需任何经验",
						"持证教练全程陪伴",
						"含全套装备",
						"最深6米",
						"含照片",
					],
					waText: "我想预订海滩体验潜水",
				},
				{
					name: "私人团体",
					amountText: "询价",
					amountNote: "最多6人",
					items: [
						"专属于你团体的教练",
						"时间灵活",
						"相同装备与行程",
						"适合家庭和朋友",
					],
					waText: "我想咨询私人体验潜水的报价",
					featured: true,
					featuredTag: "全新",
				},
			],
			note: "适合10岁以上的初学者。如果你继续考取证书，这次体验将作为你与潜水的首次接触。",
		},
		finalCta: {
			image: "/snorkeling-crystal-clear-water.jpg",
			alt: "科尔特斯海清澈的海水",
			title: "第一次在水下呼吸",
			text: "无需证书、无需经验、别找借口。科尔特斯海在6米深处等你。",
			waText: "我想预订海滩体验潜水",
		},
	},
}
