import type { StoryPageData } from "@/components/StoryPage"

/**
 * English storytelling content for expedition pages. Slugs present here render
 * with StoryPage in English; missing ones fall back to the compact
 * ExpeditionDetail template.
 */
export const storyPagesEn: Record<string, StoryPageData> = {
	"safari-la-ventana": {
		breadcrumb: "Ocean Safari La Ventana",
		hero: {
			image: "/images/orca-safari.jpg",
			alt: "Ocean Safari in La Ventana and Cerralvo Island",
			kicker: "La Ventana · Cerralvo Island",
			title: "Ocean Safari La Ventana",
			text: "Explore the waters around Cerralvo Island in search of mobula rays, dolphins, whales and other inhabitants of the Gulf of California, alongside a marine biologist guide and captains who know these waters by heart. Every trip is different. Every encounter is real.",
			meta: "La Ventana · ~6 hours · Groups of up to 8",
			primaryLabel: "Book my adventure",
			primaryWa: "Hi! I'd like to book the Ocean Safari La Ventana",
			secondaryLabel: "See what my day looks like",
			secondaryHref: "#itinerario",
		},
		blocks: [
			{
				type: "quickfacts",
				items: [
					{ value: "6 hours", label: "Approx. duration" },
					{ value: "8:00 a.m.", label: "Departure time" },
					{ value: "2-8 people", label: "Shared or private" },
					{ value: "Age 14+", label: "Minimum (shared)" },
				],
			},
			{
				type: "prose",
				kicker: "What the Ocean Safari is",
				heading: "We're not here to tick off stops. We're here to read the sea.",
				paragraphs: [
					"The morning begins in La Ventana, with Cerralvo Island drawing itself in front of us and the team getting the boat ready. We introduce ourselves, check the day's conditions, fit your snorkel gear and talk about the animals we might find. Then we head out toward the channel between the peninsula and Cerralvo Island.",
					{ lead: "From there, the sea is in charge." },
					"We don't follow a tourist route with mandatory stops. We watch birds, currents, splashes, fins, blows and any movement that might reveal activity. We listen to reports from local captains and choose the route with the best chances for that day.",
					"We might start by following a pod of dolphins, change direction for an aggregation of mobula rays, and end up watching a whale on the horizon. There are also quieter days, when it's about navigating, searching and enjoying the landscape with patience.",
					{ lead: "That's a real safari: not knowing exactly what will appear, but being in the right place to discover it." },
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/images/especies/mobulas-bajo-agua.jpg", alt: "Aggregation of mobula rays swimming below the surface in the Gulf of California, La Ventana" },
				quote: "The sea decides what it shows us. We bring the patience to discover it.",
			},
			{
				type: "callout",
				ink2: true,
				heading: "Before you book, there's something important you should know",
				paragraphs: [
					"We work with wild animals in freedom. We don't visit a place where the mobulas, dolphins or whales are waiting: we navigate an open ecosystem, and every encounter depends on the season, the weather, the currents and the animals' natural behavior.",
					"That's why we never promise a specific species or guarantee getting in the water with one. What we do promise is an active search, a team committed to making the most of the conditions, decisions made with safety first, and respectful observation that doesn't interfere with the wildlife.",
					"The sea decides what it shows us. We bring the experience to know how to look for it, and the patience to enjoy it.",
				],
			},
			{
				type: "timeline",
				id: "itinerario",
				kicker: "What your day looks like",
				title: "From the coast to the deep blue",
				note: "Times are approximate. The order of the experience may change depending on the weather, the sea conditions and the wildlife we find.",
				items: [
					{
						time: "Meeting point · La Ventana",
						title: "We meet in La Ventana",
						paragraphs: [
							"The adventure begins at our meeting point in La Ventana. We recommend arriving 15 minutes early to get to know each other, settle your belongings, try on your gear and start the briefing without rushing.",
							"We'll hand you a mask, snorkel, fins and wetsuit. We'll check sizes and explain how to move inside the boat, what signals we'll use and how we'll act if we get in the water. We'll also talk about the animals most present during the season of your visit.",
						],
					},
					{
						time: "8:00 a.m.",
						title: "We leave the coast behind",
						paragraphs: [
							"We board the boat and start heading toward the Cerralvo channel. In the first few minutes you'll begin to understand that looking for wildlife isn't just waiting for something to appear.",
							"We pay attention to feeding birds, changes on the surface, distant blows, shadows under the water and any movement that might signal activity. And yes: often it all starts with someone pointing at the horizon and shouting, \"something jumped over there!\"",
						],
						media: { src: "/images/safari/lancha-avistando-ballena.jpg", alt: "Traveler on the boat watching a whale surface off the coast of La Ventana" },
					},
					{
						title: "The search begins",
						paragraphs: [
							"This is where the fixed route ends. We can cruise the channel, approach different zones around Cerralvo Island, or completely change direction following reports and the signs of the sea.",
							"When we find animals, we first assess their behavior. Some encounters are best enjoyed from the boat; in others, when the species, conditions and safety allow, we get ready to enter the water. Every encounter works differently. That's where the magic is.",
						],
					},
					{
						title: "When the encounter allows getting in the water",
						paragraphs: [
							"Not every sighting turns into snorkeling, and that's intentional. Before getting in we assess the species, the animal's behavior, the current and swell, the group's experience, the presence of other boats and the chance of a safe, respectful approach.",
							"You don't need to be a freediver or an athlete, but you do need to feel comfortable floating and following instructions in the sea. Sometimes the best encounter happens in the water; other times it happens sitting in the boat, watching a whale breathe a few meters away. We never force an interaction just to get a photo.",
						],
						media: { src: "/images/safari/snorkel-lobos-marinos.jpg", alt: "Group of travelers snorkeling next to sea lions at Cerralvo Island, La Ventana" },
					},
					{
						title: "A pause with a taste of Baja",
						paragraphs: [
							"After several hours of navigation we look for a good spot to rest. When conditions allow, we approach a pristine beach or a quiet area to share ceviche, seasonal fruit, snacks and drinks.",
							"It's not a stop at a beach club: no vendors, no rows of loungers. Just the group, the mountains, the island and a meal that tastes much better after a morning of looking for animals.",
						],
						media: { suggest: "Baja-style picnic: ceviche, fruit and drinks served facing the sea on a pristine beach, with the island in the background." },
					},
					{
						time: "≈ 2:00 p.m.",
						title: "The way back counts too",
						paragraphs: [
							"The return to La Ventana is planned for around 2:00 p.m., though the time may vary with conditions. We keep watching the sea the whole way: many encounters appear right when someone had already put the camera away.",
							"Back on shore, we collect the gear and say goodbye with salt in our hair, new stories and, with luck, a memory card that's a good deal fuller than it was in the morning.",
						],
					},
				],
			},
			{
				type: "encounters",
				ink2: true,
				kicker: "What are the encounters really like?",
				title: "Learning to observe is part of the adventure",
				items: [
					{ title: "Dolphins", text: "They may approach the boat, ride alongside the bow or keep their distance. Some pods pass quickly; others seem to have the whole morning free and stay around us for several minutes.", media: { src: "/images/especies/delfin-salto.jpg", alt: "Dolphin leaping beside the boat in the Gulf of California" } },
					{ title: "Mobula rays", text: "We may find them swimming below the surface, gathered in groups or leaping out of the water. The big aggregations are seasonal and their presence can vary even within the best season.", media: { src: "/images/especies/mobula-salto.jpg", alt: "Mobula ray leaping out of the water in La Ventana" } },
					{ title: "Whales", text: "In many cases the first sign is a blow on the horizon. We approach calmly, respect their space and observe their direction, breathing rhythm and behavior.", media: { src: "/images/especies/ballenasaltando2.jpeg", alt: "Whale breaching in the Sea of Cortez" } },
					{ title: "Sea lions", text: "They may appear during navigation or near the coast. Although they tend to be curious, every encounter depends on the place, the season and the day's conditions.", media: { src: "/images/especies/lobomarinonadando.jpeg", alt: "Sea lion swimming in the Gulf of California" } },
					{ title: "Exceptional encounters", text: "Orcas, sperm whales, pilot whales, false killer whales, beaked whales, giant mantas and whale sharks may cross these waters. They're occasional and unpredictable; never a promise, but knowing they roam the Cerralvo channel is part of what makes exploring it so special.", media: { src: "/images/especies/orcalaventana.jpeg", alt: "Orca in the waters of La Ventana, Baja California Sur" } },
					{ title: "Sperm whales", text: "The giants of the deep sometimes cross the Cerralvo channel. Watching them breathe at the surface before a long dive is one of those moments no one forgets.", media: { src: "/images/especies/cachalote-buceo.jpg", alt: "Sperm whale swimming underwater in the Gulf of California" } },
				],
			},
			{
				type: "video",
				kicker: "A minute at sea",
				title: "See it before you live it",
				media: { suggest: "Cinematic 30-60s reel: drone leaving La Ventana, mobulas leaping, entering the water with dolphins, a whale breathing and the sunset on the way back." },
			},
			{
				type: "seasons",
				kicker: "Wildlife and seasons",
				title: "Choose your best time",
				intro: "Marine life changes throughout the year. These references help you choose a season, but no encounter can be guaranteed. For much of the year you may find dolphins, sea lions and seabirds that help us locate activity.",
				items: [
					{ name: "Spring", text: "One of the most special seasons to look for large aggregations of mobula rays. Dolphins, sea lions, blue whale and — extraordinarily — orcas or other large predators may also appear." },
					{ name: "Summer", text: "The mobula season continues and the chance of pelagic activity increases. Dolphins, sea lions, Bryde's whales and, occasionally, sperm whales, orcas and pilot whales may appear." },
					{ name: "Autumn", text: "A lesser-known season, but with interesting chances of finding dolphins, sea lions, birds, giant mantas and sperm whales." },
					{ name: "Winter", text: "The arrival of different whale species transforms the region: humpbacks, blues and fins, plus dolphins and smaller mobula aggregations." },
				],
			},
			{
				type: "mediaSplit",
				reverse: true,
				media: { src: "/images/safari/guia-biologo-camara.jpg", alt: "Keabelmet marine biologist guide photographing wildlife during the safari in La Ventana" },
				kicker: "Who's with you",
				title: "We don't just point at animals. We interpret them.",
				paragraphs: [
					"Every trip is led by a marine biologist who reads the wildlife's behavior and the sea's signs in real time. It's not just a boat ride: it's a reading of the ecosystem by someone who understands and respects it.",
					"You'll ask questions, learn and observe with new eyes. And when you understand what you're seeing, the encounter becomes even more yours.",
				],
			},
			{
				type: "checklist",
				kicker: "Is this adventure for you?",
				title: "So you book with clear expectations",
				good: {
					title: "This safari is for you if…",
					items: [
						"Nature excites you even without a guaranteed outcome.",
						"You prefer small groups and want to learn while you observe.",
						"You enjoy navigating, photography and open landscapes.",
						"It's your first snorkeling experience and you're willing to follow instructions.",
						"You travel solo, as a couple, with friends or family.",
						"You're looking for a day trip near La Paz that feels truly different.",
					],
				},
				bad: {
					title: "It may not be ideal if…",
					items: [
						"You need a guaranteed swim with a specific species.",
						"You don't want to spend several hours on a boat.",
						"You expect a completely rigid route.",
						"You're not comfortable with changes caused by the wind or the sea.",
						"You're looking to touch, feed or chase animals.",
					],
				},
			},
			{
				type: "details",
				kicker: "Everything included",
				title: "What we've already thought of for you",
				items: [
					{ title: "~6-hour marine safari", text: "Boat with a local captain and specialized guide to navigate, search for wildlife and interpret the encounters." },
					{ title: "Marine biologist guide", text: "We don't just point at animals: we explain what we're seeing, how they behave and why this channel gathers so much life." },
					{ title: "Full snorkel gear", text: "Mask, snorkel and fins. We help you choose the size and fit the gear before setting out." },
					{ title: "Wetsuit", text: "Included according to the season and the water temperature." },
					{ title: "Baja-style picnic", text: "Ceviche, seasonal fruit, snacks and drinks to rest and recharge." },
					{ title: "Photos and video", text: "We document the best moments so you don't have to choose between living the encounter and spending the safari behind a screen. Delivered 1 to 3 days later." },
				],
			},
			{
				type: "groups",
				ink2: true,
				kicker: "What to bring",
				title: "Come comfortable. We've thought of the rest.",
				groups: [
					{ name: "Essential", items: ["Swimsuit", "Towel", "Sandals or shoes that can get wet", "Light, comfortable clothing", "A change of dry clothes"] },
					{ name: "Sun protection", items: ["Cap or hat", "Sunglasses with a strap", "Biodegradable sunscreen", "A light long-sleeve layer"] },
					{ name: "Cooler months", items: ["A sweatshirt", "A windbreaker", "Extra dry clothing"] },
					{ name: "For your belongings", items: ["Waterproof phone case", "Small dry bag", "Waterproof camera, if you have one"] },
					{ name: "Highly recommended", items: ["Eat something light beforehand", "Arrive well hydrated", "Seasickness medication if you're prone to it", "Let us know about allergies or medical conditions", "Plenty of adventurous spirit"] },
				],
			},
			{
				type: "info",
				kicker: "Before setting out",
				title: "Practical information",
				items: [
					{ label: "Meeting point", value: "Keabelmet Expeditions, La Ventana. We recommend arriving 15 minutes early." },
					{ label: "Restroom", value: "The boat has no restroom; please use the facilities before the safari begins." },
					{ label: "Transport from La Paz", value: "We can arrange round-trip transport for an extra $1,000 MXN (up to 4 people), subject to availability." },
					{ label: "Food", value: "Ceviche, fruit, snacks and drinks. Let us know in advance about allergies, diets or if you don't eat fish or shrimp." },
					{ label: "Photos and video", value: "Included; usually delivered 1 to 3 days after the safari." },
					{ label: "Minors", value: "On shared trips the minimum age is 14. Children under 14 can join on a private safari, with an adapted pace." },
				],
			},
			{
				type: "gallery",
				ink2: true,
				kicker: "Moments from the safari",
				title: "A day that looks like this",
				cols: 4,
				items: [
					{ src: "/images/orca-safari.jpg", alt: "Navigating in search of wildlife in La Ventana" },
					{ src: "/images/especies/delfinsaltando.jpeg", alt: "Dolphins leaping in the Gulf of California" },
					{ src: "/images/safari/grupo-flotando-isla.jpg", alt: "Group of travelers floating together in the sea with Cerralvo Island behind" },
					{ src: "/images/especies/ballenasaltando2.jpeg", alt: "Whale breaching in the Sea of Cortez" },
					{ src: "/images/safari/snorkel-pulgares.jpg", alt: "Traveler with a snorkel celebrating in the water during the safari" },
					{ src: "/images/especies/lobomarinonadando.jpeg", alt: "Curious sea lion underwater" },
					{ src: "/images/safari/manta-gigante-buceo.jpg", alt: "Giant manta swimming underwater in the Cerralvo channel" },
					{ src: "/images/especies/mobulaschafa.jpeg", alt: "Mobula rays leaping near the boat" },
				],
			},
			{
				type: "pricing",
				id: "precios",
				kicker: "Prices",
				title: "Choose your option",
				cards: [
					{
						name: "Shared safari",
						amountMxn: 3000,
						amountNote: "/ person",
						desc: "Ideal for solo travelers, couples or small groups who want to share the experience with other adventurers.",
						items: [
							"~6-hour safari with captain and marine biologist guide",
							"Snorkel gear and wetsuit",
							"Picnic, fruit, snacks and drinks",
							"Photos and videos",
							"Minimum 4 participants · Age 14+",
						],
						waText: "Hi! I'd like to book the shared Ocean Safari La Ventana",
						ctaLabel: "Find a shared trip",
					},
					{
						name: "Private safari",
						amountMxn: 16000,
						amountNote: "/ boat",
						desc: "An exclusive experience for families, groups of friends, couples or anyone who prefers more privacy and personalized attention.",
						items: [
							"Exclusive boat, up to 8 people",
							"Captain and marine biologist guide",
							"Snorkel gear and wetsuit",
							"Picnic, fruit, snacks and drinks",
							"Photos and videos",
							"The right option for groups with children under 14",
						],
						waText: "Hi! I'd like to book the private Ocean Safari La Ventana",
						ctaLabel: "Book a private safari",
						featured: true,
						featuredTag: "Private",
					},
				],
				note: "Coming from La Paz? We can arrange round-trip transport for an extra $1,000 MXN (up to 4 people), subject to availability.",
			},
			{
				type: "policies",
				ink2: true,
				kicker: "Policies",
				title: "Clear and fair",
				items: [
					{
						title: "Weather policy",
						paragraphs: [
							"Safety always comes before the itinerary. If the captain or team decide that the wind or sea don't allow the activity to run safely, you can reschedule the safari for another available date or receive a full refund.",
							"We can't control the wind, but we can be fair with you.",
						],
					},
					{
						title: "Cancellation policy",
						paragraphs: [
							"If you cancel at least 24 hours in advance, you'll receive a refund.",
							"Cancellations with less than 24 hours' notice are non-refundable —the boat, gear, food and logistics are already prepared— but the amount can be kept as credit for a future activity, subject to availability.",
						],
					},
				],
			},
			{
				type: "faq",
				kicker: "Frequently asked questions",
				title: "Everything you usually want to know",
				items: [
					{ q: "Do I need to know how to swim?", a: ["To enjoy the snorkel entries it's advisable to know how to swim and feel comfortable in open water. You can also stay on the boat during certain encounters. Let us know before booking if someone in the group can't swim so we can assess whether the experience is suitable."] },
					{ q: "Is getting in the water mandatory?", a: ["No. Much of the safari can be enjoyed from the boat; some sightings are even better from the surface. Getting in the water depends on your comfort, the species, the conditions and the guide's assessment."] },
					{ q: "Is it guaranteed we'll see orcas?", a: ["No. Orcas are wild animals and their presence changes daily. There are seasons with better chances, but no specific sighting can be guaranteed. Any company that tells you otherwise is lying to you."] },
					{ q: "Can we swim with all the animals?", a: ["No. Getting in the water depends on the species, its behavior, the conditions, safety and regulations. Swimming with whales and sperm whales is not allowed in Mexican waters. We never force an interaction."] },
					{ q: "When is the best season?", a: ["It depends on what interests you most. Spring and early summer stand out for mobula aggregations; in the cooler months different whales may appear. Dolphins, sea lions and birds can be found for much of the year."] },
					{ q: "Can children take part?", a: ["On shared trips the minimum age is 14. Children under 14 can join on a private safari, where the guide adapts the pace and gives them more attention."] },
					{ q: "What if I get seasick?", a: ["We recommend eating light, staying hydrated and taking preventive measures if you tend to get seasick. Check in advance which medication is right for you and follow the product's or your doctor's instructions."] },
					{ q: "Is there a restroom on the boat?", a: ["No. We recommend using the facilities before setting out, as the experience lasts about six hours."] },
					{ q: "Do you offer transport from La Paz?", a: ["Yes. We can arrange round-trip transport for an extra $1,000 MXN for up to four people. It must be requested in advance and is subject to availability."] },
					{ q: "What if I don't eat fish or shrimp?", a: ["Let us know before the trip so we can review other options. You can also bring your own snacks. Any allergy must be communicated in advance."] },
					{ q: "When will I get my photos and videos?", a: ["Usually 1 to 3 days after the safari, through the channel agreed with the team."] },
					{ q: "Can I bring my camera?", a: ["Yes, at your own risk. We recommend protecting it from the water and securing it well. Space is limited, so let us know if you'll bring large gear; a GoPro, Insta360 or compact camera are no problem."] },
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/images/especies/ballena-atardecer.jpg", alt: "Whale breaching at sunset in the Gulf of California" },
				quote: "You can't always choose the moment that will stay with you. But you almost always leave wanting to come back.",
				align: "bottom",
			},
			{
				type: "prose",
				ink2: true,
				kicker: "Being water and land",
				heading: "We don't just want you to see animals. We want you to understand why they're here.",
				paragraphs: [
					"Keabelmet was born from the curiosity to discover what happens where the desert meets the sea. That's why our trips are led by people who love adventure but also know the biology and behavior of the wildlife we look for.",
					"A dolphin isn't just a fin beside the boat. A mobula isn't just a leap. A whale isn't just a photo. Every behavior tells a story — and when you understand what you're seeing, the encounter becomes even more powerful.",
				],
			},
			{
				type: "finalCta",
				image: "/images/orca-safari.jpg",
				alt: "Mobula rays and dolphins in La Ventana",
				title: "You may set out looking for orcas or mobulas. The sea may have other plans.",
				text: "That's the exciting part. Tell us when you're visiting Baja California Sur and we'll help you choose the best time to live your Ocean Safari in La Ventana and Cerralvo Island.",
				primaryLabel: "Check availability",
				primaryWa: "Hi! I'd like to check availability for the Ocean Safari La Ventana",
				secondaryLabel: "See all expeditions",
				secondaryHref: "/#expediciones",
			},
		],
	},
	"buceo-cabo-pulmo": {
		breadcrumb: "Diving in Cabo Pulmo",
		hero: {
			image: "/coral-reef-underwater-diving-cabo-pulmo-colorful-f.jpg",
			alt: "Living coral reef in Cabo Pulmo National Park",
			kicker: "Cabo Pulmo · National Park",
			title: "There are places where the sea is alive",
			text: "Cabo Pulmo is one of them. A few decades ago this reef was close to disappearing; today it's one of the planet's greatest examples of marine recovery. Here you don't come to look for one particular fish: you come to dive into an ecosystem where thousands of fish move as one.",
			meta: "Cabo Pulmo · ~5 hours · Discovery, certified and snorkel",
			primaryLabel: "Book my dive",
			primaryWa: "Hi! I'd like to book diving in Cabo Pulmo",
			secondaryLabel: "Discover what the day looks like",
			secondaryHref: "#itinerario",
		},
		blocks: [
			{
				type: "quickfacts",
				items: [
					{ value: "~5 hours", label: "Duration" },
					{ value: "8 a.m. · 12 p.m.", label: "Departures" },
					{ value: "2 dives", label: "In the National Park" },
					{ value: "Age 12+", label: "Minimum age" },
				],
			},
			{
				type: "prose",
				kicker: "The reef that came back to life",
				heading: "A village stopped fishing to start protecting. And nature responded.",
				paragraphs: [
					"For many years, Cabo Pulmo was a small fishing village. As happened in so many parts of the world, the reef slowly began to lose life. Until something extraordinary happened: the residents themselves decided to stop making a living from extracting fish and start protecting them.",
					{ lead: "It was an enormous bet. And nature responded." },
					"Decades later, Cabo Pulmo is considered one of the greatest cases of marine recovery on the planet. The reef's biomass grew spectacularly and today thousands of fish, turtles, rays, groupers and huge schools fill these waters again.",
					"When you dive here you don't just visit a National Park: you're stepping into a conservation story that's still being written every day.",
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/buceo-cabo-pulmo-cardumen.jpg", alt: "Massive school of fish moving as one in Cabo Pulmo" },
				quote: "Here the protagonist isn't an animal. It's the sheer amount of life.",
			},
			{
				type: "callout",
				ink2: true,
				heading: "What impresses first isn't a species. It's feeling surrounded by life.",
				paragraphs: [
					"There are dives where a bull shark steals all the attention. In Cabo Pulmo something different happens.",
					"Giant schools that darken the water for a few seconds. Enormous groupers watching from the reef. Turtles that pass slowly, unbothered by our presence. Rays resting on the sand. Thousands of fish moving at the same time, as if they shared a single thought.",
					"And, some days, unexpected visitors that arrive from the open sea to remind us the ocean always holds one more surprise.",
				],
			},
			{
				type: "timeline",
				id: "itinerario",
				kicker: "What your day looks like",
				title: "From the dive center to the reef",
				note: "The order and the sites may change depending on the sea conditions and the National Park's daily assignment.",
				items: [
					{
						time: "Meeting point · Cabo Pulmo",
						title: "We meet in Cabo Pulmo",
						paragraphs: [
							"The experience begins at the dive center. We recommend arriving a few minutes early to check in calmly, review the gear and use the restroom before setting out.",
							"Here you'll meet the divemaster who will be with you throughout the activity. Depending on the option, we'll review the gear, talk through the day's plan and answer any questions before heading to the boat.",
						],
					},
					{
						title: "The briefing",
						paragraphs: [
							"Before entering the water we take the time needed to explain the dive: the assigned site, the sea conditions, the maximum depth, the communication signals and everything you need to enjoy it calmly.",
							"If it's your first dive, here you'll learn to breathe underwater and feel comfortable. If you're already certified but haven't been in the sea for a while, the divemaster will adapt the pace to the group's experience.",
						],
					},
					{
						title: "Heading to the reef",
						paragraphs: [
							"We board the boat and navigate to the assigned site. Here's something few people know: the dive sites aren't chosen freely.",
							"Every morning the National Park holds a draw among the dive centers to distribute the available sites. We can't promise a specific reef — and, curiously, that's one of the reasons Cabo Pulmo stays so healthy. Nature always comes first.",
						],
						media: { suggest: "Divers aboard the panga heading to the dive site, with the desert coast of Cabo Pulmo in the background." },
					},
					{
						title: "The moment of the giant stride",
						paragraphs: [
							"There's a moment every diver remembers. You put on your mask. You breathe deep. You look back. And you roll in.",
							"Suddenly the noise of the world disappears. All that's left are the bubbles, your breathing and a reef that seems to have a life of its own. Throughout the dive we follow the reef's rhythm: we never chase animals, we never rush the experience.",
						],
						media: { src: "/buceo-cabo-pulmo-buzo.jpg", alt: "Diver descending over the Cabo Pulmo reef" },
					},
					{
						title: "Second dive",
						paragraphs: [
							"After a surface interval we do a second tank. The scenery often changes completely: another site, another depth, other wildlife.",
							"Two dives in Cabo Pulmo rarely feel the same. And that's exactly what makes you want to come back.",
						],
					},
				],
			},
			{
				type: "callout",
				heading: "Why don't we promise a specific site? Because it wouldn't be honest.",
				paragraphs: [
					"Every morning the National Park assigns the dive sites through a rotation and draw system among all authorized operators. This management reduces pressure on the reef and helps conserve one of the most important marine ecosystems in the Gulf of California.",
					"In other words: the fact that we can't choose just any site is precisely one of the reasons Cabo Pulmo remains so spectacular.",
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/coral-reef-underwater-cabo-pulmo-colorful-tropical.jpg", alt: "Colorful coral reef in Cabo Pulmo" },
				quote: "Every descent is different. So is every breath underwater.",
			},
			{
				type: "fauna",
				ink2: true,
				kicker: "Wildlife",
				title: "The reef changes every day",
				note: "We can't guarantee any species. We can guarantee that every dive happens inside one of the healthiest reefs on the planet.",
				tiers: [
					{ label: "For much of the year", species: ["Jacks", "Snappers", "Giant groupers", "Sea turtles", "Rays", "Reef fish"] },
					{ label: "Some days visitors arrive", warn: true, species: ["Bull shark", "Mobula rays", "Dolphins", "Humpback whale", "Whale shark", "Tiger shark"] },
				],
			},
			{
				type: "video",
				kicker: "A minute underwater",
				title: "See it before you live it",
				media: { suggest: "Cinematic 30-60s reel: the giant stride into the water, a school enveloping the diver, a giant grouper, a turtle crossing the reef and bubbles rising to the surface." },
			},
			{
				type: "details",
				kicker: "Which option is for you?",
				title: "Three ways to experience the reef",
				items: [
					{ title: "Discovery", text: "Never dived before? Discover what it feels like to breathe underwater. No prior experience needed: you'll do two dives always accompanied by a certified instructor." },
					{ title: "Certified diving", text: "If you hold an Open Water certification or higher, you'll do two dives adapted to the group's experience. It doesn't matter if it's been a while: the divemaster will adjust the pace." },
					{ title: "Snorkel", text: "If you prefer to stay at the surface, you can also explore Cabo Pulmo snorkeling. Snorkel groups usually go on a separate boat to make the most of everyone's time; if you'd rather stay together, let us know in advance." },
				],
			},
			{
				type: "details",
				ink2: true,
				kicker: "Everything included",
				title: "What's already taken care of",
				items: [
					{ title: "Two dives", text: "In Discovery mode or for certified divers, at the sites assigned for the day." },
					{ title: "Full diving gear", text: "All the equipment needed for the dive." },
					{ title: "Certified instructor or divemaster", text: "Accompanies you and adapts the pace to the group's experience." },
					{ title: "Boat and local captain", text: "With knowledge of the park and its conditions." },
					{ title: "Safety briefing", text: "A full explanation before entering the water and site selection based on conditions." },
					{ title: "Snacks and water", text: "Hydration and something light on board during the trip." },
				],
			},
			{
				type: "info",
				kicker: "Before booking",
				title: "Important information",
				items: [
					{ label: "Minimum age", value: "12 years old." },
					{ label: "Minimum certification", value: "Open Water for the certified diving option." },
					{ label: "Photos and video", value: "This activity does not include photo or video service." },
					{ label: "Transport", value: "We don't offer transport from La Paz to Cabo Pulmo." },
					{ label: "Restrooms", value: "The dive center has restrooms before setting out. The boat has no restroom, so we recommend using the facilities before boarding." },
				],
			},
			{
				type: "pricing",
				id: "precios",
				kicker: "Prices",
				title: "Choose your experience in Cabo Pulmo",
				cards: [
					{
						name: "Discovery",
						amountMxn: 3800,
						amountNote: "/ person",
						desc: "Your first breath underwater, with two dives accompanied at all times by a certified instructor.",
						items: [
							"Two guided dives",
							"No prior experience needed",
							"Full diving gear",
							"Certified instructor throughout the activity",
							"Snacks and water on board",
						],
						waText: "Hi! I'd like to book a Discovery dive in Cabo Pulmo",
						ctaLabel: "Book my Discovery",
					},
					{
						name: "Certified diving",
						amountMxn: 3200,
						amountNote: "/ person",
						desc: "Two dives for Open Water divers or higher, adapted to the group's experience.",
						items: [
							"Two dives on the reef",
							"Requires Open Water certification or higher",
							"Full diving gear",
							"Certified divemaster",
							"Snacks and water on board",
						],
						waText: "Hi! I'd like to book certified diving in Cabo Pulmo",
						ctaLabel: "Book certified diving",
						featured: true,
						featuredTag: "Certified",
					},
					{
						name: "Snorkel",
						amountMxn: 1500,
						amountNote: "/ person",
						desc: "Explore the reef from the surface accompanied by a guide.",
						items: [
							"Guided snorkel tour",
							"Ideal for those who prefer not to dive",
							"Snorkel gear",
							"Guide throughout the activity",
						],
						waText: "Hi! I'd like to book snorkeling in Cabo Pulmo",
						ctaLabel: "Book snorkel",
					},
				],
			},
			{
				type: "policies",
				ink2: true,
				kicker: "Policies",
				title: "Clear and fair",
				items: [
					{
						title: "Weather policy",
						paragraphs: [
							"If the weather doesn't allow the activity to run safely, you can choose to reschedule your trip or receive a full refund. Safety always comes before the itinerary.",
						],
					},
					{
						title: "Cancellation policy",
						paragraphs: [
							"If you cancel more than 24 hours in advance, you can request a refund or keep your payment as credit for a future experience with Keabelmet.",
						],
					},
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/images/buceo-cabo-pulmo.jpeg", alt: "Diver exploring the reef of Cabo Pulmo National Park" },
				quote: "You can't always choose the moment that will stay with you. But you almost always leave wanting to come back.",
				align: "bottom",
			},
			{
				type: "finalCta",
				image: "/buceo-cabo-pulmo-cardumen.jpg",
				alt: "Massive school of fish on the Cabo Pulmo reef",
				title: "You might remember a bull shark. Or a school of thousands of fish moving as one.",
				text: "That's Cabo Pulmo. Tell us when you're visiting Baja California Sur and we'll help you choose the best day to dive one of the most alive reefs on the planet.",
				primaryLabel: "Check availability",
				primaryWa: "Hi! I'd like to check availability for diving in Cabo Pulmo",
				secondaryLabel: "See all expeditions",
				secondaryHref: "/#expediciones",
			},
		],
	},
	"tiburon-ballena": {
		breadcrumb: "Whale Shark",
		hero: {
			image: "/tiburon-ballena-drone.jpg",
			alt: "Whale shark swimming near the surface in La Paz",
			kicker: "La Paz · Whale Shark",
			title: "Swim beside the largest fish on the planet",
			text: "Not to chase it. Not to touch it. Simply to keep it company for a few minutes. The whale shark can exceed ten meters and still feed on tiny organisms. Sharing the water with it doesn't feel like an extreme adventure: it feels like a privilege.",
			meta: "La Paz malecón · 2-3 hours · Oct–April season",
			primaryLabel: "Book my encounter",
			primaryWa: "Hi! I'd like to book swimming with whale sharks in La Paz",
			secondaryLabel: "See what the experience is like",
			secondaryHref: "#itinerario",
		},
		blocks: [
			{
				type: "quickfacts",
				items: [
					{ value: "2-3 hours", label: "Approx. duration" },
					{ value: "Oct – April", label: "Season" },
					{ value: "Age 12+", label: "Minimum age" },
					{ value: "La Paz malecón", label: "Meeting point" },
				],
			},
			{
				type: "prose",
				kicker: "The ocean's most gentle giant",
				heading: "Its real defining trait isn't its size. It's its calm.",
				paragraphs: [
					"Some animals inspire respect for their size. The whale shark does too. But a few seconds are enough to discover that what's impressive isn't how big it is, but how calm it is.",
					"It swims slowly. It ignores our presence. And it continues on its way, feeding on plankton near the surface.",
					{ lead: "We're not facing a predator. We're facing one of the most peaceful animals in the ocean." },
					"For a few minutes we can keep it company, always respecting its space and the rules that make this encounter possible.",
				],
			},
			{
				type: "mediaBanner",
				media: { suggest: "Giant overhead photo of the whale shark spanning the full width of the screen, with a small swimmer beside it for scale." },
				quote: "You don't have to touch something to remember it for a lifetime.",
			},
			{
				type: "timeline",
				id: "itinerario",
				kicker: "What the experience is like",
				title: "From the malecón to the encounter",
				note: "We don't follow a set route: we look for the best conditions and the animals feeding near the surface.",
				items: [
					{
						time: "Meeting point · La Paz malecón",
						title: "We meet and do the briefing",
						paragraphs: [
							"After meeting the team we do a short briefing where we explain how the activity will unfold, review the rules of the protected area and answer any questions before boarding.",
						],
					},
					{
						title: "The search begins",
						paragraphs: [
							"Once on the water the search begins. We don't follow a fixed route: we locate the animals feeding near the surface. When we find one, we wait our turn and get ready to enter the water.",
						],
						media: { suggest: "View from the boat of the guide pointing out a whale shark's fin at the surface, with the group ready with snorkels." },
					},
					{
						title: "A few minutes beside the giant",
						paragraphs: [
							"Then comes what everyone comes for. For a few minutes we swim beside the whale shark, always respecting the permitted distance and following the guide's instructions. Then we climb back aboard and begin the search again.",
							"Each encounter is brief. But very few people forget it.",
						],
						media: { suggest: "Snorkeler at a respectful distance beside the whale shark, shot from the surface with turquoise light." },
					},
				],
			},
			{
				type: "seasons",
				ink2: true,
				kicker: "Choose your departure",
				title: "Three departures a day depending on conditions",
				intro: "We offer three departure times during the season to make the most of the day's conditions. No time is better than another: each one unfolds differently, following the animals' natural behavior.",
				items: [
					{ name: "Early departure · our recommendation", text: "Meet 7:00 a.m., depart 8:00 a.m. About 3 hours. It's the longest trip of the day: as the first outing, part of the experience is locating the sharks before the water entries. If you have flexibility, it's the one we recommend most." },
					{ name: "Mid-morning departure", text: "Meet 10:00 a.m., depart 11:00 a.m. About 2 hours. The sharks are usually better located thanks to the first departure, so search time is shorter and the experience is better used." },
					{ name: "Midday departure", text: "Meet 12:00 p.m., depart 1:00 p.m. About 2 hours. Same dynamic as the second slot: the animals are usually already located, letting us head faster to the observation area." },
				],
			},
			{
				type: "callout",
				heading: "We don't come to chase animals. We come to share the water with them.",
				paragraphs: [
					"When we enter the water, we're the ones who must adapt. We never block its path. We never swim in front of it. We never try to touch it.",
					"We simply keep it company for a very small part of its journey. And we believe that's the best way to live this experience.",
				],
			},
			{
				type: "callout",
				ink2: true,
				heading: "Why is the encounter so short? Because protecting the whale shark matters more than prolonging the experience.",
				paragraphs: [
					"The activity is regulated by environmental authorities that limit observation time, the number of boats and how we can approach.",
					"Far from being an inconvenience, these rules are what allow thousands of people to keep enjoying this encounter every season. You don't just come to meet the whale shark: you also come to learn how to coexist with it responsibly.",
				],
			},
			{
				type: "prose",
				kicker: "Every day is different",
				heading: "We work with completely free animals.",
				paragraphs: [
					"Some days we find several individuals. Others we have to search longer. Some swim slowly while feeding; others disappear underwater seconds after we find them.",
					{ lead: "We believe that uncertainty makes every encounter even more valuable." },
				],
			},
			{
				type: "checklist",
				kicker: "Is it for me?",
				title: "So you book with clear expectations",
				good: {
					title: "This experience is ideal if…",
					items: [
						"You've always dreamed of swimming beside a whale shark.",
						"You have no prior snorkeling experience.",
						"You want a responsible encounter with wildlife.",
						"You're looking for an activity suitable for almost the whole family.",
					],
				},
				bad: {
					title: "It may not be for you if…",
					items: [
						"You expect to control the animals' behavior.",
						"You're looking for an experience where everything is guaranteed.",
					],
				},
			},
			{
				type: "details",
				kicker: "Everything included",
				title: "What's already taken care of",
				items: [
					{ title: "Authorized boat", text: "With a permit for the activity in the protected area." },
					{ title: "Certified guide", text: "Accompanies you and explains the rules of the encounter at all times." },
					{ title: "Full snorkel gear", text: "Mask, snorkel and fins." },
					{ title: "Wetsuit", text: "Included according to the season and water temperature." },
					{ title: "Flotation vest", text: "So you can enjoy the encounter with complete peace of mind." },
					{ title: "Safety briefing", text: "A full explanation before entering the water." },
				],
			},
			{
				type: "info",
				ink2: true,
				kicker: "Before booking",
				title: "Important information",
				items: [
					{ label: "Duration", value: "Approximately 2-3 hours depending on the departure." },
					{ label: "Season", value: "From October to April." },
					{ label: "Minimum age", value: "12 years old." },
					{ label: "Meeting point", value: "La Paz malecón." },
					{ label: "Photos and video", value: "This activity does not include photo or video service." },
				],
			},
			{
				type: "pricing",
				id: "precios",
				kicker: "Price",
				title: "Book your encounter",
				cards: [
					{
						name: "Swim with whale sharks",
						amountMxn: 1800,
						amountNote: "/ person",
						desc: "An experience suitable for almost the whole family, with no prior snorkeling experience needed.",
						items: [
							"Authorized boat and certified guide",
							"Full snorkel gear and wetsuit",
							"Flotation vest",
							"Safety briefing",
							"Season from October to April",
						],
						waText: "Hi! I'd like to book swimming with whale sharks in La Paz",
						ctaLabel: "Book my encounter",
						featured: true,
						featuredTag: "Oct – April",
					},
				],
			},
			{
				type: "mediaBanner",
				media: { suggest: "Silhouette of the whale shark seen from below against the surface light, a sense of calm and scale." },
				quote: "You may arrive thinking about its size. But you'll probably leave remembering its calm.",
				align: "bottom",
			},
			{
				type: "finalCta",
				image: "/tiburon-ballena-drone.jpg",
				alt: "Whale shark in the waters of La Paz",
				title: "Some encounters last a few minutes and still stay with you for many years.",
				text: "When you share the water with the largest fish on the planet, you discover that some of the ocean's most impressive creatures can also be the most peaceful. Tell us when you're visiting La Paz and we'll help you choose your departure.",
				primaryLabel: "Check availability",
				primaryWa: "Hi! I'd like to check availability to swim with whale sharks",
				secondaryLabel: "See all expeditions",
				secondaryHref: "/#expediciones",
			},
		],
	},
	"buceo-la-paz": {
		breadcrumb: "Diving Espíritu Santo Island",
		hero: {
			image: "/scuba-diving-underwater-sea-lions-swimming-playful.jpg",
			alt: "Diver swimming with sea lions at Espíritu Santo Island",
			kicker: "Espíritu Santo Island · Diving",
			title: "Some places make you want to return to the sea",
			text: "Very few people forget their first dive at Espíritu Santo Island. Not just for the turquoise water, the reefs or even the sea lions: they remember it because here the ocean seems full of life in every direction. Underwater walls, volcanic reefs, sunken ships and animals that appear when you least expect them.",
			meta: "La Paz Muelle Fiscal · ~7 hours · Two dives",
			primaryLabel: "Book my dive",
			primaryWa: "Hi! I'd like to book diving at Espíritu Santo Island",
			secondaryLabel: "See what the day looks like",
			secondaryHref: "#itinerario",
		},
		blocks: [
			{
				type: "quickfacts",
				items: [
					{ value: "~7 hours", label: "Duration" },
					{ value: "8:00 a.m.", label: "Departure time" },
					{ value: "2 dives", label: "National Park" },
					{ value: "Age 12+", label: "Minimum age" },
				],
			},
			{
				type: "prose",
				kicker: "Where the desert meets the ocean",
				heading: "Each site offers a different scene. Each descent reveals a different part of the island.",
				paragraphs: [
					"Espíritu Santo Island is part of a protected National Park and a UNESCO World Heritage Site. Its volcanic mountains continue underwater, forming reefs, walls and canyons where much of the Gulf of California's marine life gathers.",
					{ lead: "There's no single \"perfect\" dive here." },
					"Some days we descend over reefs full of tropical fish. Others we explore walls where the blue seems endless. And that's exactly why this place never stops surprising.",
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/sea-lions-swimming-underwater.jpg", alt: "Sea lions swimming underwater at Espíritu Santo" },
				quote: "Here the ocean seems full of life in every direction.",
			},
			{
				type: "timeline",
				id: "itinerario",
				kicker: "What your day looks like",
				title: "From the Muelle Fiscal to the island's blue",
				note: "We select the sites based on the day's conditions, visibility and marine activity.",
				items: [
					{
						time: "Meeting point · La Paz Muelle Fiscal",
						title: "We prepare gear and briefing",
						paragraphs: [
							"Our adventure begins at the Muelle Fiscal in La Paz. After preparing the gear and doing the safety briefing, we navigate toward Espíritu Santo Island as the city slowly disappears behind us.",
						],
					},
					{
						title: "We navigate to the island",
						paragraphs: [
							"During the crossing the landscape changes constantly. The reddish mountains appear on the horizon, the white-sand beaches contrast with the turquoise water and, before entering the sea, you already understand why this place is considered one of the most spectacular in Mexico.",
						],
						media: { src: "/pristine-beach-turquoise-water-espiritu-santo-isla.jpg", alt: "White-sand beach and turquoise water at Espíritu Santo Island" },
					},
					{
						title: "Two dives in the park",
						paragraphs: [
							"Once in the park we do two dives, selecting the sites based on the day's conditions. Between them we take a surface interval to rest, hydrate and prepare the next descent.",
						],
						media: { src: "/buceo-la-paz-buzo.jpg", alt: "Diver exploring a reef at Espíritu Santo Island" },
					},
				],
			},
			{
				type: "mediaSplit",
				reverse: true,
				media: { src: "/scuba-diving-underwater-la-paz-sea-lions-swimming.jpg", alt: "Reef and marine life at Espíritu Santo Island" },
				kicker: "Each dive, a different story",
				title: "What was once steel is now covered in life.",
				paragraphs: [
					"At Espíritu Santo there's no single underwater landscape. Some days we descend over reefs full of tropical fish; others we explore walls where the blue seems endless.",
					"And when conditions allow, we visit sunken ships that the ocean has slowly turned into artificial reefs: sponges, corals, schools and moray eels hidden among the structures. Here the ocean reminds us it always finds a way to create life.",
				],
			},
			{
				type: "callout",
				ink2: true,
				heading: "When a sea lion decides to approach, it does so because it wants to.",
				paragraphs: [
					"Sea lions are the most famous inhabitants of Espíritu Santo. The most special part is that we never know what the encounter will be like: some pass at a distance, others approach slowly and, when the youngest ones feel playful, they may circle us for a few seconds before disappearing back into the blue.",
					"We don't call them. We don't feed them. We don't chase them. And that's what makes every encounter so special.",
				],
			},
			{
				type: "callout",
				heading: "Conservation also means knowing when to keep your distance.",
				paragraphs: [
					"Between June and August we don't get in the water with the sea lions. During those months they're in their breeding season, and the rule is to give them the space they need to raise their pups undisturbed.",
					"We keep visiting the colony from the boat and enjoying the rest of the park.",
				],
			},
			{
				type: "fauna",
				ink2: true,
				kicker: "What could you find?",
				title: "The island's inhabitants",
				note: "As with any wildlife experience, every encounter depends on the season, the sea conditions and the animals' natural behavior.",
				tiers: [
					{ label: "Frequent inhabitants", species: ["Sea lions", "Sea turtles", "Rays", "Moray eels", "Reef fish", "Large schools"] },
					{ label: "Occasional visitors", warn: true, species: ["Dolphins", "Hammerhead shark", "Mobula rays", "Humpback whales"] },
				],
			},
			{
				type: "checklist",
				kicker: "Who is this experience for?",
				title: "So you book with clear expectations",
				good: {
					title: "This dive is ideal if…",
					items: [
						"You want to discover one of Mexico's most spectacular marine parks.",
						"You enjoy exploring different underwater scenes in one day.",
						"You're looking for a calm experience with small groups.",
						"The chance of meeting wildlife in freedom excites you.",
					],
				},
				bad: {
					title: "It may not be ideal if…",
					items: [
						"You need a guaranteed encounter with a specific species.",
						"You're looking for deep, technical dives.",
						"You prefer a completely fixed, identical route every day.",
					],
				},
			},
			{
				type: "details",
				kicker: "Everything included",
				title: "What's already taken care of",
				items: [
					{ title: "Two guided dives", text: "At the sites selected based on the day's conditions." },
					{ title: "Certified instructor or divemaster", text: "Adapts the pace to the group's experience." },
					{ title: "Full diving gear", text: "Everything needed for the two dives." },
					{ title: "Boat and captain", text: "With knowledge of the park and its conditions." },
					{ title: "Safety briefing", text: "A full explanation before each descent." },
					{ title: "Snacks and water", text: "To rest between dives." },
				],
			},
			{
				type: "info",
				kicker: "Before booking",
				title: "Important information",
				items: [
					{ label: "Duration", value: "Approximately 7 hours." },
					{ label: "Departure time", value: "8:00 a.m." },
					{ label: "Minimum age", value: "12 years old." },
					{ label: "Options", value: "Scuba Discovery or certified diving (Open Water or higher)." },
					{ label: "Sea lion season", value: "Between June and August you don't get in the water with the sea lions due to their breeding season; they're observed from the boat." },
					{ label: "Photos and video", value: "This experience does not include photo or video service." },
				],
			},
			{
				type: "pricing",
				id: "precios",
				kicker: "Prices",
				title: "Choose your diving option",
				cards: [
					{
						name: "Scuba Discovery",
						amountMxn: 4200,
						amountNote: "/ person",
						desc: "Ideal for those who want to breathe underwater for the first time, accompanied at all times by an instructor.",
						items: [
							"Two guided dives",
							"No prior experience needed",
							"Full diving gear",
							"Certified instructor",
							"Snacks and water on board",
						],
						waText: "Hi! I'd like to book a Scuba Discovery at Espíritu Santo Island",
						ctaLabel: "Book my Discovery",
					},
					{
						name: "Certified diving",
						amountMxn: 3800,
						amountNote: "/ person",
						desc: "Two dives for divers with Open Water certification or higher.",
						items: [
							"Two dives in the park",
							"Requires Open Water certification or higher",
							"Full diving gear",
							"Certified divemaster",
							"Snacks and water on board",
						],
						waText: "Hi! I'd like to book certified diving at Espíritu Santo Island",
						ctaLabel: "Book certified diving",
						featured: true,
						featuredTag: "Certified",
					},
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/lobo-marino-espiritu-santo.jpg", alt: "Sea lion watching up close at Espíritu Santo" },
				quote: "For a few seconds, you had the feeling that the ocean was curious about you too.",
				align: "bottom",
			},
			{
				type: "finalCta",
				image: "/scuba-diving-underwater-sea-lions-swimming-playful.jpg",
				alt: "Diving with sea lions at Espíritu Santo Island",
				title: "You may remember the reefs or the sunken ships. But the first thing you'll recall is that sea lion who decided to come closer.",
				text: "Tell us when you're visiting La Paz and we'll help you choose the best day to dive one of Mexico's most spectacular marine parks.",
				primaryLabel: "Check availability",
				primaryWa: "Hi! I'd like to check availability for diving at Espíritu Santo Island",
				secondaryLabel: "See all expeditions",
				secondaryHref: "/#expediciones",
			},
		],
	},
	"tour-ballena-gris": {
		breadcrumb: "Gray Whale Puerto Chale",
		hero: {
			image: "/ballena-gris-spyhop-drone.jpg",
			alt: "Gray whale spy-hopping next to a boat in Puerto Chale",
			kicker: "Puerto Chale · Gray Whale",
			title: "Imagine a 40-ton whale deciding to come say hello",
			text: "Not because you called it. Not because you fed it. Simply because it wanted to. There are very few places in the world where an animal this large voluntarily approaches people. Puerto Chale is one of them. And when it happens, it's impossible not to smile.",
			meta: "Puerto Chale · Full day from La Paz · January–March",
			primaryLabel: "Book my encounter",
			primaryWa: "Hi! I'd like to book the gray whale tour in Puerto Chale",
			secondaryLabel: "See what the day looks like",
			secondaryHref: "#itinerario",
		},
		blocks: [
			{
				type: "quickfacts",
				items: [
					{ value: "~9 hours", label: "5:00 a.m. pickup in La Paz" },
					{ value: "Jan – March", label: "Season" },
					{ value: "2-3 hours", label: "On the boat with whales" },
					{ value: "Puerto Chale", label: "Pacific coast" },
				],
			},
			{
				type: "prose",
				kicker: "A journey that travels thousands of kilometers",
				heading: "You don't come to watch a show. You come to witness one of the ocean's most extraordinary cycles.",
				paragraphs: [
					"Every winter, hundreds of gray whales reach the calm waters of Baja California Sur after traveling between 8,000 and 10,000 kilometers from the Arctic. They come to breed, rest and give birth to their calves in protected lagoons like those of Puerto Chale.",
					{ lead: "It's one of nature's great journeys." },
					"And also one of the few chances we have to observe these giants in a place where they feel safe.",
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/gray-whale-close-up-magdalena-bay.jpg", alt: "Gray whale near the surface in Puerto Chale" },
				quote: "For a few seconds any sense of fear disappears. Only admiration remains.",
			},
			{
				type: "timeline",
				id: "itinerario",
				kicker: "What the experience is like",
				title: "From the desert to the whale sanctuary",
				note: "We don't chase the whales: we cut the engine when needed, we observe, and we let them decide whether to come closer.",
				items: [
					{
						time: "≈ 5:00 a.m. · pickup in La Paz",
						title: "We cross the desert toward the Pacific",
						paragraphs: [
							"Our adventure begins very early. We leave La Paz as the desert is just beginning to light up and head toward Puerto Chale, a small fishing village on the Pacific coast. Along the way the landscape changes completely.",
						],
						media: { suggest: "Sunrise crossing the Baja desert among giant cardón cacti, on the way to Puerto Chale." },
					},
					{
						title: "We board and the encounter begins",
						paragraphs: [
							"On arrival you'll meet the captain and we'll board a boat designed to cruise the calm waters where the whales spend the winter. It doesn't take many minutes before the first blow. Then a gray back breaking the surface. Farther on, a tail.",
							"And then the most exciting part begins.",
						],
						media: { src: "/gray-whale-in-ocean.jpg", alt: "Gray whale breaking the surface in Puerto Chale" },
					},
					{
						title: "We observe, wait and let them decide",
						paragraphs: [
							"We don't chase the whales. We cut the engine when needed, we observe and we wait. We let them decide whether to come closer. Because that's the essence of this experience.",
							"At midday we pause to eat in Puerto Chale, with food prepared by the local community.",
						],
					},
				],
			},
			{
				type: "callout",
				ink2: true,
				heading: "We don't try to touch a whale. We wait for her to decide to come closer.",
				paragraphs: [
					"Gray whales are famous worldwide for their curious behavior. Some days they simply pass by the boat, and others a huge whale slowly approaches to observe the people.",
					"We can never promise it will happen. But when it does, it's one of those moments no one forgets.",
				],
			},
			{
				type: "mediaSplit",
				media: { src: "/gray-whale-mother-and-calf-swimming-together-in-ba.jpg", alt: "Gray whale mother and calf swimming together in Puerto Chale" },
				kicker: "Curiosity exists in nature too",
				title: "It doesn't happen every time. And that's exactly why every encounter is so special.",
				paragraphs: [
					"Unlike many other species, gray whales are known for voluntarily approaching boats in some of Baja California's breeding lagoons. It doesn't happen with every individual.",
					"We never try to provoke it. We simply respect their space and let them set the pace.",
				],
			},
			{
				type: "fauna",
				ink2: true,
				kicker: "Much more than a sighting",
				title: "What usually appears during the navigation",
				note: "Every trip tells a different story, and that's what makes no experience the same as the one before.",
				tiers: [
					{ label: "Frequent during the navigation", species: ["Adult whales", "Blows and tails emerging", "Dolphins", "Seabirds", "Sea lions", "The desert–Pacific contrast"] },
					{ label: "With luck", warn: true, species: ["Mothers with their calves"] },
				],
			},
			{
				type: "callout",
				heading: "An encounter based on respect.",
				paragraphs: [
					"We work following the guidelines for responsible whale watching: we keep our distance when needed, we reduce navigation speed and we let them decide the level of interaction.",
					"We believe the best wildlife experiences happen when the animal's wellbeing always comes before the perfect photo.",
				],
			},
			{
				type: "checklist",
				kicker: "Who is this experience for?",
				title: "So you book with clear expectations",
				good: {
					title: "It's perfect if…",
					items: [
						"You dream of seeing whales in freedom.",
						"You're looking for a calm, deeply moving experience.",
						"You travel as a couple, with friends or family.",
						"You enjoy getting to know nature responsibly.",
						"You want one of the most special encounters in Baja California Sur.",
					],
				},
				bad: {
					title: "It may not be for you if…",
					items: [
						"You're looking for an adrenaline-filled activity.",
						"You expect to control the animals' behavior.",
						"You want to guarantee physical contact with the whales.",
					],
				},
			},
			{
				type: "details",
				kicker: "Everything included",
				title: "What's already taken care of",
				items: [
					{ title: "Round-trip transport from La Paz", text: "Pickup at your hotel or Airbnb, round trip to Puerto Chale." },
					{ title: "Authorized boat and certified captain", text: "Designed to cruise the calm waters of the sanctuary." },
					{ title: "Specialized guide", text: "Interprets the whales' behavior and looks after the responsible encounter." },
					{ title: "Life vest", text: "So you can navigate with complete peace of mind." },
					{ title: "Food and drinks", text: "Lunch in Puerto Chale prepared by the local community, water and drinks." },
					{ title: "Photos and videos", text: "We document the best moments of your day with the whales." },
				],
			},
			{
				type: "info",
				kicker: "Before booking",
				title: "Important information",
				items: [
					{ label: "Season", value: "From January to March." },
					{ label: "Duration", value: "Full-day experience (approx. 9 hours including transport)." },
					{ label: "Location", value: "Puerto Chale, Baja California Sur." },
					{ label: "Small groups", value: "To enjoy the experience with more comfort and less impact on the wildlife." },
					{ label: "Family friendly", value: "It's a calm experience, respecting the minimum age and the boat's safety recommendations." },
				],
			},
			{
				type: "faq",
				kicker: "Frequently asked questions",
				title: "Everything you usually want to know",
				items: [
					{ q: "Is it guaranteed the whales will approach?", a: ["No. We work with completely free animals. What we do guarantee is running the activity during the best season and following responsible practices that maximize the chances of an extraordinary encounter."] },
					{ q: "Can we touch the whales?", a: ["Our goal is never to touch a whale. If one decides to approach on its own, we always follow the captain's instructions and current regulations. Our goal is to respect their natural behavior."] },
					{ q: "Is it suitable for children?", a: ["Yes. It's a calm, family-friendly experience, always respecting the minimum age and the boat's safety recommendations."] },
					{ q: "What if the weather doesn't allow us to go out?", a: ["If conditions aren't safe, you can choose to reschedule the activity or receive the corresponding refund."] },
				],
			},
			{
				type: "pricing",
				id: "precios",
				kicker: "Prices",
				title: "Choose your time on the water",
				cards: [
					{
						name: "Shared · 2 hours on the boat",
						amountMxn: 2800,
						amountNote: "/ person",
						desc: "The gray whale encounter, with round-trip transport from La Paz included.",
						items: [
							"Round-trip transport from La Paz",
							"2 hours on the boat with the whales",
							"Certified captain and specialized guide",
							"Local food, water and drinks",
							"Photos and videos",
						],
						waText: "Hi! I'd like to book the Gray Whale in Puerto Chale (2 hours)",
						ctaLabel: "Book 2 hours",
					},
					{
						name: "Shared · 3 hours on the boat",
						amountMxn: 3000,
						amountNote: "/ person",
						desc: "More time on the water to enjoy the encounter calmly and without rushing.",
						items: [
							"Round-trip transport from La Paz",
							"3 hours on the boat with the whales",
							"Certified captain and specialized guide",
							"Local food, water and drinks",
							"Photos and videos",
						],
						waText: "Hi! I'd like to book the Gray Whale in Puerto Chale (3 hours)",
						ctaLabel: "Book 3 hours",
						featured: true,
						featuredTag: "More time",
					},
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/gray-whale-breaching-sunset-baja-california.jpg", alt: "Gray whale breaching at sunset in Baja California" },
				quote: "Some of nature's most extraordinary moments can't be planned. They can only be received.",
				align: "bottom",
			},
			{
				type: "finalCta",
				image: "/ballena-gris-encuentro.jpg",
				alt: "Encounter with a gray whale in Puerto Chale",
				title: "You may remember its size or the sound of its blow. But you'll remember the moment a whale decided to come closer to observe you.",
				text: "Tell us when you're visiting Baja California Sur between January and March, and we'll help you book your day with the gray whales of Puerto Chale.",
				primaryLabel: "Check availability",
				primaryWa: "Hi! I'd like to check availability for the gray whale tour",
				secondaryLabel: "See all expeditions",
				secondaryHref: "/#expediciones",
			},
		],
	},
	"tour-espiritu-santo": {
		breadcrumb: "Snorkel Tour Espíritu Santo Island",
		hero: {
			image: "/espiritu-santo-island-paradise-beach.jpg",
			alt: "White-sand beach and turquoise water at Espíritu Santo Island",
			kicker: "Espíritu Santo Island · Balandra Beach",
			title: "A day on an island where the desert ends and the ocean begins",
			text: "White-sand beaches, turquoise water, volcanic cliffs, reefs full of life and sea lions playing in the waves. And enough time to enjoy it all without rushing. Some places you visit. Others you simply live.",
			meta: "La Paz Muelle Fiscal · 6 hours · Snorkel + beach",
			primaryLabel: "Book my spot",
			primaryWa: "Hi! I'd like to book the snorkel tour to Espíritu Santo Island and Balandra",
			secondaryLabel: "See what the day looks like",
			secondaryHref: "#itinerario",
		},
		blocks: [
			{
				type: "quickfacts",
				items: [
					{ value: "6 hours", label: "Approx. duration" },
					{ value: "Snorkel + beach", label: "No diving needed" },
					{ value: "Balandra + islands", label: "Espíritu Santo & Partida" },
					{ value: "0-3 free", label: "Family friendly" },
				],
			},
			{
				type: "prose",
				kicker: "Much more than a snorkel tour",
				heading: "Each stop has something different. Together they form one of the most complete tours in La Paz.",
				paragraphs: [
					"Espíritu Santo isn't a place you reach only to get in the water. It's a national park made of volcanic islands, pristine beaches and some of the clearest waters in the Gulf of California.",
					"In a single day you'll visit Mexico's most famous beach —Balandra—, navigate between Espíritu Santo Island and Partida Island, watch seabirds, visit reefs and discover why this corner was declared a UNESCO World Heritage Site.",
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/pristine-beach-turquoise-water-espiritu-santo-isla.jpg", alt: "Turquoise waters of Espíritu Santo Island" },
				quote: "Some places you visit. Others you simply live.",
			},
			{
				type: "timeline",
				id: "itinerario",
				kicker: "What your day looks like",
				title: "From the city to the clearest water in the Gulf",
				note: "Here we don't rush from point to point. We come to enjoy an island that deserves to be explored calmly.",
				items: [
					{
						time: "Before 11:00 a.m. · La Paz Muelle Fiscal",
						title: "We board and leave the city behind",
						paragraphs: [
							"We meet at the Muelle Fiscal, on the La Paz malecón. After meeting the team and boarding, we slowly leave the city behind. As we go, the reddish mountains begin to appear and the water grows clearer and clearer.",
						],
					},
					{
						title: "Balandra seen from the sea",
						paragraphs: [
							"Our first stop is Balandra seen from the sea, a perspective few visitors get to enjoy. Then we continue navigating between Espíritu Santo Island and Partida Island while we look for seabirds, rock formations and other surprises.",
						],
						media: { src: "/luxury-yacht-ocean-balandra-beach-turquoise-lagoon.jpg", alt: "Balandra Beach seen from the sea" },
					},
					{
						title: "Snorkel, beach and sea lions",
						paragraphs: [
							"Throughout the day we'll snorkel on reefs full of life, visit beaches where you can relax for about two hours and, if conditions allow, observe the sea lion colony.",
							"Between each activity there's always time to rest, enjoy the scenery and let the day flow.",
						],
						media: { src: "/snorkeling-coral-reef.jpg", alt: "Snorkeling on a reef in the Gulf of California" },
					},
				],
			},
			{
				type: "mediaSplit",
				reverse: true,
				media: { src: "/magnificent-frigatebird-soaring-over-ocean-in-baja.jpg", alt: "Frigatebird soaring over the sea at Espíritu Santo" },
				kicker: "A day full of small encounters",
				title: "Not everything happens underwater.",
				paragraphs: [
					"Sometimes the most memorable moment happens while navigating between the cliffs. Or when a frigatebird glides over the boat. Or seeing a baby sea lion. Or when a whale lifts its hump beside the boat.",
					"That's what makes no tour exactly the same as the one before.",
				],
			},
			{
				type: "encounters",
				ink2: true,
				kicker: "The day's protagonists",
				title: "Five scenes in a single tour",
				items: [
					{ title: "Balandra Beach", text: "You'll see one of Mexico's most famous beaches from a very different perspective: the sea.", media: { src: "/espiritu-santo-island-beach.jpg", alt: "Balandra Beach from the sea" } },
					{ title: "Espíritu Santo Island", text: "A landscape where the desert, the volcanic mountains and the Sea of Cortez meet.", media: { src: "/espiritu-santo-island-pristine-beach-turquoise-wat.jpg", alt: "Espíritu Santo Island" } },
					{ title: "Partida Island", text: "Channels, hidden beaches and incredibly clear waters.", media: { src: "/pristine-beach-turquoise-water-espiritu-santo-isla.jpg", alt: "Partida Island" } },
					{ title: "Reefs", text: "We'll snorkel at sites selected by our captain based on the day's conditions.", media: { src: "/snorkeling-coral-reef.jpg", alt: "Reef for snorkeling" } },
					{ title: "Sea lions", text: "When regulations and the season allow, we visit the sea lion colony to observe them responsibly.", media: { src: "/lobo-marino-espiritu-santo.jpg", alt: "Sea lion at Espíritu Santo" } },
				],
			},
			{
				type: "callout",
				heading: "Why don't we always swim with the sea lions?",
				paragraphs: [
					"Between June and August the sea lions are in their breeding season. During those months swimming with them isn't allowed, so we prefer to observe them from the boat so as not to interfere with the birth and care of the pups.",
					"We believe protecting nature also means knowing when to keep your distance.",
				],
			},
			{
				type: "checklist",
				kicker: "Who is this experience for?",
				title: "So you book with clear expectations",
				good: {
					title: "Ideal if…",
					items: [
						"You want to see Espíritu Santo without needing to dive.",
						"You're looking for a relaxed experience.",
						"You travel as a couple, with friends or family.",
						"You like combining beach, snorkel and nature in one day.",
						"You want to spend a full day in the Sea of Cortez.",
					],
				},
				bad: {
					title: "It may not be ideal if…",
					items: [
						"You're looking for a scuba diving experience.",
						"You prefer a short tour of just a few hours.",
						"You expect to guarantee swimming with sea lions on any date.",
					],
				},
			},
			{
				type: "details",
				kicker: "Everything included",
				title: "A full day, already sorted",
				items: [
					{ title: "~6-hour tour", text: "With National Park access wristbands included." },
					{ title: "Balandra + Espíritu Santo + Partida", text: "A tour of Mexico's most famous beach and both islands." },
					{ title: "Snorkeling on reefs", text: "At sites selected based on the day's conditions, with beach gear." },
					{ title: "Birds and sea lions", text: "Responsible watching when the season allows, plus two hours to enjoy the beach." },
					{ title: "Food and drinks", text: "Included during the tour." },
					{ title: "Equipped boat and certified crew", text: "Restroom, awning, mattresses and WiFi. Certified captain, NOM-09 guide and first aid." },
				],
			},
			{
				type: "info",
				kicker: "Before booking",
				title: "Important information",
				items: [
					{ label: "Duration", value: "6 hours." },
					{ label: "Price", value: "$1,800 MXN per person. Children 0 to 3: free." },
					{ label: "Park access", value: "National Park wristbands included." },
					{ label: "Sea lion season", value: "Between June and August they're observed from the boat due to their breeding season." },
				],
			},
			{
				type: "pricing",
				id: "precios",
				kicker: "Prices",
				title: "Book your day on the island",
				cards: [
					{
						name: "Shared",
						amountMxn: 1800,
						amountNote: "/ person",
						desc: "A full day of snorkeling, beaches and islands in the Sea of Cortez. Children 0 to 3 free.",
						items: [
							"~6-hour tour with wristbands included",
							"Balandra, Espíritu Santo and Partida Island",
							"Snorkeling on reefs and beach gear",
							"Food and drinks",
							"Boat with restroom, awning and WiFi",
						],
						waText: "Hi! I'd like to book the snorkel tour to Espíritu Santo Island and Balandra",
						ctaLabel: "Book my spot",
						featured: true,
						featuredTag: "Families",
					},
					{
						name: "Private boat",
						amountText: "On request",
						amountNote: "for your group",
						desc: "The same experience, exclusively for your family or group of friends.",
						items: [
							"Exclusive boat for your group",
							"Same complete island tour",
							"Pace adapted to you",
						],
						waText: "Hi! I'd like a quote for the private tour to Espíritu Santo Island and Balandra",
						ctaLabel: "Request a quote",
					},
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/picnic-beach-espiritu-santo.jpg", alt: "Resting on a pristine beach at Espíritu Santo" },
				quote: "You may come for Balandra. And end up falling in love with everything else.",
				align: "bottom",
			},
			{
				type: "finalCta",
				image: "/espiritu-santo-island-paradise-beach.jpg",
				alt: "Espíritu Santo Island from the sea",
				title: "Some remember this tour for the snorkeling. Others for the beach. And others because, for a day, they felt time stopped mattering.",
				text: "Tell us when you're visiting La Paz and we'll help you book your full day among Balandra, Espíritu Santo and Partida Island.",
				primaryLabel: "Check availability",
				primaryWa: "Hi! I'd like to check availability for the snorkel tour to Espíritu Santo",
				secondaryLabel: "See all expeditions",
				secondaryHref: "/#expediciones",
			},
		],
	},
	"scuba-discovery": {
		breadcrumb: "Scuba Discovery from the Beach",
		hero: {
			image: "/scuba-diving-underwater-la-paz-sea-lions-swimming.jpg",
			alt: "First diving experience in La Paz",
			kicker: "La Paz · Scuba Discovery",
			title: "Imagine breathing underwater for the first time",
			text: "It sounds strange. And for the first few seconds it feels that way too. Your brain has spent your whole life telling you that you can only breathe at the surface. Until you take that first breath underwater. And you discover that it works. From that moment on, everything changes. You don't need experience. Just curiosity.",
			meta: "La Paz · ~4 hours · No certification needed",
			primaryLabel: "Book your first dive",
			primaryWa: "Hi! I'd like to book a Scuba Discovery in La Paz",
			secondaryLabel: "See what your day looks like",
			secondaryHref: "#itinerario",
		},
		blocks: [
			{
				type: "quickfacts",
				items: [
					{ value: "~4 hours", label: "Total duration" },
					{ value: "50 min", label: "Underwater" },
					{ value: "6 meters", label: "Maximum depth" },
					{ value: "No certification", label: "No experience needed" },
				],
			},
			{
				type: "prose",
				kicker: "Every diver remembers this moment",
				heading: "They may not recall the date of their certification. But they'll remember the first time they breathed underwater.",
				paragraphs: [
					"Ask anyone who dives. Because that moment changes something: you discover there's a completely different world just a few meters below the surface.",
					"A world where time seems to slow down and the fish are in no hurry. Where every breath invites you to observe calmly.",
					{ lead: "That's the world we want to show you." },
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/snorkeling-crystal-clear-water.jpg", alt: "Crystal-clear waters ideal for a first dive in La Paz" },
				quote: "The sounds disappear. Gravity stops feeling the same. And the ocean becomes a world you're now part of too.",
			},
			{
				type: "timeline",
				id: "itinerario",
				kicker: "What your first dive looks like",
				title: "Step by step, at your pace",
				note: "You don't arrive and get thrown into the sea. Everything happens step by step, adapting to each person's pace.",
				items: [
					{
						title: "You learn the basics",
						paragraphs: [
							"Our adventure begins with a short explanation where you'll get to know the gear, learn how to breathe properly underwater and practice the basic signals we'll use during the dive.",
						],
					},
					{
						title: "You practice in calm water",
						paragraphs: [
							"Then we practice in a controlled setting and, when you feel comfortable, the adventure begins. Depending on the day's conditions, the activity takes place at El Saltito Beach or Cueva de León, two ideal spots for a first contact thanks to their calm, shallow waters.",
							"You'll always be accompanied by a certified instructor. You'll never go alone.",
						],
						media: { suggest: "Instructor practicing signals with a beginner in the shallow, calm waters of a La Paz beach." },
					},
					{
						title: "Your first dive",
						paragraphs: [
							"You'll do a dive of about 50 minutes, reaching a maximum depth of 6 meters, always accompanied by your instructor. It's the perfect depth to enjoy the feeling of breathing underwater with complete calm.",
							"You don't need to go deeper to fall in love with the ocean.",
						],
						media: { src: "/buceo-la-paz-buzo.jpg", alt: "First guided dive in La Paz" },
					},
				],
			},
			{
				type: "callout",
				ink2: true,
				heading: "You don't need experience. We teach you everything.",
				paragraphs: [
					"This experience is designed for people who have never dived. You don't need certifications, you don't need to know how to use the gear, you don't need to have snorkeled before. Our job is to guide you step by step so you can enjoy your first dive calmly and safely.",
					"Most of our participants arrive nervous. And almost all leave asking the same question: \"When can I come back?\"",
				],
			},
			{
				type: "callout",
				heading: "The hardest part isn't breathing. It's believing you really can.",
				paragraphs: [
					"During the first few minutes your mind needs to get used to a completely new idea: breathing underwater.",
					"Then something curious happens. You stop thinking about the regulator. You stop thinking about the gear. And you simply start looking around. That's when the experience really begins.",
				],
			},
			{
				type: "details",
				kicker: "What will you learn?",
				title: "The fundamentals, in a practical, simple way",
				items: [
					{ title: "Breathe underwater with calm", text: "The first and most important step, always at your pace." },
					{ title: "Communicate with signals", text: "The basic signs we'll use during the dive." },
					{ title: "Move with the diving gear", text: "How to move comfortably underwater." },
					{ title: "Control your buoyancy", text: "The key to feeling weightless and enjoying the descent." },
					{ title: "Enjoy the ocean responsibly", text: "Observe calmly and care for the marine environment." },
				],
			},
			{
				type: "fauna",
				ink2: true,
				kicker: "What could you find?",
				title: "Every dive is different",
				note: "The idea isn't to look for a specific species, but to discover how incredible it is to observe the ocean from a completely new perspective.",
				tiers: [
					{ label: "Very common to find", species: ["Reef fish", "Starfish", "Octopuses", "Pufferfish", "Schools of fish"] },
					{ label: "Occasionally", warn: true, species: ["Sea turtles"] },
				],
			},
			{
				type: "checklist",
				kicker: "Is it for me?",
				title: "So you book with clear expectations",
				good: {
					title: "Perfect if…",
					items: [
						"You've always wanted to try diving.",
						"You love nature and the sea.",
						"You've never breathed underwater.",
						"You're looking for something different during your trip.",
						"You want to know if diving is for you before getting certified.",
					],
				},
				bad: {
					title: "It may not be the best option if…",
					items: [
						"You're already a certified diver.",
						"You're looking for deep or technical dives.",
						"You expect a full certification course.",
					],
				},
			},
			{
				type: "details",
				kicker: "Everything included",
				title: "What's already taken care of",
				items: [
					{ title: "Certified instructor", text: "With you throughout the experience; you'll never go alone." },
					{ title: "Full diving gear", text: "Everything needed for your dive." },
					{ title: "Briefing before entering the water", text: "A full, practical explanation in calm water." },
					{ title: "One guided dive", text: "About 50 minutes at a maximum of 6 meters." },
					{ title: "Water and snacks", text: "If applicable, to recharge." },
				],
			},
			{
				type: "info",
				kicker: "Before booking",
				title: "Important information",
				items: [
					{ label: "Total duration", value: "Approximately 4 hours." },
					{ label: "Time underwater", value: "1 dive of about 50 minutes." },
					{ label: "Maximum depth", value: "6 meters." },
					{ label: "Minimum age", value: "12 years old." },
					{ label: "Location", value: "El Saltito Beach or Cueva de León, depending on the sea conditions." },
					{ label: "Experience level", value: "No prior experience or certification needed." },
				],
			},
			{
				type: "faq",
				kicker: "Frequently asked questions",
				title: "Everything you usually want to know",
				items: [
					{ q: "What if I've never dived?", a: ["Perfect. This experience was designed precisely for people who have never breathed underwater."] },
					{ q: "Is it safe?", a: ["Yes. Throughout the activity you'll be accompanied by a certified instructor who guides you step by step. The maximum depth is only 6 meters, ideal for a first experience."] },
					{ q: "What if I get nervous?", a: ["It's completely normal; most people feel nervous before their first dive. That's why we move at your pace and only continue when you feel comfortable."] },
					{ q: "Do I need to be a very strong swimmer?", a: ["It's advisable to feel comfortable in the water. If you have doubts about your swimming level, write to us and we'll gladly advise you."] },
					{ q: "After this am I a certified diver?", a: ["No. Scuba Discovery is an introductory experience so you can discover the world of diving. If you want to continue afterward, we can help you get your Open Water certification."] },
				],
			},
			{
				type: "pricing",
				id: "precios",
				kicker: "Price",
				title: "Book your first dive",
				cards: [
					{
						name: "Per person",
						amountMxn: 1500,
						amountNote: "/ person",
						desc: "Your first diving experience, no certification needed and accompanied at all times by an instructor.",
						items: [
							"One guided dive of ~50 minutes",
							"Certified instructor throughout the activity",
							"Full diving gear",
							"Briefing and practice in calm water",
							"Water and snacks (if applicable)",
						],
						waText: "Hi! I'd like to book a Scuba Discovery in La Paz",
						ctaLabel: "Book my first dive",
						featured: true,
						featuredTag: "Beginners",
					},
					{
						name: "Private group",
						amountText: "On request",
						amountNote: "up to 6 people",
						desc: "The same introductory experience, exclusively for your group.",
						items: [
							"Private experience for your group",
							"Up to 6 people",
							"Personalized attention from the instructor",
						],
						waText: "Hi! I'd like a quote for a private Scuba Discovery in La Paz",
						ctaLabel: "Request a quote",
					},
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/sea-lions-swimming-underwater.jpg", alt: "Marine life below the surface in La Paz" },
				quote: "The first breath. That moment when you stopped wondering if you could do it… and started enjoying it.",
				align: "bottom",
			},
			{
				type: "finalCta",
				image: "/scuba-diving-underwater-la-paz-sea-lions-swimming.jpg",
				alt: "Introductory diving in La Paz",
				title: "Discovering the ocean from within is like nothing else. And once you do, it's very hard to look at it the same way again.",
				text: "Tell us when you're visiting La Paz and book your Scuba Discovery: your first breath underwater, no prior experience needed.",
				primaryLabel: "Check availability",
				primaryWa: "Hi! I'd like to check availability for a Scuba Discovery",
				secondaryLabel: "See all expeditions",
				secondaryHref: "/#expediciones",
			},
		],
	},
	"safari-bahia-magdalena": {
		breadcrumb: "Bahía Magdalena Safari",
		hero: {
			image: "/images/marlin-bahia-magdalena-hero.jpeg",
			alt: "Striped marlin hunting in a bait ball in Bahía Magdalena",
			kicker: "Bahía Magdalena · Sardine Run",
			title: "An ocean where everything happens at once",
			text: "Thousands of sardines try to stay together. Marlin tear through the bait ball at full speed. Sea lions appear from the depths to join the hunt. Flocks of birds mark where the action is. That's Bahía Magdalena. Here we don't follow an itinerary: we follow what the sea decides to show us.",
			meta: "From La Paz · ~10 hours · November–December",
			primaryLabel: "Book your Ocean Safari",
			primaryWa: "Hi! I'd like to book the Ocean Safari in Bahía Magdalena",
			secondaryLabel: "See what the expedition is like",
			secondaryHref: "#itinerario",
		},
		blocks: [
			{
				type: "quickfacts",
				items: [
					{ value: "~10 hours", label: "With round-trip transport" },
					{ value: "Nov – Dec", label: "Season" },
					{ value: "Snorkel", label: "In open water" },
					{ value: "Small groups", label: "Lower impact" },
				],
			},
			{
				type: "prose",
				kicker: "The most unpredictable safari in Baja California Sur",
				heading: "There's no script. And that's exactly the magic.",
				paragraphs: [
					"Some days we find enormous bait balls of sardines surrounded by striped marlin. Others, a pod of dolphins decides to join the hunt. And some, the protagonist turns out to be a Bryde's whale feeding among thousands of fish.",
					"Every trip is different because we work with completely free animals. Our job is to interpret the ocean and be in the right place when nature decides to act.",
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/images/gallery/marlin-cazando.jpeg", alt: "Striped marlin hunting sardines in Bahía Magdalena" },
				quote: "We don't look for animals. We learn to read the ocean.",
			},
			{
				type: "timeline",
				id: "itinerario",
				kicker: "What your expedition looks like",
				title: "From the desert to Mexico's most dynamic Pacific",
				note: "On an Ocean Safari there's no fixed route. We don't navigate from point A to point B: we observe constantly and follow the ocean's signs.",
				items: [
					{
						time: "Before dawn · departure from La Paz",
						title: "We cross the desert toward the Pacific",
						paragraphs: [
							"Our adventure begins before the ocean fully wakes. Very early we leave La Paz toward Bahía Magdalena, crossing the desert until we reach the Pacific coast. The Sea of Cortez is left behind and before us appears one of the most dynamic marine ecosystems in Mexico.",
						],
					},
					{
						title: "We follow the ocean's signs",
						paragraphs: [
							"After preparing the gear and meeting the captain, we board. From that moment on we stop following a schedule and start following the ocean's signs: feeding birds, color changes in the water, movement at the surface.",
							"Small details that often announce something extraordinary is happening a few hundred meters ahead.",
						],
						media: { src: "/images/especies/sardinas-banco.jpeg", alt: "School of sardines forming a bait ball" },
					},
					{
						title: "We get in the water",
						paragraphs: [
							"When the sea gives us the chance, we get in the water. And we become spectators of one of the most impressive natural spectacles of the Mexican Pacific.",
						],
						media: { src: "/striped-marlin-underwater.jpg", alt: "Striped marlin underwater during the Sardine Run" },
					},
				],
			},
			{
				type: "fauna",
				ink2: true,
				kicker: "The protagonist is never the same",
				title: "Every day in Bahía Magdalena is different",
				note: "We don't promise any particular species, because we believe nature is far more thrilling when it stays completely free.",
				tiers: [
					{ label: "During a single trip you might find", species: ["Sardine bait balls", "Striped marlin", "Sea lions", "Dolphins", "Bryde's whales", "Pelicans, gulls and seabirds"] },
					{ label: "And sometimes", warn: true, species: ["Other unexpected pelagic species"] },
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/images/especies/ballena-bryde-underwater.jpeg", alt: "Bryde's whale feeding among schools of fish" },
				quote: "The Sardine Run lasts just a few minutes. Sometimes seconds. But you realize you're witnessing something that has happened exactly as nature has done it for thousands of years.",
			},
			{
				type: "mediaSplit",
				reverse: true,
				media: { src: "/images/safari/guia-biologo-camara.jpg", alt: "Marine biologist guide interpreting the ocean during the safari" },
				kicker: "Narrated by a marine biologist",
				title: "The ocean always leaves clues. My job is to help you read them.",
				paragraphs: [
					"\"For years I studied the behavior of marine wildlife and learned that the ocean always leaves clues. A change in the birds' flight, a different patch on the water or a group of dolphins moving in a specific direction can tell us a lot before the spectacle appears.",
					"That's what I most enjoy sharing on this safari: not just showing you what we see, but helping you understand why it's happening.\"",
				],
			},
			{
				type: "checklist",
				kicker: "Who is this experience for?",
				title: "So you book with clear expectations",
				good: {
					title: "Ideal if…",
					items: [
						"Wildlife in freedom excites you.",
						"You enjoy unpredictable experiences.",
						"You like snorkeling in open water.",
						"You're looking for much more than a traditional tour.",
						"You want to understand the ocean's behavior, not just observe animals.",
					],
				},
				bad: {
					title: "It may not be for you if…",
					items: [
						"You expect a completely fixed itinerary.",
						"You want to guarantee a specific species.",
						"You prefer activities where everything happens the same every day.",
					],
				},
			},
			{
				type: "details",
				kicker: "Everything included",
				title: "What's already taken care of",
				items: [
					{ title: "Round-trip transport from La Paz", text: "We cross the desert to the Pacific coast and back." },
					{ title: "Boat and certified captain", text: "With knowledge of the Bahía Magdalena ecosystem." },
					{ title: "Marine biologist guide", text: "Interprets the ocean and helps you understand what's happening." },
					{ title: "Full snorkel gear", text: "Mask, snorkel, fins and wetsuit." },
					{ title: "Snacks and water", text: "For the full day at sea." },
					{ title: "Photos and videos", text: "We document the best moments of the experience." },
				],
			},
			{
				type: "info",
				kicker: "Before booking",
				title: "Important information",
				items: [
					{ label: "Season", value: "November and December." },
					{ label: "Duration", value: "Approximately 10 hours, including round-trip transport from La Paz and the activity at sea." },
					{ label: "Level", value: "You need to feel comfortable swimming in open water and with snorkeling experience (breathing through the tube)." },
					{ label: "Small groups", value: "We work with small groups to enjoy the experience calmly and minimize impact on wildlife." },
				],
			},
			{
				type: "faq",
				kicker: "Frequently asked questions",
				title: "Everything you usually want to know",
				items: [
					{ q: "Is the Sardine Run guaranteed?", a: ["No. We work with completely wild wildlife and every day is different. We run the activity only during the best season and put all our experience into interpreting the ocean and increasing the chances of witnessing the phenomenon."] },
					{ q: "What if we don't find a bait ball?", a: ["We'll keep exploring Bahía Magdalena in search of other opportunities. Every trip is different and there's always the chance to observe other pelagic species and unique natural behaviors."] },
					{ q: "Do I need snorkeling experience?", a: ["Yes. You need to feel comfortable swimming and following the guide's instructions to fully enjoy the experience."] },
					{ q: "What if the weather doesn't allow us to go out?", a: ["If conditions aren't safe, you can choose to reschedule the activity or receive the corresponding refund."] },
				],
			},
			{
				type: "pricing",
				id: "precios",
				kicker: "Prices",
				title: "Book your Ocean Safari",
				cards: [
					{
						name: "Shared",
						amountMxn: 3500,
						amountNote: "/ person",
						desc: "The Sardine Run with round-trip transport from La Paz and a marine biologist guide included.",
						items: [
							"Round-trip transport from La Paz",
							"Marine biologist guide and certified captain",
							"Full snorkel gear and wetsuit",
							"Snacks and water",
							"Photos and videos",
						],
						waText: "Hi! I'd like to book the Ocean Safari in Bahía Magdalena",
						ctaLabel: "Book my spot",
						featured: true,
						featuredTag: "Nov – Dec",
					},
					{
						name: "Private boat",
						amountText: "On request",
						amountNote: "for your group",
						desc: "The same expedition, exclusively for your group.",
						items: [
							"Exclusive boat for your group",
							"Same safari with a marine biologist guide",
							"Pace adapted to you",
						],
						waText: "Hi! I'd like a quote for the private Ocean Safari in Bahía Magdalena",
						ctaLabel: "Request a quote",
					},
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/striped-marlin-underwater.jpg", alt: "Striped marlin cutting through a school in Bahía Magdalena" },
				quote: "The ocean never repeats the same story twice. And that's exactly why we keep coming back.",
				align: "bottom",
			},
			{
				type: "finalCta",
				image: "/images/marlin-bahia-magdalena-hero.jpeg",
				alt: "Marlin hunting in Bahía Magdalena",
				title: "You may remember a marlin cutting through the bait ball. Or the moment you understood the ocean never repeats the same story.",
				text: "We run the safari only during the best season, in November and December. Tell us your dates and we'll help you book your Ocean Safari in Bahía Magdalena.",
				primaryLabel: "Check availability",
				primaryWa: "Hi! I'd like to check availability for the Ocean Safari in Bahía Magdalena",
				secondaryLabel: "See all expeditions",
				secondaryHref: "/#expediciones",
			},
		],
	},
}
