import type { StoryPageData } from "@/components/StoryPage"

/**
 * English storytelling content for expedition pages. Slugs present here render
 * with StoryPage in English; missing ones fall back to the compact
 * ExpeditionDetail template.
 */
export const storyPagesEn: Record<string, StoryPageData> = {
	"safari-la-ventana": {
		breadcrumb: "Ocean Safari La Ventana",
		hero: {
			image: "/images/orca-safari.jpg",
			alt: "Ocean Safari in La Ventana and Cerralvo Island",
			kicker: "La Ventana · Cerralvo Island",
			title: "Ocean Safari La Ventana",
			text: "Explore the waters around Cerralvo Island in search of mobula rays, dolphins, whales and other inhabitants of the Gulf of California, alongside a marine biologist guide and captains who know these waters by heart. Every trip is different. Every encounter is real.",
			meta: "La Ventana · ~6 hours · Groups of up to 8",
			primaryLabel: "Book my adventure",
			primaryWa: "Hi! I'd like to book the Ocean Safari La Ventana",
			secondaryLabel: "See what my day looks like",
			secondaryHref: "#itinerario",
		},
		blocks: [
			{
				type: "quickfacts",
				items: [
					{ value: "6 hours", label: "Approx. duration" },
					{ value: "8:00 a.m.", label: "Departure time" },
					{ value: "2-8 people", label: "Shared or private" },
					{ value: "Age 14+", label: "Minimum (shared)" },
				],
			},
			{
				type: "prose",
				kicker: "What the Ocean Safari is",
				heading: "We're not here to tick off stops. We're here to read the sea.",
				paragraphs: [
					"The morning begins in La Ventana, with Cerralvo Island drawing itself in front of us and the team getting the boat ready. We introduce ourselves, check the day's conditions, fit your snorkel gear and talk about the animals we might find. Then we head out toward the channel between the peninsula and Cerralvo Island.",
					{ lead: "From there, the sea is in charge." },
					"We don't follow a tourist route with mandatory stops. We watch birds, currents, splashes, fins, blows and any movement that might reveal activity. We listen to reports from local captains and choose the route with the best chances for that day.",
					"We might start by following a pod of dolphins, change direction for an aggregation of mobula rays, and end up watching a whale on the horizon. There are also quieter days, when it's about navigating, searching and enjoying the landscape with patience.",
					{ lead: "That's a real safari: not knowing exactly what will appear, but being in the right place to discover it." },
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/images/especies/mobulas-bajo-agua.jpg", alt: "Aggregation of mobula rays swimming below the surface in the Gulf of California, La Ventana" },
				quote: "The sea decides what it shows us. We bring the patience to discover it.",
			},
			{
				type: "callout",
				ink2: true,
				heading: "Before you book, there's something important you should know",
				paragraphs: [
					"We work with wild animals in freedom. We don't visit a place where the mobulas, dolphins or whales are waiting: we navigate an open ecosystem, and every encounter depends on the season, the weather, the currents and the animals' natural behavior.",
					"That's why we never promise a specific species or guarantee getting in the water with one. What we do promise is an active search, a team committed to making the most of the conditions, decisions made with safety first, and respectful observation that doesn't interfere with the wildlife.",
					"The sea decides what it shows us. We bring the experience to know how to look for it, and the patience to enjoy it.",
				],
			},
			{
				type: "timeline",
				id: "itinerario",
				kicker: "What your day looks like",
				title: "From the coast to the deep blue",
				note: "Times are approximate. The order of the experience may change depending on the weather, the sea conditions and the wildlife we find.",
				items: [
					{
						time: "Meeting point · La Ventana",
						title: "We meet in La Ventana",
						paragraphs: [
							"The adventure begins at our meeting point in La Ventana. We recommend arriving 15 minutes early to get to know each other, settle your belongings, try on your gear and start the briefing without rushing.",
							"We'll hand you a mask, snorkel, fins and wetsuit. We'll check sizes and explain how to move inside the boat, what signals we'll use and how we'll act if we get in the water. We'll also talk about the animals most present during the season of your visit.",
						],
					},
					{
						time: "8:00 a.m.",
						title: "We leave the coast behind",
						paragraphs: [
							"We board the boat and start heading toward the Cerralvo channel. In the first few minutes you'll begin to understand that looking for wildlife isn't just waiting for something to appear.",
							"We pay attention to feeding birds, changes on the surface, distant blows, shadows under the water and any movement that might signal activity. And yes: often it all starts with someone pointing at the horizon and shouting, \"something jumped over there!\"",
						],
						media: { src: "/images/safari/lancha-avistando-ballena.jpg", alt: "Traveler on the boat watching a whale surface off the coast of La Ventana" },
					},
					{
						title: "The search begins",
						paragraphs: [
							"This is where the fixed route ends. We can cruise the channel, approach different zones around Cerralvo Island, or completely change direction following reports and the signs of the sea.",
							"When we find animals, we first assess their behavior. Some encounters are best enjoyed from the boat; in others, when the species, conditions and safety allow, we get ready to enter the water. Every encounter works differently. That's where the magic is.",
						],
					},
					{
						title: "When the encounter allows getting in the water",
						paragraphs: [
							"Not every sighting turns into snorkeling, and that's intentional. Before getting in we assess the species, the animal's behavior, the current and swell, the group's experience, the presence of other boats and the chance of a safe, respectful approach.",
							"You don't need to be a freediver or an athlete, but you do need to feel comfortable floating and following instructions in the sea. Sometimes the best encounter happens in the water; other times it happens sitting in the boat, watching a whale breathe a few meters away. We never force an interaction just to get a photo.",
						],
						media: { src: "/images/safari/snorkel-lobos-marinos.jpg", alt: "Group of travelers snorkeling next to sea lions at Cerralvo Island, La Ventana" },
					},
					{
						title: "A pause with a taste of Baja",
						paragraphs: [
							"After several hours of navigation we look for a good spot to rest. When conditions allow, we approach a pristine beach or a quiet area to share ceviche, seasonal fruit, snacks and drinks.",
							"It's not a stop at a beach club: no vendors, no rows of loungers. Just the group, the mountains, the island and a meal that tastes much better after a morning of looking for animals.",
						],
						media: { suggest: "Baja-style picnic: ceviche, fruit and drinks served facing the sea on a pristine beach, with the island in the background." },
					},
					{
						time: "≈ 2:00 p.m.",
						title: "The way back counts too",
						paragraphs: [
							"The return to La Ventana is planned for around 2:00 p.m., though the time may vary with conditions. We keep watching the sea the whole way: many encounters appear right when someone had already put the camera away.",
							"Back on shore, we collect the gear and say goodbye with salt in our hair, new stories and, with luck, a memory card that's a good deal fuller than it was in the morning.",
						],
					},
				],
			},
			{
				type: "encounters",
				ink2: true,
				kicker: "What are the encounters really like?",
				title: "Learning to observe is part of the adventure",
				items: [
					{ title: "Dolphins", text: "They may approach the boat, ride alongside the bow or keep their distance. Some pods pass quickly; others seem to have the whole morning free and stay around us for several minutes.", media: { src: "/images/especies/delfin-salto.jpg", alt: "Dolphin leaping beside the boat in the Gulf of California" } },
					{ title: "Mobula rays", text: "We may find them swimming below the surface, gathered in groups or leaping out of the water. The big aggregations are seasonal and their presence can vary even within the best season.", media: { src: "/images/especies/mobula-salto.jpg", alt: "Mobula ray leaping out of the water in La Ventana" } },
					{ title: "Whales", text: "In many cases the first sign is a blow on the horizon. We approach calmly, respect their space and observe their direction, breathing rhythm and behavior.", media: { src: "/images/especies/ballenasaltando2.jpeg", alt: "Whale breaching in the Sea of Cortez" } },
					{ title: "Sea lions", text: "They may appear during navigation or near the coast. Although they tend to be curious, every encounter depends on the place, the season and the day's conditions.", media: { src: "/images/especies/lobomarinonadando.jpeg", alt: "Sea lion swimming in the Gulf of California" } },
					{ title: "Exceptional encounters", text: "Orcas, sperm whales, pilot whales, false killer whales, beaked whales, giant mantas and whale sharks may cross these waters. They're occasional and unpredictable; never a promise, but knowing they roam the Cerralvo channel is part of what makes exploring it so special.", media: { src: "/images/especies/orcalaventana.jpeg", alt: "Orca in the waters of La Ventana, Baja California Sur" } },
					{ title: "Sperm whales", text: "The giants of the deep sometimes cross the Cerralvo channel. Watching them breathe at the surface before a long dive is one of those moments no one forgets.", media: { src: "/images/especies/cachalote-buceo.jpg", alt: "Sperm whale swimming underwater in the Gulf of California" } },
				],
			},
			{
				type: "video",
				kicker: "A minute at sea",
				title: "See it before you live it",
				media: { suggest: "Cinematic 30-60s reel: drone leaving La Ventana, mobulas leaping, entering the water with dolphins, a whale breathing and the sunset on the way back." },
			},
			{
				type: "seasons",
				kicker: "Wildlife and seasons",
				title: "Choose your best time",
				intro: "Marine life changes throughout the year. These references help you choose a season, but no encounter can be guaranteed. For much of the year you may find dolphins, sea lions and seabirds that help us locate activity.",
				items: [
					{ name: "Spring", text: "One of the most special seasons to look for large aggregations of mobula rays. Dolphins, sea lions, blue whale and — extraordinarily — orcas or other large predators may also appear." },
					{ name: "Summer", text: "The mobula season continues and the chance of pelagic activity increases. Dolphins, sea lions, Bryde's whales and, occasionally, sperm whales, orcas and pilot whales may appear." },
					{ name: "Autumn", text: "A lesser-known season, but with interesting chances of finding dolphins, sea lions, birds, giant mantas and sperm whales." },
					{ name: "Winter", text: "The arrival of different whale species transforms the region: humpbacks, blues and fins, plus dolphins and smaller mobula aggregations." },
				],
			},
			{
				type: "mediaSplit",
				reverse: true,
				media: { src: "/images/safari/guia-biologo-camara.jpg", alt: "Keabelmet marine biologist guide photographing wildlife during the safari in La Ventana" },
				kicker: "Who's with you",
				title: "We don't just point at animals. We interpret them.",
				paragraphs: [
					"Every trip is led by a marine biologist who reads the wildlife's behavior and the sea's signs in real time. It's not just a boat ride: it's a reading of the ecosystem by someone who understands and respects it.",
					"You'll ask questions, learn and observe with new eyes. And when you understand what you're seeing, the encounter becomes even more yours.",
				],
			},
			{
				type: "checklist",
				kicker: "Is this adventure for you?",
				title: "So you book with clear expectations",
				good: {
					title: "This safari is for you if…",
					items: [
						"Nature excites you even without a guaranteed outcome.",
						"You prefer small groups and want to learn while you observe.",
						"You enjoy navigating, photography and open landscapes.",
						"It's your first snorkeling experience and you're willing to follow instructions.",
						"You travel solo, as a couple, with friends or family.",
						"You're looking for a day trip near La Paz that feels truly different.",
					],
				},
				bad: {
					title: "It may not be ideal if…",
					items: [
						"You need a guaranteed swim with a specific species.",
						"You don't want to spend several hours on a boat.",
						"You expect a completely rigid route.",
						"You're not comfortable with changes caused by the wind or the sea.",
						"You're looking to touch, feed or chase animals.",
					],
				},
			},
			{
				type: "details",
				kicker: "Everything included",
				title: "What we've already thought of for you",
				items: [
					{ title: "~6-hour marine safari", text: "Boat with a local captain and specialized guide to navigate, search for wildlife and interpret the encounters." },
					{ title: "Marine biologist guide", text: "We don't just point at animals: we explain what we're seeing, how they behave and why this channel gathers so much life." },
					{ title: "Full snorkel gear", text: "Mask, snorkel and fins. We help you choose the size and fit the gear before setting out." },
					{ title: "Wetsuit", text: "Included according to the season and the water temperature." },
					{ title: "Baja-style picnic", text: "Ceviche, seasonal fruit, snacks and drinks to rest and recharge." },
					{ title: "Photos and video", text: "We document the best moments so you don't have to choose between living the encounter and spending the safari behind a screen. Delivered 1 to 3 days later." },
				],
			},
			{
				type: "groups",
				ink2: true,
				kicker: "What to bring",
				title: "Come comfortable. We've thought of the rest.",
				groups: [
					{ name: "Essential", items: ["Swimsuit", "Towel", "Sandals or shoes that can get wet", "Light, comfortable clothing", "A change of dry clothes"] },
					{ name: "Sun protection", items: ["Cap or hat", "Sunglasses with a strap", "Biodegradable sunscreen", "A light long-sleeve layer"] },
					{ name: "Cooler months", items: ["A sweatshirt", "A windbreaker", "Extra dry clothing"] },
					{ name: "For your belongings", items: ["Waterproof phone case", "Small dry bag", "Waterproof camera, if you have one"] },
					{ name: "Highly recommended", items: ["Eat something light beforehand", "Arrive well hydrated", "Seasickness medication if you're prone to it", "Let us know about allergies or medical conditions", "Plenty of adventurous spirit"] },
				],
			},
			{
				type: "info",
				kicker: "Before setting out",
				title: "Practical information",
				items: [
					{ label: "Meeting point", value: "Keabelmet Expeditions, La Ventana. We recommend arriving 15 minutes early." },
					{ label: "Restroom", value: "The boat has no restroom; please use the facilities before the safari begins." },
					{ label: "Transport from La Paz", value: "We can arrange round-trip transport for an extra $1,000 MXN (up to 4 people), subject to availability." },
					{ label: "Food", value: "Ceviche, fruit, snacks and drinks. Let us know in advance about allergies, diets or if you don't eat fish or shrimp." },
					{ label: "Photos and video", value: "Included; usually delivered 1 to 3 days after the safari." },
					{ label: "Minors", value: "On shared trips the minimum age is 14. Children under 14 can join on a private safari, with an adapted pace." },
				],
			},
			{
				type: "gallery",
				ink2: true,
				kicker: "Moments from the safari",
				title: "A day that looks like this",
				cols: 4,
				items: [
					{ src: "/images/orca-safari.jpg", alt: "Navigating in search of wildlife in La Ventana" },
					{ src: "/images/especies/delfinsaltando.jpeg", alt: "Dolphins leaping in the Gulf of California" },
					{ src: "/images/safari/grupo-flotando-isla.jpg", alt: "Group of travelers floating together in the sea with Cerralvo Island behind" },
					{ src: "/images/especies/ballenasaltando2.jpeg", alt: "Whale breaching in the Sea of Cortez" },
					{ src: "/images/safari/snorkel-pulgares.jpg", alt: "Traveler with a snorkel celebrating in the water during the safari" },
					{ src: "/images/especies/lobomarinonadando.jpeg", alt: "Curious sea lion underwater" },
					{ src: "/images/safari/manta-gigante-buceo.jpg", alt: "Giant manta swimming underwater in the Cerralvo channel" },
					{ src: "/images/especies/mobulaschafa.jpeg", alt: "Mobula rays leaping near the boat" },
				],
			},
			{
				type: "pricing",
				id: "precios",
				kicker: "Prices",
				title: "Choose your option",
				cards: [
					{
						name: "Shared safari",
						amountMxn: 3000,
						amountNote: "/ person",
						desc: "Ideal for solo travelers, couples or small groups who want to share the experience with other adventurers.",
						items: [
							"~6-hour safari with captain and marine biologist guide",
							"Snorkel gear and wetsuit",
							"Picnic, fruit, snacks and drinks",
							"Photos and videos",
							"Minimum 4 participants · Age 14+",
						],
						waText: "Hi! I'd like to book the shared Ocean Safari La Ventana",
						ctaLabel: "Find a shared trip",
					},
					{
						name: "Private safari",
						amountMxn: 16000,
						amountNote: "/ boat",
						desc: "An exclusive experience for families, groups of friends, couples or anyone who prefers more privacy and personalized attention.",
						items: [
							"Exclusive boat, up to 8 people",
							"Captain and marine biologist guide",
							"Snorkel gear and wetsuit",
							"Picnic, fruit, snacks and drinks",
							"Photos and videos",
							"The right option for groups with children under 14",
						],
						waText: "Hi! I'd like to book the private Ocean Safari La Ventana",
						ctaLabel: "Book a private safari",
						featured: true,
						featuredTag: "Private",
					},
				],
				note: "Coming from La Paz? We can arrange round-trip transport for an extra $1,000 MXN (up to 4 people), subject to availability.",
			},
			{
				type: "policies",
				ink2: true,
				kicker: "Policies",
				title: "Clear and fair",
				items: [
					{
						title: "Weather policy",
						paragraphs: [
							"Safety always comes before the itinerary. If the captain or team decide that the wind or sea don't allow the activity to run safely, you can reschedule the safari for another available date or receive a full refund.",
							"We can't control the wind, but we can be fair with you.",
						],
					},
					{
						title: "Cancellation policy",
						paragraphs: [
							"If you cancel at least 24 hours in advance, you'll receive a refund.",
							"Cancellations with less than 24 hours' notice are non-refundable —the boat, gear, food and logistics are already prepared— but the amount can be kept as credit for a future activity, subject to availability.",
						],
					},
				],
			},
			{
				type: "faq",
				kicker: "Frequently asked questions",
				title: "Everything you usually want to know",
				items: [
					{ q: "Do I need to know how to swim?", a: ["To enjoy the snorkel entries it's advisable to know how to swim and feel comfortable in open water. You can also stay on the boat during certain encounters. Let us know before booking if someone in the group can't swim so we can assess whether the experience is suitable."] },
					{ q: "Is getting in the water mandatory?", a: ["No. Much of the safari can be enjoyed from the boat; some sightings are even better from the surface. Getting in the water depends on your comfort, the species, the conditions and the guide's assessment."] },
					{ q: "Is it guaranteed we'll see orcas?", a: ["No. Orcas are wild animals and their presence changes daily. There are seasons with better chances, but no specific sighting can be guaranteed. Any company that tells you otherwise is lying to you."] },
					{ q: "Can we swim with all the animals?", a: ["No. Getting in the water depends on the species, its behavior, the conditions, safety and regulations. Swimming with whales and sperm whales is not allowed in Mexican waters. We never force an interaction."] },
					{ q: "When is the best season?", a: ["It depends on what interests you most. Spring and early summer stand out for mobula aggregations; in the cooler months different whales may appear. Dolphins, sea lions and birds can be found for much of the year."] },
					{ q: "Can children take part?", a: ["On shared trips the minimum age is 14. Children under 14 can join on a private safari, where the guide adapts the pace and gives them more attention."] },
					{ q: "What if I get seasick?", a: ["We recommend eating light, staying hydrated and taking preventive measures if you tend to get seasick. Check in advance which medication is right for you and follow the product's or your doctor's instructions."] },
					{ q: "Is there a restroom on the boat?", a: ["No. We recommend using the facilities before setting out, as the experience lasts about six hours."] },
					{ q: "Do you offer transport from La Paz?", a: ["Yes. We can arrange round-trip transport for an extra $1,000 MXN for up to four people. It must be requested in advance and is subject to availability."] },
					{ q: "What if I don't eat fish or shrimp?", a: ["Let us know before the trip so we can review other options. You can also bring your own snacks. Any allergy must be communicated in advance."] },
					{ q: "When will I get my photos and videos?", a: ["Usually 1 to 3 days after the safari, through the channel agreed with the team."] },
					{ q: "Can I bring my camera?", a: ["Yes, at your own risk. We recommend protecting it from the water and securing it well. Space is limited, so let us know if you'll bring large gear; a GoPro, Insta360 or compact camera are no problem."] },
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/images/especies/ballena-atardecer.jpg", alt: "Whale breaching at sunset in the Gulf of California" },
				quote: "You can't always choose the moment that will stay with you. But you almost always leave wanting to come back.",
				align: "bottom",
			},
			{
				type: "prose",
				ink2: true,
				kicker: "Being water and land",
				heading: "We don't just want you to see animals. We want you to understand why they're here.",
				paragraphs: [
					"Keabelmet was born from the curiosity to discover what happens where the desert meets the sea. That's why our trips are led by people who love adventure but also know the biology and behavior of the wildlife we look for.",
					"A dolphin isn't just a fin beside the boat. A mobula isn't just a leap. A whale isn't just a photo. Every behavior tells a story — and when you understand what you're seeing, the encounter becomes even more powerful.",
				],
			},
			{
				type: "finalCta",
				image: "/images/orca-safari.jpg",
				alt: "Mobula rays and dolphins in La Ventana",
				title: "You may set out looking for orcas or mobulas. The sea may have other plans.",
				text: "That's the exciting part. Tell us when you're visiting Baja California Sur and we'll help you choose the best time to live your Ocean Safari in La Ventana and Cerralvo Island.",
				primaryLabel: "Check availability",
				primaryWa: "Hi! I'd like to check availability for the Ocean Safari La Ventana",
				secondaryLabel: "See all expeditions",
				secondaryHref: "/#expediciones",
			},
		],
	},
	"buceo-cabo-pulmo": {
		breadcrumb: "Diving in Cabo Pulmo",
		hero: {
			image: "/coral-reef-underwater-diving-cabo-pulmo-colorful-f.jpg",
			alt: "Living coral reef in Cabo Pulmo National Park",
			kicker: "Cabo Pulmo · National Park",
			title: "There are places where the sea is alive",
			text: "Cabo Pulmo is one of them. A few decades ago this reef was close to disappearing; today it's one of the planet's greatest examples of marine recovery. Here you don't come to look for one particular fish: you come to dive into an ecosystem where thousands of fish move as one.",
			meta: "Cabo Pulmo · ~5 hours · Discovery, certified and snorkel",
			primaryLabel: "Book my dive",
			primaryWa: "Hi! I'd like to book diving in Cabo Pulmo",
			secondaryLabel: "Discover what the day looks like",
			secondaryHref: "#itinerario",
		},
		blocks: [
			{
				type: "quickfacts",
				items: [
					{ value: "~5 hours", label: "Duration" },
					{ value: "8 a.m. · 12 p.m.", label: "Departures" },
					{ value: "2 dives", label: "In the National Park" },
					{ value: "Age 12+", label: "Minimum age" },
				],
			},
			{
				type: "prose",
				kicker: "The reef that came back to life",
				heading: "A village stopped fishing to start protecting. And nature responded.",
				paragraphs: [
					"For many years, Cabo Pulmo was a small fishing village. As happened in so many parts of the world, the reef slowly began to lose life. Until something extraordinary happened: the residents themselves decided to stop making a living from extracting fish and start protecting them.",
					{ lead: "It was an enormous bet. And nature responded." },
					"Decades later, Cabo Pulmo is considered one of the greatest cases of marine recovery on the planet. The reef's biomass grew spectacularly and today thousands of fish, turtles, rays, groupers and huge schools fill these waters again.",
					"When you dive here you don't just visit a National Park: you're stepping into a conservation story that's still being written every day.",
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/buceo-cabo-pulmo-cardumen.jpg", alt: "Massive school of fish moving as one in Cabo Pulmo" },
				quote: "Here the protagonist isn't an animal. It's the sheer amount of life.",
			},
			{
				type: "callout",
				ink2: true,
				heading: "What impresses first isn't a species. It's feeling surrounded by life.",
				paragraphs: [
					"There are dives where a bull shark steals all the attention. In Cabo Pulmo something different happens.",
					"Giant schools that darken the water for a few seconds. Enormous groupers watching from the reef. Turtles that pass slowly, unbothered by our presence. Rays resting on the sand. Thousands of fish moving at the same time, as if they shared a single thought.",
					"And, some days, unexpected visitors that arrive from the open sea to remind us the ocean always holds one more surprise.",
				],
			},
			{
				type: "timeline",
				id: "itinerario",
				kicker: "What your day looks like",
				title: "From the dive center to the reef",
				note: "The order and the sites may change depending on the sea conditions and the National Park's daily assignment.",
				items: [
					{
						time: "Meeting point · Cabo Pulmo",
						title: "We meet in Cabo Pulmo",
						paragraphs: [
							"The experience begins at the dive center. We recommend arriving a few minutes early to check in calmly, review the gear and use the restroom before setting out.",
							"Here you'll meet the divemaster who will be with you throughout the activity. Depending on the option, we'll review the gear, talk through the day's plan and answer any questions before heading to the boat.",
						],
					},
					{
						title: "The briefing",
						paragraphs: [
							"Before entering the water we take the time needed to explain the dive: the assigned site, the sea conditions, the maximum depth, the communication signals and everything you need to enjoy it calmly.",
							"If it's your first dive, here you'll learn to breathe underwater and feel comfortable. If you're already certified but haven't been in the sea for a while, the divemaster will adapt the pace to the group's experience.",
						],
					},
					{
						title: "Heading to the reef",
						paragraphs: [
							"We board the boat and navigate to the assigned site. Here's something few people know: the dive sites aren't chosen freely.",
							"Every morning the National Park holds a draw among the dive centers to distribute the available sites. We can't promise a specific reef — and, curiously, that's one of the reasons Cabo Pulmo stays so healthy. Nature always comes first.",
						],
						media: { suggest: "Divers aboard the panga heading to the dive site, with the desert coast of Cabo Pulmo in the background." },
					},
					{
						title: "The moment of the giant stride",
						paragraphs: [
							"There's a moment every diver remembers. You put on your mask. You breathe deep. You look back. And you roll in.",
							"Suddenly the noise of the world disappears. All that's left are the bubbles, your breathing and a reef that seems to have a life of its own. Throughout the dive we follow the reef's rhythm: we never chase animals, we never rush the experience.",
						],
						media: { src: "/buceo-cabo-pulmo-buzo.jpg", alt: "Diver descending over the Cabo Pulmo reef" },
					},
					{
						title: "Second dive",
						paragraphs: [
							"After a surface interval we do a second tank. The scenery often changes completely: another site, another depth, other wildlife.",
							"Two dives in Cabo Pulmo rarely feel the same. And that's exactly what makes you want to come back.",
						],
					},
				],
			},
			{
				type: "callout",
				heading: "Why don't we promise a specific site? Because it wouldn't be honest.",
				paragraphs: [
					"Every morning the National Park assigns the dive sites through a rotation and draw system among all authorized operators. This management reduces pressure on the reef and helps conserve one of the most important marine ecosystems in the Gulf of California.",
					"In other words: the fact that we can't choose just any site is precisely one of the reasons Cabo Pulmo remains so spectacular.",
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/coral-reef-underwater-cabo-pulmo-colorful-tropical.jpg", alt: "Colorful coral reef in Cabo Pulmo" },
				quote: "Every descent is different. So is every breath underwater.",
			},
			{
				type: "fauna",
				ink2: true,
				kicker: "Wildlife",
				title: "The reef changes every day",
				note: "We can't guarantee any species. We can guarantee that every dive happens inside one of the healthiest reefs on the planet.",
				tiers: [
					{ label: "For much of the year", species: ["Jacks", "Snappers", "Giant groupers", "Sea turtles", "Rays", "Reef fish"] },
					{ label: "Some days visitors arrive", warn: true, species: ["Bull shark", "Mobula rays", "Dolphins", "Humpback whale", "Whale shark", "Tiger shark"] },
				],
			},
			{
				type: "video",
				kicker: "A minute underwater",
				title: "See it before you live it",
				media: { suggest: "Cinematic 30-60s reel: the giant stride into the water, a school enveloping the diver, a giant grouper, a turtle crossing the reef and bubbles rising to the surface." },
			},
			{
				type: "details",
				kicker: "Which option is for you?",
				title: "Three ways to experience the reef",
				items: [
					{ title: "Discovery", text: "Never dived before? Discover what it feels like to breathe underwater. No prior experience needed: you'll do two dives always accompanied by a certified instructor." },
					{ title: "Certified diving", text: "If you hold an Open Water certification or higher, you'll do two dives adapted to the group's experience. It doesn't matter if it's been a while: the divemaster will adjust the pace." },
					{ title: "Snorkel", text: "If you prefer to stay at the surface, you can also explore Cabo Pulmo snorkeling. Snorkel groups usually go on a separate boat to make the most of everyone's time; if you'd rather stay together, let us know in advance." },
				],
			},
			{
				type: "details",
				ink2: true,
				kicker: "Everything included",
				title: "What's already taken care of",
				items: [
					{ title: "Two dives", text: "In Discovery mode or for certified divers, at the sites assigned for the day." },
					{ title: "Full diving gear", text: "All the equipment needed for the dive." },
					{ title: "Certified instructor or divemaster", text: "Accompanies you and adapts the pace to the group's experience." },
					{ title: "Boat and local captain", text: "With knowledge of the park and its conditions." },
					{ title: "Safety briefing", text: "A full explanation before entering the water and site selection based on conditions." },
					{ title: "Snacks and water", text: "Hydration and something light on board during the trip." },
				],
			},
			{
				type: "info",
				kicker: "Before booking",
				title: "Important information",
				items: [
					{ label: "Minimum age", value: "12 years old." },
					{ label: "Minimum certification", value: "Open Water for the certified diving option." },
					{ label: "Photos and video", value: "This activity does not include photo or video service." },
					{ label: "Transport", value: "We don't offer transport from La Paz to Cabo Pulmo." },
					{ label: "Restrooms", value: "The dive center has restrooms before setting out. The boat has no restroom, so we recommend using the facilities before boarding." },
				],
			},
			{
				type: "pricing",
				id: "precios",
				kicker: "Prices",
				title: "Choose your experience in Cabo Pulmo",
				cards: [
					{
						name: "Discovery",
						amountMxn: 3800,
						amountNote: "/ person",
						desc: "Your first breath underwater, with two dives accompanied at all times by a certified instructor.",
						items: [
							"Two guided dives",
							"No prior experience needed",
							"Full diving gear",
							"Certified instructor throughout the activity",
							"Snacks and water on board",
						],
						waText: "Hi! I'd like to book a Discovery dive in Cabo Pulmo",
						ctaLabel: "Book my Discovery",
					},
					{
						name: "Certified diving",
						amountMxn: 3200,
						amountNote: "/ person",
						desc: "Two dives for Open Water divers or higher, adapted to the group's experience.",
						items: [
							"Two dives on the reef",
							"Requires Open Water certification or higher",
							"Full diving gear",
							"Certified divemaster",
							"Snacks and water on board",
						],
						waText: "Hi! I'd like to book certified diving in Cabo Pulmo",
						ctaLabel: "Book certified diving",
						featured: true,
						featuredTag: "Certified",
					},
					{
						name: "Snorkel",
						amountMxn: 1500,
						amountNote: "/ person",
						desc: "Explore the reef from the surface accompanied by a guide.",
						items: [
							"Guided snorkel tour",
							"Ideal for those who prefer not to dive",
							"Snorkel gear",
							"Guide throughout the activity",
						],
						waText: "Hi! I'd like to book snorkeling in Cabo Pulmo",
						ctaLabel: "Book snorkel",
					},
				],
			},
			{
				type: "policies",
				ink2: true,
				kicker: "Policies",
				title: "Clear and fair",
				items: [
					{
						title: "Weather policy",
						paragraphs: [
							"If the weather doesn't allow the activity to run safely, you can choose to reschedule your trip or receive a full refund. Safety always comes before the itinerary.",
						],
					},
					{
						title: "Cancellation policy",
						paragraphs: [
							"If you cancel more than 24 hours in advance, you can request a refund or keep your payment as credit for a future experience with Keabelmet.",
						],
					},
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/images/buceo-cabo-pulmo.jpeg", alt: "Diver exploring the reef of Cabo Pulmo National Park" },
				quote: "You can't always choose the moment that will stay with you. But you almost always leave wanting to come back.",
				align: "bottom",
			},
			{
				type: "finalCta",
				image: "/buceo-cabo-pulmo-cardumen.jpg",
				alt: "Massive school of fish on the Cabo Pulmo reef",
				title: "You might remember a bull shark. Or a school of thousands of fish moving as one.",
				text: "That's Cabo Pulmo. Tell us when you're visiting Baja California Sur and we'll help you choose the best day to dive one of the most alive reefs on the planet.",
				primaryLabel: "Check availability",
				primaryWa: "Hi! I'd like to check availability for diving in Cabo Pulmo",
				secondaryLabel: "See all expeditions",
				secondaryHref: "/#expediciones",
			},
		],
	},
	"tiburon-ballena": {
		breadcrumb: "Whale Shark",
		hero: {
			image: "/tiburon-ballena-drone.jpg",
			alt: "Whale shark swimming near the surface in La Paz",
			kicker: "La Paz · Whale Shark",
			title: "Swim beside the largest fish on the planet",
			text: "Not to chase it. Not to touch it. Simply to keep it company for a few minutes. The whale shark can exceed ten meters and still feed on tiny organisms. Sharing the water with it doesn't feel like an extreme adventure: it feels like a privilege.",
			meta: "La Paz malecón · 2-3 hours · Oct–April season",
			primaryLabel: "Book my encounter",
			primaryWa: "Hi! I'd like to book swimming with whale sharks in La Paz",
			secondaryLabel: "See what the experience is like",
			secondaryHref: "#itinerario",
		},
		blocks: [
			{
				type: "quickfacts",
				items: [
					{ value: "2-3 hours", label: "Approx. duration" },
					{ value: "Oct – April", label: "Season" },
					{ value: "Age 12+", label: "Minimum age" },
					{ value: "La Paz malecón", label: "Meeting point" },
				],
			},
			{
				type: "prose",
				kicker: "The ocean's most gentle giant",
				heading: "Its real defining trait isn't its size. It's its calm.",
				paragraphs: [
					"Some animals inspire respect for their size. The whale shark does too. But a few seconds are enough to discover that what's impressive isn't how big it is, but how calm it is.",
					"It swims slowly. It ignores our presence. And it continues on its way, feeding on plankton near the surface.",
					{ lead: "We're not facing a predator. We're facing one of the most peaceful animals in the ocean." },
					"For a few minutes we can keep it company, always respecting its space and the rules that make this encounter possible.",
				],
			},
			{
				type: "mediaBanner",
				media: { suggest: "Giant overhead photo of the whale shark spanning the full width of the screen, with a small swimmer beside it for scale." },
				quote: "You don't have to touch something to remember it for a lifetime.",
			},
			{
				type: "timeline",
				id: "itinerario",
				kicker: "What the experience is like",
				title: "From the malecón to the encounter",
				note: "We don't follow a set route: we look for the best conditions and the animals feeding near the surface.",
				items: [
					{
						time: "Meeting point · La Paz malecón",
						title: "We meet and do the briefing",
						paragraphs: [
							"After meeting the team we do a short briefing where we explain how the activity will unfold, review the rules of the protected area and answer any questions before boarding.",
						],
					},
					{
						title: "The search begins",
						paragraphs: [
							"Once on the water the search begins. We don't follow a fixed route: we locate the animals feeding near the surface. When we find one, we wait our turn and get ready to enter the water.",
						],
						media: { suggest: "View from the boat of the guide pointing out a whale shark's fin at the surface, with the group ready with snorkels." },
					},
					{
						title: "A few minutes beside the giant",
						paragraphs: [
							"Then comes what everyone comes for. For a few minutes we swim beside the whale shark, always respecting the permitted distance and following the guide's instructions. Then we climb back aboard and begin the search again.",
							"Each encounter is brief. But very few people forget it.",
						],
						media: { suggest: "Snorkeler at a respectful distance beside the whale shark, shot from the surface with turquoise light." },
					},
				],
			},
			{
				type: "seasons",
				ink2: true,
				kicker: "Choose your departure",
				title: "Three departures a day depending on conditions",
				intro: "We offer three departure times during the season to make the most of the day's conditions. No time is better than another: each one unfolds differently, following the animals' natural behavior.",
				items: [
					{ name: "Early departure · our recommendation", text: "Meet 7:00 a.m., depart 8:00 a.m. About 3 hours. It's the longest trip of the day: as the first outing, part of the experience is locating the sharks before the water entries. If you have flexibility, it's the one we recommend most." },
					{ name: "Mid-morning departure", text: "Meet 10:00 a.m., depart 11:00 a.m. About 2 hours. The sharks are usually better located thanks to the first departure, so search time is shorter and the experience is better used." },
					{ name: "Midday departure", text: "Meet 12:00 p.m., depart 1:00 p.m. About 2 hours. Same dynamic as the second slot: the animals are usually already located, letting us head faster to the observation area." },
				],
			},
			{
				type: "callout",
				heading: "We don't come to chase animals. We come to share the water with them.",
				paragraphs: [
					"When we enter the water, we're the ones who must adapt. We never block its path. We never swim in front of it. We never try to touch it.",
					"We simply keep it company for a very small part of its journey. And we believe that's the best way to live this experience.",
				],
			},
			{
				type: "callout",
				ink2: true,
				heading: "Why is the encounter so short? Because protecting the whale shark matters more than prolonging the experience.",
				paragraphs: [
					"The activity is regulated by environmental authorities that limit observation time, the number of boats and how we can approach.",
					"Far from being an inconvenience, these rules are what allow thousands of people to keep enjoying this encounter every season. You don't just come to meet the whale shark: you also come to learn how to coexist with it responsibly.",
				],
			},
			{
				type: "prose",
				kicker: "Every day is different",
				heading: "We work with completely free animals.",
				paragraphs: [
					"Some days we find several individuals. Others we have to search longer. Some swim slowly while feeding; others disappear underwater seconds after we find them.",
					{ lead: "We believe that uncertainty makes every encounter even more valuable." },
				],
			},
			{
				type: "checklist",
				kicker: "Is it for me?",
				title: "So you book with clear expectations",
				good: {
					title: "This experience is ideal if…",
					items: [
						"You've always dreamed of swimming beside a whale shark.",
						"You have no prior snorkeling experience.",
						"You want a responsible encounter with wildlife.",
						"You're looking for an activity suitable for almost the whole family.",
					],
				},
				bad: {
					title: "It may not be for you if…",
					items: [
						"You expect to control the animals' behavior.",
						"You're looking for an experience where everything is guaranteed.",
					],
				},
			},
			{
				type: "details",
				kicker: "Everything included",
				title: "What's already taken care of",
				items: [
					{ title: "Authorized boat", text: "With a permit for the activity in the protected area." },
					{ title: "Certified guide", text: "Accompanies you and explains the rules of the encounter at all times." },
					{ title: "Full snorkel gear", text: "Mask, snorkel and fins." },
					{ title: "Wetsuit", text: "Included according to the season and water temperature." },
					{ title: "Flotation vest", text: "So you can enjoy the encounter with complete peace of mind." },
					{ title: "Safety briefing", text: "A full explanation before entering the water." },
				],
			},
			{
				type: "info",
				ink2: true,
				kicker: "Before booking",
				title: "Important information",
				items: [
					{ label: "Duration", value: "Approximately 2-3 hours depending on the departure." },
					{ label: "Season", value: "From October to April." },
					{ label: "Minimum age", value: "12 years old." },
					{ label: "Meeting point", value: "La Paz malecón." },
					{ label: "Photos and video", value: "This activity does not include photo or video service." },
				],
			},
			{
				type: "pricing",
				id: "precios",
				kicker: "Price",
				title: "Book your encounter",
				cards: [
					{
						name: "Swim with whale sharks",
						amountMxn: 1800,
						amountNote: "/ person",
						desc: "An experience suitable for almost the whole family, with no prior snorkeling experience needed.",
						items: [
							"Authorized boat and certified guide",
							"Full snorkel gear and wetsuit",
							"Flotation vest",
							"Safety briefing",
							"Season from October to April",
						],
						waText: "Hi! I'd like to book swimming with whale sharks in La Paz",
						ctaLabel: "Book my encounter",
						featured: true,
						featuredTag: "Oct – April",
					},
				],
			},
			{
				type: "mediaBanner",
				media: { suggest: "Silhouette of the whale shark seen from below against the surface light, a sense of calm and scale." },
				quote: "You may arrive thinking about its size. But you'll probably leave remembering its calm.",
				align: "bottom",
			},
			{
				type: "finalCta",
				image: "/tiburon-ballena-drone.jpg",
				alt: "Whale shark in the waters of La Paz",
				title: "Some encounters last a few minutes and still stay with you for many years.",
				text: "When you share the water with the largest fish on the planet, you discover that some of the ocean's most impressive creatures can also be the most peaceful. Tell us when you're visiting La Paz and we'll help you choose your departure.",
				primaryLabel: "Check availability",
				primaryWa: "Hi! I'd like to check availability to swim with whale sharks",
				secondaryLabel: "See all expeditions",
				secondaryHref: "/#expediciones",
			},
		],
	},
}
