import type { StoryPageData } from "@/components/StoryPage"

/**
 * Contenu narratif (fr) des pages d'expédition. Les slugs présents ici sont
 * rendus avec StoryPage en français ; les autres retombent sur le modèle
 * compact ExpeditionDetail.
 */
export const storyPagesFr: Record<string, StoryPageData> = {
	"safari-la-ventana": {
		breadcrumb: "Ocean Safari La Ventana",
		hero: {
			image: "/images/orca-safari.jpg",
			alt: "Ocean Safari à La Ventana et à l'île Cerralvo",
			kicker: "La Ventana · Île Cerralvo",
			title: "Ocean Safari La Ventana",
			text: "Explorez les eaux autour de l'île Cerralvo à la recherche de raies mobula, de dauphins, de baleines et d'autres habitants du golfe de Californie, aux côtés d'un guide biologiste marin et de capitaines qui connaissent ces eaux par cœur. Chaque sortie est différente. Chaque rencontre est réelle.",
			meta: "La Ventana · ~6 heures · Groupes jusqu'à 8 personnes",
			primaryLabel: "Réserver mon aventure",
			primaryWa: "Bonjour! Je voudrais réserver l'Ocean Safari La Ventana",
			secondaryLabel: "Découvrir le déroulement de ma journée",
			secondaryHref: "#itinerario",
		},
		blocks: [
			{
				type: "quickfacts",
				items: [
					{ value: "6 heures", label: "Durée approx." },
					{ value: "8h00", label: "Heure de départ" },
					{ value: "2-8 personnes", label: "Partagé ou privé" },
					{ value: "14 ans", label: "Âge minimum (partagé)" },
				],
			},
			{
				type: "prose",
				kicker: "Qu'est-ce que l'Ocean Safari",
				heading: "Ici, on ne vient pas cocher des étapes. On vient lire la mer.",
				paragraphs: [
					"La matinée commence à La Ventana, avec l'île Cerralvo qui se dessine devant nous et l'équipe qui prépare le bateau. Nous nous présentons, vérifions les conditions du jour, ajustons votre équipement de snorkeling et parlons des animaux que nous pourrions rencontrer. Puis nous partons vers le chenal qui sépare la péninsule de l'île Cerralvo.",
					{ lead: "À partir de là, c'est la mer qui décide." },
					"Nous ne suivons pas un itinéraire touristique avec des arrêts obligatoires. Nous observons les oiseaux, les courants, les éclaboussures, les nageoires, les souffles et tout mouvement pouvant révéler une activité. Nous écoutons les rapports des capitaines locaux et choisissons la route qui offre les meilleures chances ce jour-là.",
					"Nous pouvons commencer en suivant un groupe de dauphins, changer de direction pour une agrégation de raies mobula et finir par observer une baleine à l'horizon. Il y a aussi des journées plus calmes, où il s'agit de naviguer, de chercher et de profiter du paysage avec patience.",
					{ lead: "C'est ça, un vrai safari : ne pas savoir exactement ce qui va apparaître, mais être au bon endroit pour le découvrir." },
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/images/especies/mobulas-bajo-agua.jpg", alt: "Agrégation de raies mobula nageant sous la surface dans le golfe de Californie, La Ventana" },
				quote: "La mer décide ce qu'elle nous montre. Nous apportons la patience pour le découvrir.",
			},
			{
				type: "callout",
				ink2: true,
				heading: "Avant de réserver, voici quelque chose d'important à savoir",
				paragraphs: [
					"Nous travaillons avec des animaux sauvages en liberté. Nous ne visitons pas un endroit où les raies mobula, les dauphins ou les baleines nous attendent : nous naviguons dans un écosystème ouvert, et chaque rencontre dépend de la saison, de la météo, des courants et du comportement naturel des animaux.",
					"C'est pourquoi nous ne promettons jamais une espèce précise ni ne garantissons d'entrer dans l'eau avec elle. Ce que nous promettons, c'est une recherche active, une équipe engagée à tirer le meilleur parti des conditions, des décisions prises en donnant toujours la priorité à la sécurité, et une observation respectueuse qui n'interfère pas avec la faune.",
					"La mer décide ce qu'elle nous montre. Nous apportons l'expérience pour savoir la chercher, et la patience pour en profiter.",
				],
			},
			{
				type: "timeline",
				id: "itinerario",
				kicker: "Le déroulement de votre journée",
				title: "De la côte au grand bleu",
				note: "Les horaires sont approximatifs. L'ordre de l'expérience peut changer selon la météo, l'état de la mer et la faune que nous rencontrons.",
				items: [
					{
						time: "Point de rendez-vous · La Ventana",
						title: "Nous nous retrouvons à La Ventana",
						paragraphs: [
							"L'aventure commence à notre point de rendez-vous à La Ventana. Nous vous recommandons d'arriver 15 minutes à l'avance pour faire connaissance, ranger vos affaires, essayer votre équipement et commencer le briefing sans précipitation.",
							"Nous vous remettrons masque, tuba, palmes et combinaison. Nous vérifierons les tailles et vous expliquerons comment vous déplacer dans le bateau, quels signaux nous utiliserons et comment agir si nous entrons dans l'eau. Nous parlerons aussi des animaux les plus présents durant la saison de votre visite.",
						],
					},
					{
						time: "8h00",
						title: "Nous laissons la côte derrière nous",
						paragraphs: [
							"Nous montons à bord et commençons à naviguer vers le chenal de Cerralvo. Dès les premières minutes, vous comprendrez que chercher la faune ne consiste pas simplement à attendre que quelque chose apparaisse.",
							"Nous prêtons attention aux oiseaux qui se nourrissent, aux changements à la surface, aux souffles au loin, aux ombres sous l'eau et à tout mouvement pouvant indiquer une activité. Et oui : souvent, tout commence par quelqu'un qui pointe l'horizon en criant : « Quelque chose a sauté là-bas ! »",
						],
						media: { src: "/images/safari/lancha-avistando-ballena.jpg", alt: "Voyageur sur le bateau observant une baleine faire surface au large de La Ventana" },
					},
					{
						title: "La recherche commence",
						paragraphs: [
							"Ici se termine l'itinéraire fixe. Nous pouvons parcourir le chenal, nous approcher de différentes zones autour de l'île Cerralvo, ou changer complètement de direction en suivant les rapports et les signes de la mer.",
							"Quand nous trouvons des animaux, nous évaluons d'abord leur comportement. Certaines rencontres se savourent mieux depuis le bateau ; pour d'autres, quand l'espèce, les conditions et la sécurité le permettent, nous nous préparons à entrer dans l'eau. Chaque rencontre est différente. C'est là que réside la magie.",
						],
					},
					{
						title: "Quand la rencontre permet d'entrer dans l'eau",
						paragraphs: [
							"Toutes les observations ne se transforment pas en séance de snorkeling, et c'est intentionnel. Avant d'entrer, nous évaluons l'espèce, le comportement de l'animal, le courant et la houle, l'expérience du groupe, la présence d'autres bateaux et la possibilité d'une approche sûre et respectueuse.",
							"Vous n'avez pas besoin d'être apnéiste ni athlète, mais vous devez vous sentir à l'aise en flottant et suivre les indications en mer. Parfois, la meilleure rencontre se vit dans l'eau ; d'autres fois, assis dans le bateau, à regarder une baleine respirer à quelques mètres. Nous ne forçons jamais une interaction juste pour obtenir une photo.",
						],
						media: { src: "/images/safari/snorkel-lobos-marinos.jpg", alt: "Groupe de voyageurs faisant du snorkeling avec des otaries à l'île Cerralvo, La Ventana" },
					},
					{
						title: "Une pause au goût de Baja",
						paragraphs: [
							"Après plusieurs heures de navigation, nous cherchons un bon endroit pour nous reposer. Quand les conditions le permettent, nous nous approchons d'une plage préservée ou d'une zone calme pour partager ceviche, fruits de saison, snacks et boissons.",
							"Ce n'est pas un arrêt dans un club de plage : pas de vendeurs, pas de rangées de transats. Juste le groupe, les montagnes, l'île et un repas qui a bien meilleur goût après une matinée à chercher des animaux.",
						],
						media: { suggest: "Pique-nique style Baja : ceviche, fruits et boissons servis face à la mer sur une plage préservée, avec l'île en arrière-plan." },
					},
					{
						time: "≈ 14h00",
						title: "Le retour compte aussi",
						paragraphs: [
							"Le retour à La Ventana est prévu vers 14h00, bien que l'heure puisse varier selon les conditions. Nous continuons à observer la mer tout le long du trajet : de nombreuses rencontres surviennent juste au moment où quelqu'un venait de ranger son appareil photo.",
							"De retour à terre, nous récupérons l'équipement et nous nous quittons avec du sel dans les cheveux, de nouvelles histoires et, avec un peu de chance, une carte mémoire nettement plus pleine que le matin.",
						],
					},
				],
			},
			{
				type: "encounters",
				ink2: true,
				kicker: "À quoi ressemblent vraiment les rencontres ?",
				title: "Apprendre à observer fait partie de l'aventure",
				items: [
					{ title: "Dauphins", text: "Ils peuvent s'approcher du bateau, nager le long de la proue ou garder leurs distances. Certains groupes passent rapidement ; d'autres semblent avoir toute la matinée devant eux et restent plusieurs minutes autour de nous.", media: { src: "/images/especies/delfin-salto.jpg", alt: "Dauphin bondissant près du bateau dans le golfe de Californie" } },
					{ title: "Raies mobula", text: "Nous pouvons les trouver nageant sous la surface, rassemblées en groupes ou sautant hors de l'eau. Les grandes agrégations sont saisonnières et leur présence peut varier même durant la meilleure saison.", media: { src: "/images/especies/mobula-salto.jpg", alt: "Raie mobula bondissant hors de l'eau à La Ventana" } },
					{ title: "Baleines", text: "Dans de nombreux cas, le premier indice est un souffle à l'horizon. Nous nous approchons calmement, respectons leur espace et observons leur direction, leur rythme de respiration et leur comportement.", media: { src: "/images/especies/ballenasaltando2.jpeg", alt: "Baleine bondissant dans la mer de Cortez" } },
					{ title: "Otaries", text: "Elles peuvent apparaître pendant la navigation ou près de la côte. Bien qu'elles soient généralement curieuses, chaque rencontre dépend du lieu, de la saison et des conditions du jour.", media: { src: "/images/especies/lobomarinonadando.jpeg", alt: "Otarie nageant dans le golfe de Californie" } },
					{ title: "Rencontres exceptionnelles", text: "Orques, cachalots, globicéphales, fausses orques, baleines à bec, mantas géantes et requins-baleines peuvent traverser ces eaux. Ce sont des rencontres occasionnelles et imprévisibles ; jamais une promesse, mais savoir qu'ils parcourent le chenal de Cerralvo fait partie de ce qui rend son exploration si spéciale.", media: { src: "/images/especies/orcalaventana.jpeg", alt: "Orque dans les eaux de La Ventana, Basse-Californie du Sud" } },
					{ title: "Cachalots", text: "Les géants des profondeurs traversent parfois le chenal de Cerralvo. Les voir respirer à la surface avant une longue plongée est un de ces moments que personne n'oublie.", media: { src: "/images/especies/cachalote-buceo.jpg", alt: "Cachalot nageant sous l'eau dans le golfe de Californie" } },
				],
			},
			{
				type: "video",
				kicker: "Une minute en mer",
				title: "Regardez avant de le vivre",
				media: { suggest: "Vidéo cinématographique de 30-60s : drone quittant La Ventana, raies mobula bondissantes, entrée dans l'eau avec des dauphins, une baleine qui respire et le coucher de soleil du retour." },
			},
			{
				type: "seasons",
				kicker: "Faune et saisons",
				title: "Choisissez votre meilleur moment",
				intro: "La vie marine change au fil de l'année. Ces repères vous aident à choisir une saison, mais aucune rencontre ne peut être garantie. Pendant une grande partie de l'année, des dauphins, des otaries et des oiseaux marins peuvent apparaître et nous aider à localiser l'activité.",
				items: [
					{ name: "Printemps", text: "L'une des saisons les plus spéciales pour rechercher de grandes agrégations de raies mobula. Des dauphins, otaries, baleines bleues et, exceptionnellement, des orques ou d'autres grands prédateurs peuvent aussi apparaître." },
					{ name: "Été", text: "La saison des mobula continue et les chances d'activité pélagique augmentent. Des dauphins, otaries, rorquals de Bryde et, occasionnellement, des cachalots, orques et globicéphales peuvent apparaître." },
					{ name: "Automne", text: "Une saison moins connue, mais avec des possibilités intéressantes de trouver des dauphins, otaries, oiseaux, mantas géantes et cachalots." },
					{ name: "Hiver", text: "L'arrivée de différentes espèces de baleines transforme la région : baleines à bosse, bleues et communes, ainsi que des dauphins et de petites agrégations de raies mobula." },
				],
			},
			{
				type: "mediaSplit",
				reverse: true,
				media: { src: "/images/safari/guia-biologo-camara.jpg", alt: "Guide biologiste marin de Keabelmet photographiant la faune pendant le safari à La Ventana" },
				kicker: "Qui vous accompagne",
				title: "Nous ne faisons pas que montrer les animaux. Nous les interprétons.",
				paragraphs: [
					"Chaque sortie est menée par un biologiste marin qui lit le comportement de la faune et les signes de la mer en temps réel. Ce n'est pas une simple balade en bateau : c'est une lecture de l'écosystème par quelqu'un qui le comprend et le respecte.",
					"Vous allez poser des questions, apprendre et observer avec un regard neuf. Et quand vous comprenez ce que vous voyez, la rencontre devient encore plus la vôtre.",
				],
			},
			{
				type: "checklist",
				kicker: "Cette aventure est-elle pour vous ?",
				title: "Pour réserver avec des attentes claires",
				good: {
					title: "Ce safari est pour vous si…",
					items: [
						"La nature vous passionne même sans résultat garanti.",
						"Vous préférez les petits groupes et voulez apprendre en observant.",
						"Vous aimez naviguer, la photographie et les paysages ouverts.",
						"C'est votre première expérience de snorkeling et vous êtes prêt à suivre les consignes.",
						"Vous voyagez seul, en couple, entre amis ou en famille.",
						"Vous cherchez une excursion d'une journée près de La Paz qui sorte vraiment de l'ordinaire.",
					],
				},
				bad: {
					title: "Ce n'est peut-être pas idéal si…",
					items: [
						"Vous avez besoin de nager avec une espèce précise garantie.",
						"Vous ne voulez pas passer plusieurs heures en bateau.",
						"Vous attendez un itinéraire complètement rigide.",
						"Vous n'êtes pas à l'aise avec les changements dus au vent ou à la mer.",
						"Vous cherchez à toucher, nourrir ou poursuivre les animaux.",
					],
				},
			},
			{
				type: "details",
				kicker: "Tout ce qui est inclus",
				title: "Ce à quoi nous avons déjà pensé pour vous",
				items: [
					{ title: "Safari marin de ~6 heures", text: "Bateau avec capitaine local et guide spécialisé pour naviguer, chercher la faune et interpréter les rencontres." },
					{ title: "Guide biologiste marin", text: "Nous ne faisons pas que montrer les animaux : nous vous expliquons ce que nous voyons, comment ils se comportent et pourquoi ce chenal rassemble tant de vie." },
					{ title: "Équipement complet de snorkeling", text: "Masque, tuba et palmes. Nous vous aidons à choisir la taille et à ajuster l'équipement avant de partir." },
					{ title: "Combinaison néoprène", text: "Incluse selon la saison et la température de l'eau." },
					{ title: "Pique-nique style Baja", text: "Ceviche, fruits de saison, snacks et boissons pour se reposer et reprendre des forces." },
					{ title: "Photos et vidéo", text: "Nous documentons les meilleurs moments pour que vous n'ayez pas à choisir entre vivre la rencontre et passer le safari derrière un écran. Livrées 1 à 3 jours après." },
				],
			},
			{
				type: "groups",
				ink2: true,
				kicker: "Quoi apporter",
				title: "Venez à l'aise. Nous avons pensé au reste.",
				groups: [
					{ name: "Essentiel", items: ["Maillot de bain", "Serviette", "Sandales ou chaussures pouvant se mouiller", "Vêtements légers et confortables", "Vêtements de rechange secs"] },
					{ name: "Protection solaire", items: ["Casquette ou chapeau", "Lunettes de soleil avec cordon", "Crème solaire biodégradable", "Vêtement léger à manches longues"] },
					{ name: "Mois frais", items: ["Sweat-shirt", "Coupe-vent", "Vêtements secs supplémentaires"] },
					{ name: "Pour vos affaires", items: ["Housse étanche pour téléphone", "Petit sac étanche", "Caméra étanche, si vous en avez une"] },
					{ name: "Vivement recommandé", items: ["Manger léger avant de partir", "Arriver bien hydraté", "Médicament contre le mal de mer si vous y êtes sujet", "Nous informer d'allergies ou de conditions médicales", "Beaucoup d'esprit d'aventure"] },
				],
			},
			{
				type: "info",
				kicker: "Avant de partir",
				title: "Informations pratiques",
				items: [
					{ label: "Point de rendez-vous", value: "Keabelmet Expeditions, La Ventana. Nous recommandons d'arriver 15 minutes à l'avance." },
					{ label: "Toilettes", value: "Le bateau n'a pas de toilettes ; utilisez les sanitaires avant de commencer le safari." },
					{ label: "Transport depuis La Paz", value: "Nous pouvons organiser un transport aller-retour pour 1 000 MXN supplémentaires (jusqu'à 4 personnes), selon disponibilité." },
					{ label: "Repas", value: "Ceviche, fruits, snacks et boissons. Prévenez-nous à l'avance en cas d'allergies, de régime particulier ou si vous ne mangez pas de poisson ou de crevettes." },
					{ label: "Photos et vidéo", value: "Incluses ; généralement livrées 1 à 3 jours après le safari." },
					{ label: "Mineurs", value: "Sur les sorties partagées, l'âge minimum est de 14 ans. Les moins de 14 ans peuvent participer à un safari privé, à un rythme adapté." },
				],
			},
			{
				type: "gallery",
				ink2: true,
				kicker: "Moments du safari",
				title: "Une journée qui ressemble à ça",
				cols: 4,
				items: [
					{ src: "/images/orca-safari.jpg", alt: "Navigation à la recherche de faune à La Ventana" },
					{ src: "/images/especies/delfinsaltando.jpeg", alt: "Dauphins bondissant dans le golfe de Californie" },
					{ src: "/images/safari/grupo-flotando-isla.jpg", alt: "Groupe de voyageurs flottant ensemble en mer avec l'île Cerralvo en arrière-plan" },
					{ src: "/images/especies/ballenasaltando2.jpeg", alt: "Baleine bondissant dans la mer de Cortez" },
					{ src: "/images/safari/snorkel-pulgares.jpg", alt: "Voyageuse avec tuba célébrant dans l'eau pendant le safari" },
					{ src: "/images/especies/lobomarinonadando.jpeg", alt: "Otarie curieuse sous l'eau" },
					{ src: "/images/safari/manta-gigante-buceo.jpg", alt: "Manta géante nageant sous l'eau dans le chenal de Cerralvo" },
					{ src: "/images/especies/mobulaschafa.jpeg", alt: "Raies mobula bondissant près du bateau" },
				],
			},
			{
				type: "pricing",
				id: "precios",
				kicker: "Tarifs",
				title: "Choisissez votre formule",
				cards: [
					{
						name: "Safari partagé",
						amountMxn: 3000,
						amountNote: "/ personne",
						desc: "Idéal pour les voyageurs seuls, les couples ou les petits groupes qui veulent partager l'expérience avec d'autres aventuriers.",
						items: [
							"Safari de ~6 heures avec capitaine et guide biologiste marin",
							"Équipement de snorkeling et combinaison",
							"Pique-nique, fruits, snacks et boissons",
							"Photos et vidéos",
							"Minimum 4 participants · Âge minimum 14 ans",
						],
						waText: "Bonjour! Je voudrais réserver l'Ocean Safari La Ventana partagé",
						ctaLabel: "Trouver une sortie partagée",
					},
					{
						name: "Safari privé",
						amountMxn: 16000,
						amountNote: "/ bateau",
						desc: "Une expérience exclusive pour les familles, les groupes d'amis, les couples ou ceux qui préfèrent plus d'intimité et une attention personnalisée.",
						items: [
							"Bateau exclusif, jusqu'à 8 personnes",
							"Capitaine et guide biologiste marin",
							"Équipement de snorkeling et combinaison",
							"Pique-nique, fruits, snacks et boissons",
							"Photos et vidéos",
							"L'option adaptée pour les groupes avec des moins de 14 ans",
						],
						waText: "Bonjour! Je voudrais réserver l'Ocean Safari La Ventana privé",
						ctaLabel: "Réserver un safari privé",
						featured: true,
						featuredTag: "Privé",
					},
				],
				note: "Vous venez de La Paz ? Nous pouvons organiser un transport aller-retour pour 1 000 MXN supplémentaires (jusqu'à 4 personnes), selon disponibilité.",
			},
			{
				type: "policies",
				ink2: true,
				kicker: "Politiques",
				title: "Claires et équitables",
				items: [
					{
						title: "Politique météo",
						paragraphs: [
							"La sécurité passe toujours avant l'itinéraire. Si le capitaine ou l'équipe jugent que le vent ou la mer ne permettent pas de réaliser l'activité en toute sécurité, vous pourrez reprogrammer le safari à une autre date disponible ou obtenir le remboursement.",
							"Nous ne pouvons pas contrôler le vent, mais nous pouvons être justes avec vous.",
						],
					},
					{
						title: "Politique d'annulation",
						paragraphs: [
							"Si vous annulez au moins 24 heures à l'avance, vous serez remboursé.",
							"Les annulations à moins de 24 heures ne sont pas remboursables — le bateau, l'équipement, les repas et la logistique sont déjà prêts — mais le montant peut être conservé comme crédit pour une future activité, selon disponibilité.",
						],
					},
				],
			},
			{
				type: "faq",
				kicker: "Questions fréquentes",
				title: "Tout ce que vous voulez savoir",
				items: [
					{ q: "Dois-je savoir nager ?", a: ["Pour profiter des séances de snorkeling, il est recommandé de savoir nager et de se sentir à l'aise en eau libre. Vous pouvez aussi rester dans le bateau pendant certaines rencontres. Prévenez-nous avant de réserver si quelqu'un du groupe ne sait pas nager afin d'évaluer si l'expérience est adaptée."] },
					{ q: "Est-il obligatoire d'entrer dans l'eau ?", a: ["Non. Une bonne partie du safari peut se vivre depuis le bateau ; certaines observations sont même meilleures depuis la surface. Entrer dans l'eau dépend de votre confort, de l'espèce, des conditions et de l'évaluation du guide."] },
					{ q: "Est-il garanti que nous verrons des orques ?", a: ["Non. Les orques sont des animaux sauvages et leur présence change chaque jour. Il existe des saisons plus favorables, mais aucune observation précise ne peut être garantie. Toute entreprise qui vous dit le contraire vous ment."] },
					{ q: "Pouvons-nous nager avec tous les animaux ?", a: ["Non. Entrer dans l'eau dépend de l'espèce, de son comportement, des conditions, de la sécurité et de la réglementation. Nager avec les baleines et les cachalots n'est pas autorisé dans les eaux mexicaines. Nous ne forçons jamais une interaction."] },
					{ q: "Quelle est la meilleure saison ?", a: ["Cela dépend de ce qui vous intéresse le plus. Le printemps et le début de l'été se distinguent par les agrégations de raies mobula ; durant les mois plus frais, différentes baleines peuvent apparaître. Dauphins, otaries et oiseaux peuvent être observés une grande partie de l'année."] },
					{ q: "Les enfants peuvent-ils participer ?", a: ["Sur les sorties partagées, l'âge minimum est de 14 ans. Les moins de 14 ans peuvent participer à un safari privé, où le guide adapte le rythme et leur accorde plus d'attention."] },
					{ q: "Que se passe-t-il si j'ai le mal de mer ?", a: ["Nous recommandons de manger léger, de rester hydraté et de prendre des mesures préventives si vous êtes sujet au mal de mer. Consultez à l'avance le médicament adapté et suivez les indications du produit ou de votre médecin."] },
					{ q: "Y a-t-il des toilettes sur le bateau ?", a: ["Non. Nous recommandons d'utiliser les sanitaires avant de partir, car l'expérience dure environ six heures."] },
					{ q: "Proposez-vous un transport depuis La Paz ?", a: ["Oui. Nous pouvons organiser un transport aller-retour pour 1 000 MXN supplémentaires pour un maximum de quatre personnes. À demander à l'avance, selon disponibilité."] },
					{ q: "Que se passe-t-il si je ne mange pas de poisson ou de crevettes ?", a: ["Prévenez-nous avant le départ pour examiner d'autres options. Vous pouvez aussi apporter vos propres snacks. Toute allergie doit être communiquée à l'avance."] },
					{ q: "Quand recevrai-je mes photos et vidéos ?", a: ["Généralement 1 à 3 jours après le safari, via le canal convenu avec l'équipe."] },
					{ q: "Puis-je apporter mon appareil photo ?", a: ["Oui, à vos risques et périls. Nous recommandons de le protéger de l'eau et de bien l'attacher. L'espace est limité, prévenez-nous si vous apportez du matériel volumineux ; une GoPro, une Insta360 ou un appareil compact ne posent pas de problème."] },
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/images/especies/ballena-atardecer.jpg", alt: "Baleine bondissant au coucher du soleil dans le golfe de Californie" },
				quote: "On ne choisit pas toujours le moment qui nous marquera. Mais on repart presque toujours avec l'envie de revenir.",
				align: "bottom",
			},
			{
				type: "prose",
				ink2: true,
				kicker: "Être eau et terre",
				heading: "Nous ne voulons pas seulement que vous voyiez des animaux. Nous voulons que vous compreniez pourquoi ils sont là.",
				paragraphs: [
					"Keabelmet est né de la curiosité de découvrir ce qui se passe là où le désert rencontre la mer. C'est pourquoi nos sorties sont menées par des personnes qui aiment l'aventure, mais qui connaissent aussi la biologie et le comportement de la faune que nous recherchons.",
					"Un dauphin n'est pas juste une nageoire près du bateau. Une raie mobula n'est pas juste un saut. Une baleine n'est pas juste une photo. Chaque comportement raconte une histoire — et quand vous comprenez ce que vous voyez, la rencontre devient encore plus puissante.",
				],
			},
			{
				type: "finalCta",
				image: "/images/orca-safari.jpg",
				alt: "Raies mobula et dauphins à La Ventana",
				title: "Vous partirez peut-être à la recherche d'orques ou de raies mobula. La mer aura peut-être d'autres plans.",
				text: "C'est ça, la partie palpitante. Dites-nous quand vous visitez la Basse-Californie du Sud et nous vous aiderons à choisir le meilleur moment pour vivre votre Ocean Safari à La Ventana et à l'île Cerralvo.",
				primaryLabel: "Vérifier les disponibilités",
				primaryWa: "Bonjour! Je voudrais vérifier les disponibilités pour l'Ocean Safari La Ventana",
				secondaryLabel: "Voir toutes les expéditions",
				secondaryHref: "/#expediciones",
			},
		],
	},
	"buceo-cabo-pulmo": {
		breadcrumb: "Plongée à Cabo Pulmo",
		hero: {
			image: "/coral-reef-underwater-diving-cabo-pulmo-colorful-f.jpg",
			alt: "Récif corallien vivant dans le parc national de Cabo Pulmo",
			kicker: "Cabo Pulmo · Parc National",
			title: "Il existe des endroits où la mer est vivante",
			text: "Cabo Pulmo en fait partie. Il y a quelques décennies, ce récif a failli disparaître ; aujourd'hui, c'est l'un des plus grands exemples de restauration marine de la planète. Ici, on ne vient pas chercher un poisson en particulier : on vient plonger dans un écosystème où des milliers de poissons se déplacent comme un seul organisme.",
			meta: "Cabo Pulmo · ~5 heures · Discovery, certifiés et snorkeling",
			primaryLabel: "Réserver ma plongée",
			primaryWa: "Bonjour! Je voudrais réserver une plongée à Cabo Pulmo",
			secondaryLabel: "Découvrir le déroulement de la journée",
			secondaryHref: "#itinerario",
		},
		blocks: [
			{
				type: "quickfacts",
				items: [
					{ value: "~5 heures", label: "Durée" },
					{ value: "8h · 12h", label: "Horaires" },
					{ value: "2 plongées", label: "Dans le parc national" },
					{ value: "12 ans", label: "Âge minimum" },
				],
			},
			{
				type: "prose",
				kicker: "Le récif qui est revenu à la vie",
				heading: "Un village a cessé de pêcher pour commencer à protéger. Et la nature a répondu.",
				paragraphs: [
					"Pendant de nombreuses années, Cabo Pulmo était un petit village de pêcheurs. Comme cela s'est produit dans tant d'endroits du monde, le récif a peu à peu commencé à perdre de sa vitalité. Jusqu'à ce que quelque chose d'extraordinaire se produise : les habitants eux-mêmes ont décidé d'arrêter de vivre de l'extraction de poissons pour commencer à les protéger.",
					{ lead: "C'était un pari énorme. Et la nature a répondu." },
					"Des décennies plus tard, Cabo Pulmo est considéré comme l'un des plus grands cas de restauration marine de la planète. La biomasse du récif a augmenté de façon spectaculaire, et aujourd'hui des milliers de poissons, tortues, raies, mérous et grands bancs remplissent à nouveau ces eaux.",
					"Quand vous plongez ici, vous ne visitez pas seulement un parc national : vous entrez dans une histoire de conservation qui continue de s'écrire chaque jour.",
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/buceo-cabo-pulmo-cardumen.jpg", alt: "Immense banc de poissons se déplaçant comme un seul organisme à Cabo Pulmo" },
				quote: "Ici, le protagoniste n'est pas un animal. C'est la quantité de vie.",
			},
			{
				type: "callout",
				ink2: true,
				heading: "Ce qui impressionne d'abord n'est pas une espèce. C'est de se sentir entouré de vie.",
				paragraphs: [
					"Il existe des plongées où un requin taureau attire toute l'attention. À Cabo Pulmo, c'est différent.",
					"Des bancs géants qui obscurcissent l'eau pendant quelques secondes. D'énormes mérous qui observent depuis le récif. Des tortues qui passent lentement, indifférentes à notre présence. Des raies qui se reposent sur le sable. Des milliers de poissons qui se déplacent en même temps, comme s'ils partageaient une seule pensée.",
					"Et, certains jours, des visiteurs inattendus qui arrivent du large pour nous rappeler que l'océan garde toujours une surprise de plus.",
				],
			},
			{
				type: "timeline",
				id: "itinerario",
				kicker: "Le déroulement de votre journée",
				title: "Du centre de plongée au récif",
				note: "L'ordre et les sites peuvent changer selon les conditions de la mer et l'attribution quotidienne du parc national.",
				items: [
					{
						time: "Point de rendez-vous · Cabo Pulmo",
						title: "Nous nous retrouvons à Cabo Pulmo",
						paragraphs: [
							"L'expérience commence au centre de plongée. Nous vous recommandons d'arriver quelques minutes à l'avance pour vous enregistrer calmement, vérifier l'équipement et utiliser les toilettes avant de partir.",
							"Vous y rencontrerez le divemaster qui vous accompagnera pendant toute l'activité. Selon la formule choisie, nous vérifierons l'équipement, discuterons du programme de la journée et répondrons à vos questions avant de rejoindre le bateau.",
						],
					},
					{
						title: "Le briefing",
						paragraphs: [
							"Avant d'entrer dans l'eau, nous prenons le temps nécessaire pour expliquer la plongée : le site attribué ce jour-là, les conditions de la mer, la profondeur maximale, les signaux de communication et tout ce qu'il faut pour profiter de l'expérience en toute tranquillité.",
							"Si c'est votre première plongée, vous apprendrez ici à respirer sous l'eau et à vous sentir à l'aise avant de commencer. Si vous êtes déjà plongeur certifié mais n'avez pas plongé depuis un moment, le divemaster adaptera le rythme à l'expérience du groupe.",
						],
					},
					{
						title: "Cap sur le récif",
						paragraphs: [
							"Nous montons à bord et naviguons vers le site attribué. C'est ici que se produit quelque chose que peu de gens connaissent : les sites de plongée ne sont pas choisis librement.",
							"Chaque matin, le parc national organise un tirage au sort entre les centres de plongée pour répartir les sites disponibles. Nous ne pouvons donc pas promettre un récif précis — et, curieusement, c'est justement l'une des raisons pour lesquelles Cabo Pulmo reste l'un des écosystèmes marins les plus sains. La nature passe toujours en premier.",
						],
						media: { suggest: "Plongeurs à bord de la panga naviguant vers le site de plongée, avec la côte désertique de Cabo Pulmo en arrière-plan." },
					},
					{
						title: "Le moment du saut",
						paragraphs: [
							"Il y a un instant que tout plongeur se rappelle. Vous mettez votre masque. Vous respirez profondément. Vous regardez en arrière. Et vous basculez dans l'eau.",
							"Soudain, le bruit du monde disparaît. Il ne reste que les bulles, la respiration et un récif qui semble avoir sa propre vie. Pendant la plongée, nous suivons le rythme du récif : nous ne poursuivons jamais les animaux, nous n'accélérons jamais l'expérience.",
						],
						media: { src: "/buceo-cabo-pulmo-buzo.jpg", alt: "Plongeur descendant sur le récif de Cabo Pulmo" },
					},
					{
						title: "Deuxième plongée",
						paragraphs: [
							"Après un intervalle en surface, nous effectuons une deuxième plongée. Souvent, le paysage change complètement : autre site, autre profondeur, autre faune.",
							"Deux plongées à Cabo Pulmo se ressemblent rarement. Et c'est précisément ce qui donne envie d'y revenir.",
						],
					},
				],
			},
			{
				type: "callout",
				heading: "Pourquoi ne promettons-nous pas un site précis ? Parce que ce ne serait pas honnête.",
				paragraphs: [
					"Chaque matin, le parc national attribue les sites de plongée par un système de rotation et de tirage au sort entre tous les opérateurs autorisés. Cette gestion réduit la pression sur le récif et aide à préserver l'un des écosystèmes marins les plus importants du golfe de Californie.",
					"Autrement dit : ne pas pouvoir choisir n'importe quel site est justement l'une des raisons pour lesquelles Cabo Pulmo reste aussi spectaculaire.",
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/coral-reef-underwater-cabo-pulmo-colorful-tropical.jpg", alt: "Récif corallien coloré à Cabo Pulmo" },
				quote: "Chaque descente est différente. Chaque respiration sous l'eau aussi.",
			},
			{
				type: "fauna",
				ink2: true,
				kicker: "Faune",
				title: "Le récif change chaque jour",
				note: "Nous ne pouvons garantir aucune espèce. Ce que nous pouvons garantir, c'est que chaque plongée se déroule dans l'un des récifs les plus sains de la planète.",
				tiers: [
					{ label: "Pendant une grande partie de l'année", species: ["Carangues", "Vivaneaux", "Mérous géants", "Tortues marines", "Raies", "Poissons de récif"] },
					{ label: "Certains jours, des visiteurs arrivent", warn: true, species: ["Requin taureau", "Raies mobula", "Dauphins", "Baleine à bosse", "Requin-baleine", "Requin tigre"] },
				],
			},
			{
				type: "video",
				kicker: "Une minute sous l'eau",
				title: "Regardez avant de le vivre",
				media: { suggest: "Vidéo cinématographique de 30-60s : le saut dans l'eau, un banc de poissons enveloppant le plongeur, un mérou géant, une tortue traversant le récif et des bulles remontant vers la surface." },
			},
			{
				type: "details",
				kicker: "Quelle option est faite pour vous ?",
				title: "Trois façons de vivre le récif",
				items: [
					{ title: "Discovery", text: "Vous n'avez jamais plongé ? Découvrez ce que l'on ressent en respirant sous l'eau. Aucune expérience préalable nécessaire : vous ferez deux plongées, toujours accompagné d'un instructeur certifié." },
					{ title: "Plongée certifiée", text: "Si vous détenez une certification Open Water ou supérieure, vous ferez deux plongées adaptées à l'expérience du groupe. Peu importe si cela fait longtemps que vous n'avez pas plongé : le divemaster ajustera le rythme." },
					{ title: "Snorkeling", text: "Si vous préférez rester en surface, vous pouvez aussi explorer Cabo Pulmo en snorkeling. Les groupes de snorkeling partent généralement sur un bateau distinct pour optimiser le temps de chacun ; si vous préférez rester ensemble, prévenez-nous à l'avance." },
				],
			},
			{
				type: "details",
				ink2: true,
				kicker: "Tout ce qui est inclus",
				title: "Ce qui est déjà pris en charge",
				items: [
					{ title: "Deux plongées", text: "En formule Discovery ou pour plongeurs certifiés, sur les sites attribués pour la journée." },
					{ title: "Équipement complet de plongée", text: "Tout le nécessaire pour la plongée." },
					{ title: "Instructeur ou divemaster certifié", text: "Vous accompagne et adapte le rythme à l'expérience du groupe." },
					{ title: "Bateau et capitaine local", text: "Avec une connaissance du parc et de ses conditions." },
					{ title: "Briefing de sécurité", text: "Explication complète avant d'entrer dans l'eau et sélection du site selon les conditions." },
					{ title: "Collations et eau", text: "De quoi s'hydrater à bord pendant la sortie." },
				],
			},
			{
				type: "info",
				kicker: "Avant de réserver",
				title: "Informations importantes",
				items: [
					{ label: "Âge minimum", value: "12 ans." },
					{ label: "Certification minimale", value: "Open Water pour la formule plongée certifiée." },
					{ label: "Photo et vidéo", value: "Cette activité n'inclut pas de service de photo ou vidéo." },
					{ label: "Transport", value: "Nous ne proposons pas de transport depuis La Paz vers Cabo Pulmo." },
					{ label: "Toilettes", value: "Le centre de plongée dispose de toilettes avant le départ. Le bateau n'en a pas, nous recommandons donc d'utiliser les installations avant l'embarquement." },
				],
			},
			{
				type: "pricing",
				id: "precios",
				kicker: "Tarifs",
				title: "Choisissez votre expérience à Cabo Pulmo",
				cards: [
					{
						name: "Discovery",
						amountMxn: 3800,
						amountNote: "/ personne",
						desc: "Votre première respiration sous l'eau, avec deux plongées accompagnées à tout moment par un instructeur certifié.",
						items: [
							"Deux plongées encadrées",
							"Aucune expérience préalable nécessaire",
							"Équipement complet de plongée",
							"Instructeur certifié pendant toute l'activité",
							"Collations et eau à bord",
						],
						waText: "Bonjour! Je voudrais réserver un Discovery de plongée à Cabo Pulmo",
						ctaLabel: "Réserver mon Discovery",
					},
					{
						name: "Plongée certifiée",
						amountMxn: 3200,
						amountNote: "/ personne",
						desc: "Deux plongées pour plongeurs Open Water ou supérieur, adaptées à l'expérience du groupe.",
						items: [
							"Deux plongées sur le récif",
							"Certification Open Water ou supérieure requise",
							"Équipement complet de plongée",
							"Divemaster certifié",
							"Collations et eau à bord",
						],
						waText: "Bonjour! Je voudrais réserver une plongée certifiée à Cabo Pulmo",
						ctaLabel: "Réserver une plongée certifiée",
						featured: true,
						featuredTag: "Certifiés",
					},
					{
						name: "Snorkeling",
						amountMxn: 1500,
						amountNote: "/ personne",
						desc: "Explorez le récif depuis la surface accompagné d'un guide.",
						items: [
							"Sortie de snorkeling encadrée",
							"Idéal pour ceux qui préfèrent ne pas plonger",
							"Équipement de snorkeling",
							"Guide pendant toute l'activité",
						],
						waText: "Bonjour! Je voudrais réserver du snorkeling à Cabo Pulmo",
						ctaLabel: "Réserver le snorkeling",
					},
				],
			},
			{
				type: "policies",
				ink2: true,
				kicker: "Politiques",
				title: "Claires et équitables",
				items: [
					{
						title: "Politique météo",
						paragraphs: [
							"Si la météo ne permet pas de réaliser l'activité en toute sécurité, vous pourrez choisir entre reprogrammer votre sortie ou obtenir un remboursement complet. La sécurité passe toujours avant l'itinéraire.",
						],
					},
					{
						title: "Politique d'annulation",
						paragraphs: [
							"Si vous annulez plus de 24 heures à l'avance, vous pourrez demander un remboursement ou conserver votre paiement comme crédit pour une future expérience avec Keabelmet.",
						],
					},
				],
			},
			{
				type: "mediaBanner",
				media: { src: "/images/buceo-cabo-pulmo.jpeg", alt: "Plongeur explorant le récif du parc national de Cabo Pulmo" },
				quote: "On ne choisit pas toujours le moment qui nous marquera. Mais on repart presque toujours avec l'envie de revenir.",
				align: "bottom",
			},
			{
				type: "finalCta",
				image: "/buceo-cabo-pulmo-cardumen.jpg",
				alt: "Immense banc de poissons sur le récif de Cabo Pulmo",
				title: "Vous vous souviendrez peut-être d'un requin taureau. Ou d'un banc de milliers de poissons se déplaçant comme un seul organisme.",
				text: "C'est ça, Cabo Pulmo. Dites-nous quand vous visitez la Basse-Californie du Sud et nous vous aiderons à choisir le meilleur jour pour plonger dans l'un des récifs les plus vivants de la planète.",
				primaryLabel: "Vérifier les disponibilités",
				primaryWa: "Bonjour! Je voudrais vérifier les disponibilités pour plonger à Cabo Pulmo",
				secondaryLabel: "Voir toutes les expéditions",
				secondaryHref: "/#expediciones",
			},
		],
	},
	"tiburon-ballena": {
		breadcrumb: "Requin-baleine",
		hero: {
			image: "/tiburon-ballena-drone.jpg",
			alt: "Requin-baleine nageant près de la surface à La Paz",
			kicker: "La Paz · Requin-baleine",
			title: "Nagez aux côtés du plus grand poisson de la planète",
			text: "Pas pour le poursuivre. Pas pour le toucher. Simplement pour l'accompagner quelques minutes. Le requin-baleine peut dépasser dix mètres et pourtant se nourrir d'organismes minuscules. Partager l'eau avec lui ne ressemble pas à une aventure extrême : cela se ressent comme un privilège.",
			meta: "Malecón de La Paz · 2-3 heures · Saison oct-avril",
			primaryLabel: "Réserver ma rencontre",
			primaryWa: "Bonjour! Je voudrais réserver la nage avec les requins-baleines à La Paz",
			secondaryLabel: "Découvrir l'expérience",
			secondaryHref: "#itinerario",
		},
		blocks: [
			{
				type: "quickfacts",
				items: [
					{ value: "2-3 heures", label: "Durée approx." },
					{ value: "Oct - avril", label: "Saison" },
					{ value: "12 ans", label: "Âge minimum" },
					{ value: "Malecón de La Paz", label: "Point de rendez-vous" },
				],
			},
			{
				type: "prose",
				kicker: "Le géant le plus noble de l'océan",
				heading: "Sa véritable caractéristique n'est pas sa taille. C'est sa tranquillité.",
				paragraphs: [
					"Certains animaux inspirent le respect par leur taille. Le requin-baleine aussi. Mais il suffit de quelques secondes pour découvrir que ce qui impressionne vraiment n'est pas sa taille, mais son calme.",
					"Il nage lentement. Il ignore notre présence. Et il poursuit son chemin en se nourrissant de plancton près de la surface.",
					{ lead: "Nous ne sommes pas face à un prédateur. Nous sommes face à l'un des animaux les plus pacifiques qui peuplent l'océan." },
					"Pendant quelques minutes, nous pourrons l'accompagner, toujours en respectant son espace et les règles qui rendent cette rencontre possible.",
				],
			},
			{
				type: "mediaBanner",
				media: { suggest: "Photographie aérienne géante du requin-baleine occupant toute la largeur de l'écran, avec un nageur à côté pour donner l'échelle." },
				quote: "Il n'est pas nécessaire de toucher quelque chose pour s'en souvenir toute sa vie.",
			},
			{
				type: "timeline",
				id: "itinerario",
				kicker: "Le déroulement de l'expérience",
				title: "Du malecón à la rencontre",
				note: "Nous ne suivons pas un itinéraire établi : nous recherchons les meilleures conditions et les spécimens qui se nourrissent près de la surface.",
				items: [
					{
						time: "Point de rendez-vous · Malecón de La Paz",
						title: "Nous nous retrouvons et faisons le briefing",
						paragraphs: [
							"Après nous être réunis avec l'équipe, nous faisons un bref briefing où nous expliquons le déroulement de l'activité, revoyons les règles de la zone protégée et répondons à vos questions avant de monter à bord.",
						],
					},
					{
						title: "La recherche commence",
						paragraphs: [
							"Une fois sur l'eau, la recherche commence. Nous ne suivons pas d'itinéraire fixe : nous localisons les spécimens qui se nourrissent près de la surface. Quand nous en trouvons un, nous attendons notre tour et nous préparons à entrer dans l'eau.",
						],
						media: { suggest: "Vue depuis le bateau du guide indiquant l'aileron d'un requin-baleine à la surface, avec le groupe prêt avec palmes et tuba." },
					},
					{
						title: "Quelques minutes aux côtés du géant",
						paragraphs: [
							"C'est là que se produit ce que tout le monde vient chercher. Pendant quelques minutes, nous nageons aux côtés du requin-baleine, toujours en respectant la distance autorisée et en suivant les indications du guide. Puis nous remontons à bord et recommençons la recherche.",
							"Chaque rencontre est brève. Mais très peu de gens l'oublient.",
						],
						media: { suggest: "Nageur avec tuba à distance respectueuse du requin-baleine, prise depuis la surface avec une lumière turquoise." },
					},
				],
			},
			{
				type: "seasons",
				ink2: true,
				kicker: "Choisissez votre horaire",
				title: "Trois sorties par jour selon les conditions",
				intro: "Nous proposons trois horaires de départ pendant la saison pour profiter des meilleures conditions de la journée. Aucun horaire n'est meilleur qu'un autre : chacun se déroule différemment selon le comportement naturel des animaux.",
				items: [
					{ name: "Sortie du matin · notre recommandation", text: "Rendez-vous à 7h, départ à 8h. Durée approx. 3 heures. C'est la sortie la plus longue de la journée : étant la première du matin, une partie de l'expérience consiste à localiser les requins avant les entrées dans l'eau. Si vous avez de la flexibilité, c'est celle que nous recommandons le plus." },
					{ name: "Sortie de milieu de matinée", text: "Rendez-vous à 10h, départ à 11h. Durée approx. 2 heures. Les requins sont généralement déjà mieux repérés grâce à la première sortie, le temps de recherche est donc réduit et l'expérience est mieux optimisée." },
					{ name: "Sortie de midi", text: "Rendez-vous à 12h, départ à 13h. Durée approx. 2 heures. Même dynamique que le deuxième créneau : les spécimens sont généralement déjà localisés, ce qui permet de nous diriger plus rapidement vers la zone d'observation." },
				],
			},
			{
				type: "callout",
				heading: "Ici, on ne vient pas poursuivre les animaux. On vient partager l'eau avec eux.",
				paragraphs: [
					"Quand nous entrons dans l'eau, c'est nous qui devons nous adapter. Nous ne bloquons jamais son chemin. Nous ne nageons jamais devant lui. Nous n'essayons jamais de le toucher.",
					"Nous l'accompagnons simplement pendant une toute petite partie de son parcours. Et nous pensons que c'est la meilleure façon de vivre cette expérience.",
				],
			},
			{
				type: "callout",
				ink2: true,
				heading: "Pourquoi la rencontre est-elle si courte ? Parce que protéger le requin-baleine est plus important que prolonger l'expérience.",
				paragraphs: [
					"L'activité est réglementée par des autorités environnementales qui limitent le temps d'observation, le nombre de bateaux et la façon dont nous pouvons nous approcher.",
					"Loin d'être un inconvénient, ces règles sont précisément ce qui permet à des milliers de personnes de continuer à profiter de cette rencontre chaque saison. Vous ne venez pas seulement rencontrer le requin-baleine : vous venez aussi apprendre à cohabiter avec lui de manière responsable.",
				],
			},
			{
				type: "prose",
				kicker: "Chaque jour est différent",
				heading: "Nous travaillons avec des animaux complètement libres.",
				paragraphs: [
					"Certains jours, nous trouvons plusieurs spécimens. D'autres, nous devons les chercher plus longtemps. Certains nagent lentement en se nourrissant ; d'autres disparaissent sous l'eau quelques secondes après que nous les ayons trouvés.",
					{ lead: "Nous pensons que cette incertitude rend chaque rencontre encore plus précieuse." },
				],
			},
			{
				type: "checklist",
				kicker: "Est-ce fait pour vous ?",
				title: "Pour réserver avec des attentes claires",
				good: {
					title: "Cette expérience est idéale si…",
					items: [
						"Vous avez toujours rêvé de nager aux côtés d'un requin-baleine.",
						"Vous n'avez aucune expérience préalable de snorkeling.",
						"Vous voulez vivre une rencontre responsable avec la faune sauvage.",
						"Vous cherchez une activité adaptée à presque toute la famille.",
					],
				},
				bad: {
					title: "Ce n'est peut-être pas pour vous si…",
					items: [
						"Vous vous attendez à contrôler le comportement des animaux.",
						"Vous cherchez une expérience où tout est garanti.",
					],
				},
			},
			{
				type: "details",
				kicker: "Tout ce qui est inclus",
				title: "Ce qui est déjà pris en charge",
				items: [
					{ title: "Bateau autorisé", text: "Avec un permis pour l'activité dans la zone protégée." },
					{ title: "Guide certifié", text: "Vous accompagne et explique les règles de la rencontre à tout moment." },
					{ title: "Équipement complet de snorkeling", text: "Masque, tuba et palmes." },
					{ title: "Combinaison néoprène", text: "Incluse selon la saison et la température de l'eau." },
					{ title: "Gilet de flottaison", text: "Pour profiter de la rencontre en toute tranquillité." },
					{ title: "Briefing de sécurité", text: "Explication complète avant d'entrer dans l'eau." },
				],
			},
			{
				type: "info",
				ink2: true,
				kicker: "Avant de réserver",
				title: "Informations importantes",
				items: [
					{ label: "Durée", value: "Environ 2-3 heures selon l'horaire." },
					{ label: "Saison", value: "D'octobre à avril." },
					{ label: "Âge minimum", value: "12 ans." },
					{ label: "Point de rendez-vous", value: "Malecón de La Paz." },
					{ label: "Photo et vidéo", value: "Cette activité n'inclut pas de service de photo ou vidéo." },
				],
			},
			{
				type: "pricing",
				id: "precios",
				kicker: "Tarif",
				title: "Réservez votre rencontre",
				cards: [
					{
						name: "Nage avec les requins-baleines",
						amountMxn: 1800,
						amountNote: "/ personne",
						desc: "Une expérience adaptée à presque toute la famille, sans expérience préalable de snorkeling nécessaire.",
						items: [
							"Bateau autorisé et guide certifié",
							"Équipement complet de snorkeling et combinaison",
							"Gilet de flottaison",
							"Briefing de sécurité",
							"Saison d'octobre à avril",
						],
						waText: "Bonjour! Je voudrais réserver la nage avec les requins-baleines à La Paz",
						ctaLabel: "Réserver ma rencontre",
						featured: true,
						featuredTag: "Oct - avril",
					},
				],
			},
			{
				type: "mediaBanner",
				media: { suggest: "Silhouette du requin-baleine vue d'en dessous à contre-jour de la surface, sensation de calme et d'échelle." },
				quote: "Vous arriverez peut-être en pensant à sa taille. Mais vous repartirez probablement en vous souvenant de sa tranquillité.",
				align: "bottom",
			},
			{
				type: "finalCta",
				image: "/tiburon-ballena-drone.jpg",
				alt: "Requin-baleine dans les eaux de La Paz",
				title: "Certaines rencontres durent quelques minutes et pourtant restent avec vous pendant de nombreuses années.",
				text: "Quand vous partagez l'eau avec le plus grand poisson de la planète, vous découvrez que certaines des créatures les plus impressionnantes de l'océan peuvent aussi être les plus pacifiques. Dites-nous quand vous visitez La Paz et nous vous aiderons à choisir votre horaire.",
				primaryLabel: "Vérifier les disponibilités",
				primaryWa: "Bonjour! Je voudrais vérifier les disponibilités pour nager avec les requins-baleines",
				secondaryLabel: "Voir toutes les expéditions",
				secondaryHref: "/#expediciones",
			},
		],
	},
}
